version: '3.6'

services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      ## Expose the port for tooling (SQL language server in IDE, connecting with GUI's etc)
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgrespassword

  #  graphql-engine:
  #    image: hasura/graphql-engine:v2.7.0.cli-migrations-v3
  #    volumes:
  #      - ./hasura/migrations:/hasura-migrations
  #      - ./hasura/metadata:/hasura-metadata
  #    ports:
  #      - '8080:8080'
  #    depends_on:
  #      - 'postgres'
  #    restart: always
  #    environment:
  #      ## Actions endpoint
  #      NEXTJS_SERVER_URL: http://host.docker.internal:3000
  #      ## postgres database to store Hasura metadata
  #      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  #      ## this env var can be used to add the above postgres database to Hasura as a data source.
  #      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  #      HEROKU_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  #      ## enable debugging mode. It is recommended to disable this in production
  #      HASURA_GRAPHQL_DEV_MODE: 'true'
  #      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  #      ## uncomment next line to set an admin secret
  #      HASURA_GRAPHQL_AUTH_HOOK: http://host.docker.internal:3000/api/hasuraAuthWebhook
  #      HASURA_GRAPHQL_ADMIN_SECRET: admin-secret

  graphql-engine:
    build:
      context: ./hasura
      args:
        BACKEND_HOST: host.docker.internal:3000/api
        AUTH_HOOK_PATH: hasuraAuthWebhook
        ACTION_BASE_PATH: actions
        REMOTE_SCHEMA_PATH: remote-schemas/graphql
        TRIGGERS_PATH: triggers
    depends_on:
      - 'postgres'
    ports:
      - '8080:8080'
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HEROKU_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: admin-secret
      HASURA_GRAPHQL_DEV_MODE: true
volumes:
  db_data:
