/* eslint-disable */

export const AllTypesProps: Record<string, any> = {
  Query: {
    brands: {
      filter: 'brands_filter',
    },
    brands_by_id: {},
    brands_aggregated: {
      filter: 'brands_filter',
    },
    brands_directus_users: {
      filter: 'brands_directus_users_filter',
    },
    brands_directus_users_by_id: {},
    brands_directus_users_aggregated: {
      filter: 'brands_directus_users_filter',
    },
    collaborators: {
      filter: 'collaborators_filter',
    },
    collaborators_by_id: {},
    collaborators_aggregated: {
      filter: 'collaborators_filter',
    },
    collaborator_roles: {
      filter: 'collaborator_roles_filter',
    },
    collaborator_roles_by_id: {},
    collaborator_roles_aggregated: {
      filter: 'collaborator_roles_filter',
    },
    junction_directus_users_skills: {
      filter: 'junction_directus_users_skills_filter',
    },
    junction_directus_users_skills_by_id: {},
    junction_directus_users_skills_aggregated: {
      filter: 'junction_directus_users_skills_filter',
    },
    skills: {
      filter: 'skills_filter',
    },
    skills_by_id: {},
    skills_aggregated: {
      filter: 'skills_filter',
    },
    producers: {
      filter: 'producers_filter',
    },
    producers_by_id: {},
    producers_aggregated: {
      filter: 'producers_filter',
    },
    producers_production_materials: {
      filter: 'producers_production_materials_filter',
    },
    producers_production_materials_by_id: {},
    producers_production_materials_aggregated: {
      filter: 'producers_production_materials_filter',
    },
    producers_production_methods: {
      filter: 'producers_production_methods_filter',
    },
    producers_production_methods_by_id: {},
    producers_production_methods_aggregated: {
      filter: 'producers_production_methods_filter',
    },
    production_methods: {
      filter: 'production_methods_filter',
    },
    production_methods_by_id: {},
    production_methods_aggregated: {
      filter: 'production_methods_filter',
    },
    production_materials_production_methods: {
      filter: 'production_materials_production_methods_filter',
    },
    production_materials_production_methods_by_id: {},
    production_materials_production_methods_aggregated: {
      filter: 'production_materials_production_methods_filter',
    },
    fulfillers: {
      filter: 'fulfillers_filter',
    },
    fulfillers_by_id: {},
    fulfillers_aggregated: {
      filter: 'fulfillers_filter',
    },
    price_currencies: {
      filter: 'price_currencies_filter',
    },
    price_currencies_by_id: {},
    price_currencies_aggregated: {
      filter: 'price_currencies_filter',
    },
    stages: {
      filter: 'stages_filter',
    },
    stages_by_id: {},
    stages_aggregated: {
      filter: 'stages_filter',
    },
    currencies: {
      filter: 'currencies_filter',
    },
    currencies_by_id: {},
    currencies_aggregated: {
      filter: 'currencies_filter',
    },
    products_content: {
      filter: 'products_content_filter',
    },
    products_content_by_id: {},
    products_content_aggregated: {
      filter: 'products_content_filter',
    },
    products_contributors: {
      filter: 'products_contributors_filter',
    },
    products_contributors_by_id: {},
    products_contributors_aggregated: {
      filter: 'products_contributors_filter',
    },
    products_design_files: {
      filter: 'products_design_files_filter',
    },
    products_design_files_by_id: {},
    products_design_files_aggregated: {
      filter: 'products_design_files_filter',
    },
    products_files: {
      filter: 'products_files_filter',
    },
    products_files_by_id: {},
    products_files_aggregated: {
      filter: 'products_files_filter',
    },
    products_production_materials: {
      filter: 'products_production_materials_filter',
    },
    products_production_materials_by_id: {},
    products_production_materials_aggregated: {
      filter: 'products_production_materials_filter',
    },
    products_production_methods: {
      filter: 'products_production_methods_filter',
    },
    products_production_methods_by_id: {},
    products_production_methods_aggregated: {
      filter: 'products_production_methods_filter',
    },
    products_wearables: {
      filter: 'products_wearables_filter',
    },
    products_wearables_by_id: {},
    products_wearables_aggregated: {
      filter: 'products_wearables_filter',
    },
    file_formats: {
      filter: 'file_formats_filter',
    },
    file_formats_by_id: {},
    file_formats_aggregated: {
      filter: 'file_formats_filter',
    },
    products: {
      filter: 'products_filter',
    },
    products_by_id: {},
    products_aggregated: {
      filter: 'products_filter',
    },
    production_materials: {
      filter: 'production_materials_filter',
    },
    production_materials_by_id: {},
    production_materials_aggregated: {
      filter: 'production_materials_filter',
    },
    invoices: {
      filter: 'invoices_filter',
    },
    invoices_by_id: {},
    invoices_aggregated: {
      filter: 'invoices_filter',
    },
  },
  brands: {
    logo: {
      filter: 'directus_files_filter',
    },
    products: {
      filter: 'products_filter',
    },
    users: {
      filter: 'brands_directus_users_filter',
    },
  },
  Date: `scalar.Date` as const,
  directus_files: {
    folder: {
      filter: 'directus_folders_filter',
    },
    uploaded_by: {
      filter: 'directus_users_filter',
    },
    modified_by: {
      filter: 'directus_users_filter',
    },
  },
  directus_folders: {
    parent: {
      filter: 'directus_folders_filter',
    },
  },
  directus_folders_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    parent: 'directus_folders_filter',
    _and: 'directus_folders_filter',
    _or: 'directus_folders_filter',
  },
  string_filter_operators: {},
  directus_users: {
    avatar: {
      filter: 'directus_files_filter',
    },
    role: {
      filter: 'directus_roles_filter',
    },
    collaborators: {
      filter: 'collaborators_filter',
    },
    skills: {
      filter: 'junction_directus_users_skills_filter',
    },
  },
  Hash: `scalar.Hash` as const,
  JSON: `scalar.JSON` as const,
  directus_files_filter: {
    id: 'string_filter_operators',
    storage: 'string_filter_operators',
    filename_disk: 'string_filter_operators',
    filename_download: 'string_filter_operators',
    title: 'string_filter_operators',
    type: 'string_filter_operators',
    folder: 'directus_folders_filter',
    uploaded_by: 'directus_users_filter',
    uploaded_on: 'date_filter_operators',
    uploaded_on_func: 'datetime_function_filter_operators',
    modified_by: 'directus_users_filter',
    modified_on: 'date_filter_operators',
    modified_on_func: 'datetime_function_filter_operators',
    charset: 'string_filter_operators',
    filesize: 'number_filter_operators',
    width: 'number_filter_operators',
    height: 'number_filter_operators',
    duration: 'number_filter_operators',
    embed: 'string_filter_operators',
    description: 'string_filter_operators',
    location: 'string_filter_operators',
    tags: 'string_filter_operators',
    tags_func: 'count_function_filter_operators',
    metadata: 'string_filter_operators',
    metadata_func: 'count_function_filter_operators',
    _and: 'directus_files_filter',
    _or: 'directus_files_filter',
  },
  directus_users_filter: {
    id: 'string_filter_operators',
    first_name: 'string_filter_operators',
    last_name: 'string_filter_operators',
    email: 'string_filter_operators',
    password: 'hash_filter_operators',
    location: 'string_filter_operators',
    title: 'string_filter_operators',
    description: 'string_filter_operators',
    tags: 'string_filter_operators',
    tags_func: 'count_function_filter_operators',
    avatar: 'directus_files_filter',
    language: 'string_filter_operators',
    theme: 'string_filter_operators',
    tfa_secret: 'hash_filter_operators',
    status: 'string_filter_operators',
    role: 'directus_roles_filter',
    token: 'hash_filter_operators',
    last_access: 'date_filter_operators',
    last_access_func: 'datetime_function_filter_operators',
    last_page: 'string_filter_operators',
    provider: 'string_filter_operators',
    external_identifier: 'string_filter_operators',
    auth_data: 'string_filter_operators',
    auth_data_func: 'count_function_filter_operators',
    email_notifications: 'boolean_filter_operators',
    discord_handle: 'string_filter_operators',
    discord_id: 'string_filter_operators',
    timezone: 'string_filter_operators',
    twitter_handle: 'string_filter_operators',
    collaborators: 'collaborators_filter',
    collaborators_func: 'count_function_filter_operators',
    skills: 'junction_directus_users_skills_filter',
    skills_func: 'count_function_filter_operators',
    _and: 'directus_users_filter',
    _or: 'directus_users_filter',
  },
  hash_filter_operators: {},
  count_function_filter_operators: {
    count: 'number_filter_operators',
  },
  number_filter_operators: {
    _eq: 'GraphQLStringOrFloat',
    _neq: 'GraphQLStringOrFloat',
    _in: 'GraphQLStringOrFloat',
    _nin: 'GraphQLStringOrFloat',
    _gt: 'GraphQLStringOrFloat',
    _gte: 'GraphQLStringOrFloat',
    _lt: 'GraphQLStringOrFloat',
    _lte: 'GraphQLStringOrFloat',
    _between: 'GraphQLStringOrFloat',
    _nbetween: 'GraphQLStringOrFloat',
  },
  GraphQLStringOrFloat: `scalar.GraphQLStringOrFloat` as const,
  directus_roles_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    icon: 'string_filter_operators',
    description: 'string_filter_operators',
    ip_access: 'string_filter_operators',
    enforce_tfa: 'boolean_filter_operators',
    admin_access: 'boolean_filter_operators',
    app_access: 'boolean_filter_operators',
    users: 'directus_users_filter',
    users_func: 'count_function_filter_operators',
    _and: 'directus_roles_filter',
    _or: 'directus_roles_filter',
  },
  boolean_filter_operators: {},
  date_filter_operators: {
    _between: 'GraphQLStringOrFloat',
    _nbetween: 'GraphQLStringOrFloat',
  },
  datetime_function_filter_operators: {
    year: 'number_filter_operators',
    month: 'number_filter_operators',
    week: 'number_filter_operators',
    day: 'number_filter_operators',
    weekday: 'number_filter_operators',
    hour: 'number_filter_operators',
    minute: 'number_filter_operators',
    second: 'number_filter_operators',
  },
  collaborators_filter: {
    account: 'directus_users_filter',
    date_created: 'date_filter_operators',
    date_created_func: 'datetime_function_filter_operators',
    date_updated: 'date_filter_operators',
    date_updated_func: 'datetime_function_filter_operators',
    display_name: 'string_filter_operators',
    id: 'number_filter_operators',
    payment_eth_address: 'string_filter_operators',
    role: 'collaborator_roles_filter',
    user_created: 'directus_users_filter',
    _and: 'collaborators_filter',
    _or: 'collaborators_filter',
  },
  collaborator_roles_filter: {
    description: 'string_filter_operators',
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    _and: 'collaborator_roles_filter',
    _or: 'collaborator_roles_filter',
  },
  junction_directus_users_skills_filter: {
    directus_users_id: 'directus_users_filter',
    id: 'number_filter_operators',
    skills_id: 'skills_filter',
    _and: 'junction_directus_users_skills_filter',
    _or: 'junction_directus_users_skills_filter',
  },
  skills_filter: {
    description: 'string_filter_operators',
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    _and: 'skills_filter',
    _or: 'skills_filter',
  },
  directus_roles: {
    users: {
      filter: 'directus_users_filter',
    },
  },
  collaborators: {
    account: {
      filter: 'directus_users_filter',
    },
    role: {
      filter: 'collaborator_roles_filter',
    },
    user_created: {
      filter: 'directus_users_filter',
    },
  },
  junction_directus_users_skills: {
    directus_users_id: {
      filter: 'directus_users_filter',
    },
    skills_id: {
      filter: 'skills_filter',
    },
  },
  GraphQLBigInt: `scalar.GraphQLBigInt` as const,
  products: {
    brand_id: {
      filter: 'brands_filter',
    },
    clo3d_file: {
      filter: 'directus_files_filter',
    },
    fulfiller_id: {
      filter: 'fulfillers_filter',
    },
    price: {
      filter: 'price_currencies_filter',
    },
    producer_id: {
      filter: 'producers_filter',
    },
    product_stage: {
      filter: 'stages_filter',
    },
    sale_currency: {
      filter: 'currencies_filter',
    },
    contributors: {
      filter: 'products_contributors_filter',
    },
    design_files: {
      filter: 'products_design_files_filter',
    },
    content: {
      filter: 'products_content_filter',
    },
    images: {
      filter: 'products_files_filter',
    },
    materials: {
      filter: 'products_production_materials_filter',
    },
    wearable_files: {
      filter: 'products_wearables_filter',
    },
    production_methods: {
      filter: 'products_production_methods_filter',
    },
    client_invoices: {
      filter: 'invoices_filter',
    },
    production_invoices: {
      filter: 'invoices_filter',
    },
  },
  brands_filter: {
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    description: 'string_filter_operators',
    discord_url: 'string_filter_operators',
    eth_address: 'string_filter_operators',
    id: 'number_filter_operators',
    logo: 'directus_files_filter',
    name: 'string_filter_operators',
    notion_id: 'string_filter_operators',
    twitter_url: 'string_filter_operators',
    website_url: 'string_filter_operators',
    products: 'products_filter',
    products_func: 'count_function_filter_operators',
    users: 'brands_directus_users_filter',
    users_func: 'count_function_filter_operators',
    _and: 'brands_filter',
    _or: 'brands_filter',
  },
  products_filter: {
    brand_id: 'brands_filter',
    clo3d_file: 'directus_files_filter',
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    description: 'string_filter_operators',
    discord_channel_id: 'string_filter_operators',
    fulfiller_id: 'fulfillers_filter',
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    nft_token_id: 'number_filter_operators',
    notion_id: 'string_filter_operators',
    price: 'price_currencies_filter',
    producer_id: 'producers_filter',
    product_stage: 'stages_filter',
    production_cost: 'number_filter_operators',
    quantity: 'number_filter_operators',
    release_date: 'date_filter_operators',
    release_date_func: 'datetime_function_filter_operators',
    sale_currency: 'currencies_filter',
    sale_price: 'number_filter_operators',
    sale_type: 'string_filter_operators',
    season: 'number_filter_operators',
    shopify_id: 'string_filter_operators',
    status: 'string_filter_operators',
    notes: 'string_filter_operators',
    contributors: 'products_contributors_filter',
    contributors_func: 'count_function_filter_operators',
    design_files: 'products_design_files_filter',
    design_files_func: 'count_function_filter_operators',
    content: 'products_content_filter',
    content_func: 'count_function_filter_operators',
    images: 'products_files_filter',
    images_func: 'count_function_filter_operators',
    materials: 'products_production_materials_filter',
    materials_func: 'count_function_filter_operators',
    wearable_files: 'products_wearables_filter',
    wearable_files_func: 'count_function_filter_operators',
    production_methods: 'products_production_methods_filter',
    production_methods_func: 'count_function_filter_operators',
    client_invoices: 'invoices_filter',
    client_invoices_func: 'count_function_filter_operators',
    production_invoices: 'invoices_filter',
    production_invoices_func: 'count_function_filter_operators',
    _and: 'products_filter',
    _or: 'products_filter',
  },
  fulfillers_filter: {
    address: 'string_filter_operators',
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    email: 'string_filter_operators',
    eth_address: 'string_filter_operators',
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    website_url: 'string_filter_operators',
    _and: 'fulfillers_filter',
    _or: 'fulfillers_filter',
  },
  price_currencies_filter: {
    amount: 'number_filter_operators',
    currency: 'string_filter_operators',
    id: 'number_filter_operators',
    _and: 'price_currencies_filter',
    _or: 'price_currencies_filter',
  },
  producers_filter: {
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    email: 'string_filter_operators',
    eth_address: 'string_filter_operators',
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    shipping_address: 'string_filter_operators',
    production_materials_stocked: 'producers_production_materials_filter',
    production_materials_stocked_func: 'count_function_filter_operators',
    production_methods: 'producers_production_methods_filter',
    production_methods_func: 'count_function_filter_operators',
    supplied_materials: 'production_materials_filter',
    supplied_materials_func: 'count_function_filter_operators',
    _and: 'producers_filter',
    _or: 'producers_filter',
  },
  producers_production_materials_filter: {
    id: 'number_filter_operators',
    producers_id: 'producers_filter',
    production_materials_id: 'production_materials_filter',
    quantity: 'number_filter_operators',
    _and: 'producers_production_materials_filter',
    _or: 'producers_production_materials_filter',
  },
  production_materials_filter: {
    base_price: 'number_filter_operators',
    color_palette: 'string_filter_operators',
    color_palette_func: 'count_function_filter_operators',
    composition: 'string_filter_operators',
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    created_by: 'directus_users_filter',
    description: 'string_filter_operators',
    gender: 'string_filter_operators',
    id: 'number_filter_operators',
    made_in: 'string_filter_operators',
    name: 'string_filter_operators',
    neck_tag: 'boolean_filter_operators',
    note: 'string_filter_operators',
    rating: 'string_filter_operators',
    size_guide: 'directus_files_filter',
    supplier: 'producers_filter',
    tags: 'string_filter_operators',
    tags_func: 'count_function_filter_operators',
    production_methods: 'production_materials_production_methods_filter',
    production_methods_func: 'count_function_filter_operators',
    stocked_at: 'producers_production_materials_filter',
    stocked_at_func: 'count_function_filter_operators',
    _and: 'production_materials_filter',
    _or: 'production_materials_filter',
  },
  production_materials_production_methods_filter: {
    id: 'number_filter_operators',
    production_materials_id: 'production_materials_filter',
    production_methods_id: 'production_methods_filter',
    _and: 'production_materials_production_methods_filter',
    _or: 'production_materials_production_methods_filter',
  },
  production_methods_filter: {
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    description: 'string_filter_operators',
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    producers: 'producers_production_methods_filter',
    producers_func: 'count_function_filter_operators',
    production_materials: 'production_materials_production_methods_filter',
    production_materials_func: 'count_function_filter_operators',
    _and: 'production_methods_filter',
    _or: 'production_methods_filter',
  },
  producers_production_methods_filter: {
    id: 'number_filter_operators',
    producers_id: 'producers_filter',
    production_methods_id: 'production_methods_filter',
    _and: 'producers_production_methods_filter',
    _or: 'producers_production_methods_filter',
  },
  stages_filter: {
    description: 'string_filter_operators',
    name: 'string_filter_operators',
    sort: 'number_filter_operators',
    _and: 'stages_filter',
    _or: 'stages_filter',
  },
  currencies_filter: {
    currency: 'string_filter_operators',
    id: 'number_filter_operators',
    _and: 'currencies_filter',
    _or: 'currencies_filter',
  },
  products_contributors_filter: {
    collaborators_id: 'collaborators_filter',
    contribution_share: 'number_filter_operators',
    id: 'number_filter_operators',
    products_id: 'products_filter',
    robot_earned: 'number_filter_operators',
    _and: 'products_contributors_filter',
    _or: 'products_contributors_filter',
  },
  products_design_files_filter: {
    directus_files_id: 'directus_files_filter',
    id: 'number_filter_operators',
    products_id: 'products_filter',
    _and: 'products_design_files_filter',
    _or: 'products_design_files_filter',
  },
  products_content_filter: {
    directus_files_id: 'directus_files_filter',
    id: 'number_filter_operators',
    products_id: 'products_filter',
    _and: 'products_content_filter',
    _or: 'products_content_filter',
  },
  products_files_filter: {
    directus_files_id: 'directus_files_filter',
    id: 'number_filter_operators',
    products_id: 'products_filter',
    _and: 'products_files_filter',
    _or: 'products_files_filter',
  },
  products_production_materials_filter: {
    id: 'number_filter_operators',
    production_materials_id: 'production_materials_filter',
    products_id: 'products_filter',
    _and: 'products_production_materials_filter',
    _or: 'products_production_materials_filter',
  },
  products_wearables_filter: {
    directus_files_id: 'directus_files_filter',
    file_format: 'file_formats_filter',
    id: 'number_filter_operators',
    primary: 'boolean_filter_operators',
    products_id: 'products_filter',
    _and: 'products_wearables_filter',
    _or: 'products_wearables_filter',
  },
  file_formats_filter: {
    description: 'string_filter_operators',
    extension: 'string_filter_operators',
    id: 'number_filter_operators',
    mime_type: 'string_filter_operators',
    name: 'string_filter_operators',
    _and: 'file_formats_filter',
    _or: 'file_formats_filter',
  },
  products_production_methods_filter: {
    id: 'number_filter_operators',
    production_methods_id: 'production_methods_filter',
    products_id: 'products_filter',
    _and: 'products_production_methods_filter',
    _or: 'products_production_methods_filter',
  },
  invoices_filter: {
    id: 'number_filter_operators',
    user_created: 'directus_users_filter',
    date_created: 'date_filter_operators',
    date_created_func: 'datetime_function_filter_operators',
    user_updated: 'directus_users_filter',
    date_updated: 'date_filter_operators',
    date_updated_func: 'datetime_function_filter_operators',
    details: 'string_filter_operators',
    description: 'string_filter_operators',
    status: 'string_filter_operators',
    amount: 'number_filter_operators',
    transaction_url: 'string_filter_operators',
    production_product_id: 'products_filter',
    client_product_id: 'products_filter',
    _and: 'invoices_filter',
    _or: 'invoices_filter',
  },
  brands_directus_users_filter: {
    brands_id: 'brands_filter',
    directus_users_id: 'directus_users_filter',
    id: 'number_filter_operators',
    _and: 'brands_directus_users_filter',
    _or: 'brands_directus_users_filter',
  },
  producers: {
    production_materials_stocked: {
      filter: 'producers_production_materials_filter',
    },
    production_methods: {
      filter: 'producers_production_methods_filter',
    },
    supplied_materials: {
      filter: 'production_materials_filter',
    },
  },
  producers_production_materials: {
    producers_id: {
      filter: 'producers_filter',
    },
    production_materials_id: {
      filter: 'production_materials_filter',
    },
  },
  production_materials: {
    created_by: {
      filter: 'directus_users_filter',
    },
    size_guide: {
      filter: 'directus_files_filter',
    },
    supplier: {
      filter: 'producers_filter',
    },
    production_methods: {
      filter: 'production_materials_production_methods_filter',
    },
    stocked_at: {
      filter: 'producers_production_materials_filter',
    },
  },
  production_materials_production_methods: {
    production_materials_id: {
      filter: 'production_materials_filter',
    },
    production_methods_id: {
      filter: 'production_methods_filter',
    },
  },
  production_methods: {
    producers: {
      filter: 'producers_production_methods_filter',
    },
    production_materials: {
      filter: 'production_materials_production_methods_filter',
    },
  },
  producers_production_methods: {
    producers_id: {
      filter: 'producers_filter',
    },
    production_methods_id: {
      filter: 'production_methods_filter',
    },
  },
  products_contributors: {
    collaborators_id: {
      filter: 'collaborators_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  products_design_files: {
    directus_files_id: {
      filter: 'directus_files_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  products_content: {
    directus_files_id: {
      filter: 'directus_files_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  products_files: {
    directus_files_id: {
      filter: 'directus_files_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  products_production_materials: {
    production_materials_id: {
      filter: 'production_materials_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  products_wearables: {
    directus_files_id: {
      filter: 'directus_files_filter',
    },
    file_format: {
      filter: 'file_formats_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  products_production_methods: {
    production_methods_id: {
      filter: 'production_methods_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  invoices: {
    user_created: {
      filter: 'directus_users_filter',
    },
    user_updated: {
      filter: 'directus_users_filter',
    },
    production_product_id: {
      filter: 'products_filter',
    },
    client_product_id: {
      filter: 'products_filter',
    },
  },
  brands_directus_users: {
    brands_id: {
      filter: 'brands_filter',
    },
    directus_users_id: {
      filter: 'directus_users_filter',
    },
  },
  Mutation: {
    create_brands_items: {
      filter: 'brands_filter',
      data: 'create_brands_input',
    },
    create_brands_item: {
      data: 'create_brands_input',
    },
    create_brands_directus_users_items: {
      filter: 'brands_directus_users_filter',
      data: 'create_brands_directus_users_input',
    },
    create_brands_directus_users_item: {
      data: 'create_brands_directus_users_input',
    },
    create_collaborators_items: {
      filter: 'collaborators_filter',
      data: 'create_collaborators_input',
    },
    create_collaborators_item: {
      data: 'create_collaborators_input',
    },
    create_collaborator_roles_items: {
      filter: 'collaborator_roles_filter',
      data: 'create_collaborator_roles_input',
    },
    create_collaborator_roles_item: {
      data: 'create_collaborator_roles_input',
    },
    create_junction_directus_users_skills_items: {
      filter: 'junction_directus_users_skills_filter',
      data: 'create_junction_directus_users_skills_input',
    },
    create_junction_directus_users_skills_item: {
      data: 'create_junction_directus_users_skills_input',
    },
    create_skills_items: {
      filter: 'skills_filter',
      data: 'create_skills_input',
    },
    create_skills_item: {
      data: 'create_skills_input',
    },
    create_producers_items: {
      filter: 'producers_filter',
      data: 'create_producers_input',
    },
    create_producers_item: {
      data: 'create_producers_input',
    },
    create_producers_production_materials_items: {
      filter: 'producers_production_materials_filter',
      data: 'create_producers_production_materials_input',
    },
    create_producers_production_materials_item: {
      data: 'create_producers_production_materials_input',
    },
    create_producers_production_methods_items: {
      filter: 'producers_production_methods_filter',
      data: 'create_producers_production_methods_input',
    },
    create_producers_production_methods_item: {
      data: 'create_producers_production_methods_input',
    },
    create_production_methods_items: {
      filter: 'production_methods_filter',
      data: 'create_production_methods_input',
    },
    create_production_methods_item: {
      data: 'create_production_methods_input',
    },
    create_production_materials_production_methods_items: {
      filter: 'production_materials_production_methods_filter',
      data: 'create_production_materials_production_methods_input',
    },
    create_production_materials_production_methods_item: {
      data: 'create_production_materials_production_methods_input',
    },
    create_fulfillers_items: {
      filter: 'fulfillers_filter',
      data: 'create_fulfillers_input',
    },
    create_fulfillers_item: {
      data: 'create_fulfillers_input',
    },
    create_price_currencies_items: {
      filter: 'price_currencies_filter',
      data: 'create_price_currencies_input',
    },
    create_price_currencies_item: {
      data: 'create_price_currencies_input',
    },
    create_stages_items: {
      filter: 'stages_filter',
      data: 'create_stages_input',
    },
    create_stages_item: {
      data: 'create_stages_input',
    },
    create_currencies_items: {
      filter: 'currencies_filter',
      data: 'create_currencies_input',
    },
    create_currencies_item: {
      data: 'create_currencies_input',
    },
    create_products_content_items: {
      filter: 'products_content_filter',
      data: 'create_products_content_input',
    },
    create_products_content_item: {
      data: 'create_products_content_input',
    },
    create_products_contributors_items: {
      filter: 'products_contributors_filter',
      data: 'create_products_contributors_input',
    },
    create_products_contributors_item: {
      data: 'create_products_contributors_input',
    },
    create_products_design_files_items: {
      filter: 'products_design_files_filter',
      data: 'create_products_design_files_input',
    },
    create_products_design_files_item: {
      data: 'create_products_design_files_input',
    },
    create_products_files_items: {
      filter: 'products_files_filter',
      data: 'create_products_files_input',
    },
    create_products_files_item: {
      data: 'create_products_files_input',
    },
    create_products_production_materials_items: {
      filter: 'products_production_materials_filter',
      data: 'create_products_production_materials_input',
    },
    create_products_production_materials_item: {
      data: 'create_products_production_materials_input',
    },
    create_products_production_methods_items: {
      filter: 'products_production_methods_filter',
      data: 'create_products_production_methods_input',
    },
    create_products_production_methods_item: {
      data: 'create_products_production_methods_input',
    },
    create_products_wearables_items: {
      filter: 'products_wearables_filter',
      data: 'create_products_wearables_input',
    },
    create_products_wearables_item: {
      data: 'create_products_wearables_input',
    },
    create_file_formats_items: {
      filter: 'file_formats_filter',
      data: 'create_file_formats_input',
    },
    create_file_formats_item: {
      data: 'create_file_formats_input',
    },
    create_products_items: {
      filter: 'products_filter',
      data: 'create_products_input',
    },
    create_products_item: {
      data: 'create_products_input',
    },
    create_production_materials_items: {
      filter: 'production_materials_filter',
      data: 'create_production_materials_input',
    },
    create_production_materials_item: {
      data: 'create_production_materials_input',
    },
    create_invoices_items: {
      filter: 'invoices_filter',
      data: 'create_invoices_input',
    },
    create_invoices_item: {
      data: 'create_invoices_input',
    },
    update_brands_items: {
      filter: 'brands_filter',
      data: 'update_brands_input',
    },
    update_brands_batch: {
      filter: 'brands_filter',
      data: 'update_brands_input',
    },
    update_brands_item: {
      data: 'update_brands_input',
    },
    update_brands_directus_users_items: {
      filter: 'brands_directus_users_filter',
      data: 'update_brands_directus_users_input',
    },
    update_brands_directus_users_batch: {
      filter: 'brands_directus_users_filter',
      data: 'update_brands_directus_users_input',
    },
    update_brands_directus_users_item: {
      data: 'update_brands_directus_users_input',
    },
    update_collaborators_items: {
      filter: 'collaborators_filter',
      data: 'update_collaborators_input',
    },
    update_collaborators_batch: {
      filter: 'collaborators_filter',
      data: 'update_collaborators_input',
    },
    update_collaborators_item: {
      data: 'update_collaborators_input',
    },
    update_collaborator_roles_items: {
      filter: 'collaborator_roles_filter',
      data: 'update_collaborator_roles_input',
    },
    update_collaborator_roles_batch: {
      filter: 'collaborator_roles_filter',
      data: 'update_collaborator_roles_input',
    },
    update_collaborator_roles_item: {
      data: 'update_collaborator_roles_input',
    },
    update_junction_directus_users_skills_items: {
      filter: 'junction_directus_users_skills_filter',
      data: 'update_junction_directus_users_skills_input',
    },
    update_junction_directus_users_skills_batch: {
      filter: 'junction_directus_users_skills_filter',
      data: 'update_junction_directus_users_skills_input',
    },
    update_junction_directus_users_skills_item: {
      data: 'update_junction_directus_users_skills_input',
    },
    update_skills_items: {
      filter: 'skills_filter',
      data: 'update_skills_input',
    },
    update_skills_batch: {
      filter: 'skills_filter',
      data: 'update_skills_input',
    },
    update_skills_item: {
      data: 'update_skills_input',
    },
    update_producers_items: {
      filter: 'producers_filter',
      data: 'update_producers_input',
    },
    update_producers_batch: {
      filter: 'producers_filter',
      data: 'update_producers_input',
    },
    update_producers_item: {
      data: 'update_producers_input',
    },
    update_producers_production_materials_items: {
      filter: 'producers_production_materials_filter',
      data: 'update_producers_production_materials_input',
    },
    update_producers_production_materials_batch: {
      filter: 'producers_production_materials_filter',
      data: 'update_producers_production_materials_input',
    },
    update_producers_production_materials_item: {
      data: 'update_producers_production_materials_input',
    },
    update_producers_production_methods_items: {
      filter: 'producers_production_methods_filter',
      data: 'update_producers_production_methods_input',
    },
    update_producers_production_methods_batch: {
      filter: 'producers_production_methods_filter',
      data: 'update_producers_production_methods_input',
    },
    update_producers_production_methods_item: {
      data: 'update_producers_production_methods_input',
    },
    update_production_methods_items: {
      filter: 'production_methods_filter',
      data: 'update_production_methods_input',
    },
    update_production_methods_batch: {
      filter: 'production_methods_filter',
      data: 'update_production_methods_input',
    },
    update_production_methods_item: {
      data: 'update_production_methods_input',
    },
    update_production_materials_production_methods_items: {
      filter: 'production_materials_production_methods_filter',
      data: 'update_production_materials_production_methods_input',
    },
    update_production_materials_production_methods_batch: {
      filter: 'production_materials_production_methods_filter',
      data: 'update_production_materials_production_methods_input',
    },
    update_production_materials_production_methods_item: {
      data: 'update_production_materials_production_methods_input',
    },
    update_fulfillers_items: {
      filter: 'fulfillers_filter',
      data: 'update_fulfillers_input',
    },
    update_fulfillers_batch: {
      filter: 'fulfillers_filter',
      data: 'update_fulfillers_input',
    },
    update_fulfillers_item: {
      data: 'update_fulfillers_input',
    },
    update_price_currencies_items: {
      filter: 'price_currencies_filter',
      data: 'update_price_currencies_input',
    },
    update_price_currencies_batch: {
      filter: 'price_currencies_filter',
      data: 'update_price_currencies_input',
    },
    update_price_currencies_item: {
      data: 'update_price_currencies_input',
    },
    update_stages_items: {
      filter: 'stages_filter',
      data: 'update_stages_input',
    },
    update_stages_batch: {
      filter: 'stages_filter',
      data: 'update_stages_input',
    },
    update_stages_item: {
      data: 'update_stages_input',
    },
    update_currencies_items: {
      filter: 'currencies_filter',
      data: 'update_currencies_input',
    },
    update_currencies_batch: {
      filter: 'currencies_filter',
      data: 'update_currencies_input',
    },
    update_currencies_item: {
      data: 'update_currencies_input',
    },
    update_products_content_items: {
      filter: 'products_content_filter',
      data: 'update_products_content_input',
    },
    update_products_content_batch: {
      filter: 'products_content_filter',
      data: 'update_products_content_input',
    },
    update_products_content_item: {
      data: 'update_products_content_input',
    },
    update_products_contributors_items: {
      filter: 'products_contributors_filter',
      data: 'update_products_contributors_input',
    },
    update_products_contributors_batch: {
      filter: 'products_contributors_filter',
      data: 'update_products_contributors_input',
    },
    update_products_contributors_item: {
      data: 'update_products_contributors_input',
    },
    update_products_design_files_items: {
      filter: 'products_design_files_filter',
      data: 'update_products_design_files_input',
    },
    update_products_design_files_batch: {
      filter: 'products_design_files_filter',
      data: 'update_products_design_files_input',
    },
    update_products_design_files_item: {
      data: 'update_products_design_files_input',
    },
    update_products_files_items: {
      filter: 'products_files_filter',
      data: 'update_products_files_input',
    },
    update_products_files_batch: {
      filter: 'products_files_filter',
      data: 'update_products_files_input',
    },
    update_products_files_item: {
      data: 'update_products_files_input',
    },
    update_products_production_materials_items: {
      filter: 'products_production_materials_filter',
      data: 'update_products_production_materials_input',
    },
    update_products_production_materials_batch: {
      filter: 'products_production_materials_filter',
      data: 'update_products_production_materials_input',
    },
    update_products_production_materials_item: {
      data: 'update_products_production_materials_input',
    },
    update_products_production_methods_items: {
      filter: 'products_production_methods_filter',
      data: 'update_products_production_methods_input',
    },
    update_products_production_methods_batch: {
      filter: 'products_production_methods_filter',
      data: 'update_products_production_methods_input',
    },
    update_products_production_methods_item: {
      data: 'update_products_production_methods_input',
    },
    update_products_wearables_items: {
      filter: 'products_wearables_filter',
      data: 'update_products_wearables_input',
    },
    update_products_wearables_batch: {
      filter: 'products_wearables_filter',
      data: 'update_products_wearables_input',
    },
    update_products_wearables_item: {
      data: 'update_products_wearables_input',
    },
    update_file_formats_items: {
      filter: 'file_formats_filter',
      data: 'update_file_formats_input',
    },
    update_file_formats_batch: {
      filter: 'file_formats_filter',
      data: 'update_file_formats_input',
    },
    update_file_formats_item: {
      data: 'update_file_formats_input',
    },
    update_products_items: {
      filter: 'products_filter',
      data: 'update_products_input',
    },
    update_products_batch: {
      filter: 'products_filter',
      data: 'update_products_input',
    },
    update_products_item: {
      data: 'update_products_input',
    },
    update_production_materials_items: {
      filter: 'production_materials_filter',
      data: 'update_production_materials_input',
    },
    update_production_materials_batch: {
      filter: 'production_materials_filter',
      data: 'update_production_materials_input',
    },
    update_production_materials_item: {
      data: 'update_production_materials_input',
    },
    update_invoices_items: {
      filter: 'invoices_filter',
      data: 'update_invoices_input',
    },
    update_invoices_batch: {
      filter: 'invoices_filter',
      data: 'update_invoices_input',
    },
    update_invoices_item: {
      data: 'update_invoices_input',
    },
    delete_brands_items: {},
    delete_brands_item: {},
    delete_brands_directus_users_items: {},
    delete_brands_directus_users_item: {},
    delete_collaborators_items: {},
    delete_collaborators_item: {},
    delete_collaborator_roles_items: {},
    delete_collaborator_roles_item: {},
    delete_junction_directus_users_skills_items: {},
    delete_junction_directus_users_skills_item: {},
    delete_skills_items: {},
    delete_skills_item: {},
    delete_producers_items: {},
    delete_producers_item: {},
    delete_producers_production_materials_items: {},
    delete_producers_production_materials_item: {},
    delete_producers_production_methods_items: {},
    delete_producers_production_methods_item: {},
    delete_production_methods_items: {},
    delete_production_methods_item: {},
    delete_production_materials_production_methods_items: {},
    delete_production_materials_production_methods_item: {},
    delete_fulfillers_items: {},
    delete_fulfillers_item: {},
    delete_price_currencies_items: {},
    delete_price_currencies_item: {},
    delete_stages_items: {},
    delete_stages_item: {},
    delete_currencies_items: {},
    delete_currencies_item: {},
    delete_products_content_items: {},
    delete_products_content_item: {},
    delete_products_contributors_items: {},
    delete_products_contributors_item: {},
    delete_products_design_files_items: {},
    delete_products_design_files_item: {},
    delete_products_files_items: {},
    delete_products_files_item: {},
    delete_products_production_materials_items: {},
    delete_products_production_materials_item: {},
    delete_products_production_methods_items: {},
    delete_products_production_methods_item: {},
    delete_products_wearables_items: {},
    delete_products_wearables_item: {},
    delete_file_formats_items: {},
    delete_file_formats_item: {},
    delete_products_items: {},
    delete_products_item: {},
    delete_production_materials_items: {},
    delete_production_materials_item: {},
    delete_invoices_items: {},
    delete_invoices_item: {},
  },
  create_brands_input: {
    created_at: 'Date',
    logo: 'create_directus_files_input',
    products: 'create_products_input',
    users: 'create_brands_directus_users_input',
  },
  create_directus_files_input: {
    folder: 'create_directus_folders_input',
    uploaded_by: 'create_directus_users_input',
    uploaded_on: 'Date',
    modified_by: 'create_directus_users_input',
    modified_on: 'Date',
    filesize: 'GraphQLBigInt',
    tags: 'JSON',
    metadata: 'JSON',
  },
  create_directus_folders_input: {
    parent: 'create_directus_folders_input',
  },
  create_directus_users_input: {
    password: 'Hash',
    tags: 'JSON',
    avatar: 'create_directus_files_input',
    tfa_secret: 'Hash',
    role: 'create_directus_roles_input',
    token: 'Hash',
    last_access: 'Date',
    auth_data: 'JSON',
    collaborators: 'create_collaborators_input',
    skills: 'create_junction_directus_users_skills_input',
  },
  create_directus_roles_input: {
    users: 'create_directus_users_input',
  },
  create_collaborators_input: {
    account: 'create_directus_users_input',
    date_created: 'Date',
    date_updated: 'Date',
    role: 'create_collaborator_roles_input',
    user_created: 'create_directus_users_input',
  },
  create_collaborator_roles_input: {},
  create_junction_directus_users_skills_input: {
    directus_users_id: 'create_directus_users_input',
    skills_id: 'create_skills_input',
  },
  create_skills_input: {},
  create_products_input: {
    brand_id: 'create_brands_input',
    clo3d_file: 'create_directus_files_input',
    created_at: 'Date',
    fulfiller_id: 'create_fulfillers_input',
    price: 'create_price_currencies_input',
    producer_id: 'create_producers_input',
    product_stage: 'create_stages_input',
    quantity: 'GraphQLBigInt',
    release_date: 'Date',
    sale_currency: 'create_currencies_input',
    contributors: 'create_products_contributors_input',
    design_files: 'create_products_design_files_input',
    content: 'create_products_content_input',
    images: 'create_products_files_input',
    materials: 'create_products_production_materials_input',
    wearable_files: 'create_products_wearables_input',
    production_methods: 'create_products_production_methods_input',
    client_invoices: 'create_invoices_input',
    production_invoices: 'create_invoices_input',
  },
  create_fulfillers_input: {
    created_at: 'Date',
  },
  create_price_currencies_input: {},
  create_producers_input: {
    created_at: 'Date',
    production_materials_stocked: 'create_producers_production_materials_input',
    production_methods: 'create_producers_production_methods_input',
    supplied_materials: 'create_production_materials_input',
  },
  create_producers_production_materials_input: {
    producers_id: 'create_producers_input',
    production_materials_id: 'create_production_materials_input',
  },
  create_production_materials_input: {
    color_palette: 'JSON',
    created_at: 'Date',
    created_by: 'create_directus_users_input',
    size_guide: 'create_directus_files_input',
    supplier: 'create_producers_input',
    tags: 'JSON',
    production_methods: 'create_production_materials_production_methods_input',
    stocked_at: 'create_producers_production_materials_input',
  },
  create_production_materials_production_methods_input: {
    production_materials_id: 'create_production_materials_input',
    production_methods_id: 'create_production_methods_input',
  },
  create_production_methods_input: {
    created_at: 'Date',
    producers: 'create_producers_production_methods_input',
    production_materials:
      'create_production_materials_production_methods_input',
  },
  create_producers_production_methods_input: {
    producers_id: 'create_producers_input',
    production_methods_id: 'create_production_methods_input',
  },
  create_stages_input: {},
  create_currencies_input: {},
  create_products_contributors_input: {
    collaborators_id: 'create_collaborators_input',
    products_id: 'create_products_input',
  },
  create_products_design_files_input: {
    directus_files_id: 'create_directus_files_input',
    products_id: 'create_products_input',
  },
  create_products_content_input: {
    directus_files_id: 'create_directus_files_input',
    products_id: 'create_products_input',
  },
  create_products_files_input: {
    directus_files_id: 'create_directus_files_input',
    products_id: 'create_products_input',
  },
  create_products_production_materials_input: {
    production_materials_id: 'create_production_materials_input',
    products_id: 'create_products_input',
  },
  create_products_wearables_input: {
    directus_files_id: 'create_directus_files_input',
    file_format: 'create_file_formats_input',
    products_id: 'create_products_input',
  },
  create_file_formats_input: {},
  create_products_production_methods_input: {
    production_methods_id: 'create_production_methods_input',
    products_id: 'create_products_input',
  },
  create_invoices_input: {
    user_created: 'create_directus_users_input',
    date_created: 'Date',
    user_updated: 'create_directus_users_input',
    date_updated: 'Date',
    production_product_id: 'create_products_input',
    client_product_id: 'create_products_input',
  },
  create_brands_directus_users_input: {
    brands_id: 'create_brands_input',
    directus_users_id: 'create_directus_users_input',
  },
  update_brands_input: {
    created_at: 'Date',
    logo: 'update_directus_files_input',
    products: 'update_products_input',
    users: 'update_brands_directus_users_input',
  },
  update_directus_files_input: {
    folder: 'update_directus_folders_input',
    uploaded_by: 'update_directus_users_input',
    uploaded_on: 'Date',
    modified_by: 'update_directus_users_input',
    modified_on: 'Date',
    filesize: 'GraphQLBigInt',
    tags: 'JSON',
    metadata: 'JSON',
  },
  update_directus_folders_input: {
    parent: 'update_directus_folders_input',
  },
  update_directus_users_input: {
    password: 'Hash',
    tags: 'JSON',
    avatar: 'update_directus_files_input',
    tfa_secret: 'Hash',
    role: 'update_directus_roles_input',
    token: 'Hash',
    last_access: 'Date',
    auth_data: 'JSON',
    collaborators: 'update_collaborators_input',
    skills: 'update_junction_directus_users_skills_input',
  },
  update_directus_roles_input: {
    users: 'update_directus_users_input',
  },
  update_collaborators_input: {
    account: 'update_directus_users_input',
    date_created: 'Date',
    date_updated: 'Date',
    role: 'update_collaborator_roles_input',
    user_created: 'update_directus_users_input',
  },
  update_collaborator_roles_input: {},
  update_junction_directus_users_skills_input: {
    directus_users_id: 'update_directus_users_input',
    skills_id: 'update_skills_input',
  },
  update_skills_input: {},
  update_products_input: {
    brand_id: 'update_brands_input',
    clo3d_file: 'update_directus_files_input',
    created_at: 'Date',
    fulfiller_id: 'update_fulfillers_input',
    price: 'update_price_currencies_input',
    producer_id: 'update_producers_input',
    product_stage: 'update_stages_input',
    quantity: 'GraphQLBigInt',
    release_date: 'Date',
    sale_currency: 'update_currencies_input',
    contributors: 'update_products_contributors_input',
    design_files: 'update_products_design_files_input',
    content: 'update_products_content_input',
    images: 'update_products_files_input',
    materials: 'update_products_production_materials_input',
    wearable_files: 'update_products_wearables_input',
    production_methods: 'update_products_production_methods_input',
    client_invoices: 'update_invoices_input',
    production_invoices: 'update_invoices_input',
  },
  update_fulfillers_input: {
    created_at: 'Date',
  },
  update_price_currencies_input: {},
  update_producers_input: {
    created_at: 'Date',
    production_materials_stocked: 'update_producers_production_materials_input',
    production_methods: 'update_producers_production_methods_input',
    supplied_materials: 'update_production_materials_input',
  },
  update_producers_production_materials_input: {
    producers_id: 'update_producers_input',
    production_materials_id: 'update_production_materials_input',
  },
  update_production_materials_input: {
    color_palette: 'JSON',
    created_at: 'Date',
    created_by: 'update_directus_users_input',
    size_guide: 'update_directus_files_input',
    supplier: 'update_producers_input',
    tags: 'JSON',
    production_methods: 'update_production_materials_production_methods_input',
    stocked_at: 'update_producers_production_materials_input',
  },
  update_production_materials_production_methods_input: {
    production_materials_id: 'update_production_materials_input',
    production_methods_id: 'update_production_methods_input',
  },
  update_production_methods_input: {
    created_at: 'Date',
    producers: 'update_producers_production_methods_input',
    production_materials:
      'update_production_materials_production_methods_input',
  },
  update_producers_production_methods_input: {
    producers_id: 'update_producers_input',
    production_methods_id: 'update_production_methods_input',
  },
  update_stages_input: {},
  update_currencies_input: {},
  update_products_contributors_input: {
    collaborators_id: 'update_collaborators_input',
    products_id: 'update_products_input',
  },
  update_products_design_files_input: {
    directus_files_id: 'update_directus_files_input',
    products_id: 'update_products_input',
  },
  update_products_content_input: {
    directus_files_id: 'update_directus_files_input',
    products_id: 'update_products_input',
  },
  update_products_files_input: {
    directus_files_id: 'update_directus_files_input',
    products_id: 'update_products_input',
  },
  update_products_production_materials_input: {
    production_materials_id: 'update_production_materials_input',
    products_id: 'update_products_input',
  },
  update_products_wearables_input: {
    directus_files_id: 'update_directus_files_input',
    file_format: 'update_file_formats_input',
    products_id: 'update_products_input',
  },
  update_file_formats_input: {},
  update_products_production_methods_input: {
    production_methods_id: 'update_production_methods_input',
    products_id: 'update_products_input',
  },
  update_invoices_input: {
    user_created: 'update_directus_users_input',
    date_created: 'Date',
    user_updated: 'update_directus_users_input',
    date_updated: 'Date',
    production_product_id: 'update_products_input',
    client_product_id: 'update_products_input',
  },
  update_brands_directus_users_input: {
    brands_id: 'update_brands_input',
    directus_users_id: 'update_directus_users_input',
  },
};

export const ReturnTypes: Record<string, any> = {
  Query: {
    brands: 'brands',
    brands_by_id: 'brands',
    brands_aggregated: 'brands_aggregated',
    brands_directus_users: 'brands_directus_users',
    brands_directus_users_by_id: 'brands_directus_users',
    brands_directus_users_aggregated: 'brands_directus_users_aggregated',
    collaborators: 'collaborators',
    collaborators_by_id: 'collaborators',
    collaborators_aggregated: 'collaborators_aggregated',
    collaborator_roles: 'collaborator_roles',
    collaborator_roles_by_id: 'collaborator_roles',
    collaborator_roles_aggregated: 'collaborator_roles_aggregated',
    junction_directus_users_skills: 'junction_directus_users_skills',
    junction_directus_users_skills_by_id: 'junction_directus_users_skills',
    junction_directus_users_skills_aggregated:
      'junction_directus_users_skills_aggregated',
    skills: 'skills',
    skills_by_id: 'skills',
    skills_aggregated: 'skills_aggregated',
    producers: 'producers',
    producers_by_id: 'producers',
    producers_aggregated: 'producers_aggregated',
    producers_production_materials: 'producers_production_materials',
    producers_production_materials_by_id: 'producers_production_materials',
    producers_production_materials_aggregated:
      'producers_production_materials_aggregated',
    producers_production_methods: 'producers_production_methods',
    producers_production_methods_by_id: 'producers_production_methods',
    producers_production_methods_aggregated:
      'producers_production_methods_aggregated',
    production_methods: 'production_methods',
    production_methods_by_id: 'production_methods',
    production_methods_aggregated: 'production_methods_aggregated',
    production_materials_production_methods:
      'production_materials_production_methods',
    production_materials_production_methods_by_id:
      'production_materials_production_methods',
    production_materials_production_methods_aggregated:
      'production_materials_production_methods_aggregated',
    fulfillers: 'fulfillers',
    fulfillers_by_id: 'fulfillers',
    fulfillers_aggregated: 'fulfillers_aggregated',
    price_currencies: 'price_currencies',
    price_currencies_by_id: 'price_currencies',
    price_currencies_aggregated: 'price_currencies_aggregated',
    stages: 'stages',
    stages_by_id: 'stages',
    stages_aggregated: 'stages_aggregated',
    currencies: 'currencies',
    currencies_by_id: 'currencies',
    currencies_aggregated: 'currencies_aggregated',
    products_content: 'products_content',
    products_content_by_id: 'products_content',
    products_content_aggregated: 'products_content_aggregated',
    products_contributors: 'products_contributors',
    products_contributors_by_id: 'products_contributors',
    products_contributors_aggregated: 'products_contributors_aggregated',
    products_design_files: 'products_design_files',
    products_design_files_by_id: 'products_design_files',
    products_design_files_aggregated: 'products_design_files_aggregated',
    products_files: 'products_files',
    products_files_by_id: 'products_files',
    products_files_aggregated: 'products_files_aggregated',
    products_production_materials: 'products_production_materials',
    products_production_materials_by_id: 'products_production_materials',
    products_production_materials_aggregated:
      'products_production_materials_aggregated',
    products_production_methods: 'products_production_methods',
    products_production_methods_by_id: 'products_production_methods',
    products_production_methods_aggregated:
      'products_production_methods_aggregated',
    products_wearables: 'products_wearables',
    products_wearables_by_id: 'products_wearables',
    products_wearables_aggregated: 'products_wearables_aggregated',
    file_formats: 'file_formats',
    file_formats_by_id: 'file_formats',
    file_formats_aggregated: 'file_formats_aggregated',
    products: 'products',
    products_by_id: 'products',
    products_aggregated: 'products_aggregated',
    production_materials: 'production_materials',
    production_materials_by_id: 'production_materials',
    production_materials_aggregated: 'production_materials_aggregated',
    invoices: 'invoices',
    invoices_by_id: 'invoices',
    invoices_aggregated: 'invoices_aggregated',
  },
  brands: {
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    description: 'String',
    discord_url: 'String',
    eth_address: 'String',
    id: 'ID',
    logo: 'directus_files',
    name: 'String',
    notion_id: 'String',
    twitter_url: 'String',
    website_url: 'String',
    products: 'products',
    products_func: 'count_functions',
    users: 'brands_directus_users',
    users_func: 'count_functions',
  },
  Date: `scalar.Date` as const,
  datetime_functions: {
    year: 'Int',
    month: 'Int',
    week: 'Int',
    day: 'Int',
    weekday: 'Int',
    hour: 'Int',
    minute: 'Int',
    second: 'Int',
  },
  directus_files: {
    id: 'ID',
    storage: 'String',
    filename_disk: 'String',
    filename_download: 'String',
    title: 'String',
    type: 'String',
    folder: 'directus_folders',
    uploaded_by: 'directus_users',
    uploaded_on: 'Date',
    uploaded_on_func: 'datetime_functions',
    modified_by: 'directus_users',
    modified_on: 'Date',
    modified_on_func: 'datetime_functions',
    charset: 'String',
    filesize: 'GraphQLBigInt',
    width: 'Int',
    height: 'Int',
    duration: 'Int',
    embed: 'String',
    description: 'String',
    location: 'String',
    tags: 'JSON',
    tags_func: 'count_functions',
    metadata: 'JSON',
    metadata_func: 'count_functions',
  },
  directus_folders: {
    id: 'ID',
    name: 'String',
    parent: 'directus_folders',
  },
  directus_users: {
    id: 'ID',
    first_name: 'String',
    last_name: 'String',
    email: 'String',
    password: 'Hash',
    location: 'String',
    title: 'String',
    description: 'String',
    tags: 'JSON',
    tags_func: 'count_functions',
    avatar: 'directus_files',
    language: 'String',
    theme: 'String',
    tfa_secret: 'Hash',
    status: 'String',
    role: 'directus_roles',
    token: 'Hash',
    last_access: 'Date',
    last_access_func: 'datetime_functions',
    last_page: 'String',
    provider: 'String',
    external_identifier: 'String',
    auth_data: 'JSON',
    auth_data_func: 'count_functions',
    email_notifications: 'Boolean',
    discord_handle: 'String',
    discord_id: 'String',
    timezone: 'String',
    twitter_handle: 'String',
    collaborators: 'collaborators',
    collaborators_func: 'count_functions',
    skills: 'junction_directus_users_skills',
    skills_func: 'count_functions',
  },
  Hash: `scalar.Hash` as const,
  JSON: `scalar.JSON` as const,
  count_functions: {
    count: 'Int',
  },
  GraphQLStringOrFloat: `scalar.GraphQLStringOrFloat` as const,
  directus_roles: {
    id: 'ID',
    name: 'String',
    icon: 'String',
    description: 'String',
    ip_access: 'String',
    enforce_tfa: 'Boolean',
    admin_access: 'Boolean',
    app_access: 'Boolean',
    users: 'directus_users',
    users_func: 'count_functions',
  },
  collaborators: {
    account: 'directus_users',
    date_created: 'Date',
    date_created_func: 'datetime_functions',
    date_updated: 'Date',
    date_updated_func: 'datetime_functions',
    display_name: 'String',
    id: 'ID',
    payment_eth_address: 'String',
    role: 'collaborator_roles',
    user_created: 'directus_users',
  },
  collaborator_roles: {
    description: 'String',
    id: 'ID',
    name: 'String',
  },
  junction_directus_users_skills: {
    directus_users_id: 'directus_users',
    id: 'ID',
    skills_id: 'skills',
  },
  skills: {
    description: 'String',
    id: 'ID',
    name: 'String',
  },
  GraphQLBigInt: `scalar.GraphQLBigInt` as const,
  products: {
    brand_id: 'brands',
    clo3d_file: 'directus_files',
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    description: 'String',
    discord_channel_id: 'String',
    fulfiller_id: 'fulfillers',
    id: 'ID',
    name: 'String',
    nft_token_id: 'Int',
    notion_id: 'String',
    price: 'price_currencies',
    producer_id: 'producers',
    product_stage: 'stages',
    production_cost: 'Float',
    quantity: 'GraphQLBigInt',
    release_date: 'Date',
    release_date_func: 'datetime_functions',
    sale_currency: 'currencies',
    sale_price: 'Float',
    sale_type: 'String',
    season: 'Int',
    shopify_id: 'String',
    status: 'String',
    notes: 'String',
    contributors: 'products_contributors',
    contributors_func: 'count_functions',
    design_files: 'products_design_files',
    design_files_func: 'count_functions',
    content: 'products_content',
    content_func: 'count_functions',
    images: 'products_files',
    images_func: 'count_functions',
    materials: 'products_production_materials',
    materials_func: 'count_functions',
    wearable_files: 'products_wearables',
    wearable_files_func: 'count_functions',
    production_methods: 'products_production_methods',
    production_methods_func: 'count_functions',
    client_invoices: 'invoices',
    client_invoices_func: 'count_functions',
    production_invoices: 'invoices',
    production_invoices_func: 'count_functions',
  },
  fulfillers: {
    address: 'String',
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    email: 'String',
    eth_address: 'String',
    id: 'ID',
    name: 'String',
    website_url: 'String',
  },
  price_currencies: {
    amount: 'Int',
    currency: 'String',
    id: 'ID',
  },
  producers: {
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    email: 'String',
    eth_address: 'String',
    id: 'ID',
    name: 'String',
    shipping_address: 'String',
    production_materials_stocked: 'producers_production_materials',
    production_materials_stocked_func: 'count_functions',
    production_methods: 'producers_production_methods',
    production_methods_func: 'count_functions',
    supplied_materials: 'production_materials',
    supplied_materials_func: 'count_functions',
  },
  producers_production_materials: {
    id: 'ID',
    producers_id: 'producers',
    production_materials_id: 'production_materials',
    quantity: 'Int',
  },
  production_materials: {
    base_price: 'Int',
    color_palette: 'JSON',
    color_palette_func: 'count_functions',
    composition: 'String',
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    created_by: 'directus_users',
    description: 'String',
    gender: 'String',
    id: 'ID',
    made_in: 'String',
    name: 'String',
    neck_tag: 'Boolean',
    note: 'String',
    rating: 'String',
    size_guide: 'directus_files',
    supplier: 'producers',
    tags: 'JSON',
    tags_func: 'count_functions',
    production_methods: 'production_materials_production_methods',
    production_methods_func: 'count_functions',
    stocked_at: 'producers_production_materials',
    stocked_at_func: 'count_functions',
  },
  production_materials_production_methods: {
    id: 'ID',
    production_materials_id: 'production_materials',
    production_methods_id: 'production_methods',
  },
  production_methods: {
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    description: 'String',
    id: 'ID',
    name: 'String',
    producers: 'producers_production_methods',
    producers_func: 'count_functions',
    production_materials: 'production_materials_production_methods',
    production_materials_func: 'count_functions',
  },
  producers_production_methods: {
    id: 'ID',
    producers_id: 'producers',
    production_methods_id: 'production_methods',
  },
  stages: {
    description: 'String',
    name: 'ID',
    sort: 'Int',
  },
  currencies: {
    currency: 'String',
    id: 'ID',
  },
  products_contributors: {
    collaborators_id: 'collaborators',
    contribution_share: 'Int',
    id: 'ID',
    products_id: 'products',
    robot_earned: 'Float',
  },
  products_design_files: {
    directus_files_id: 'directus_files',
    id: 'ID',
    products_id: 'products',
  },
  products_content: {
    directus_files_id: 'directus_files',
    id: 'ID',
    products_id: 'products',
  },
  products_files: {
    directus_files_id: 'directus_files',
    id: 'ID',
    products_id: 'products',
  },
  products_production_materials: {
    id: 'ID',
    production_materials_id: 'production_materials',
    products_id: 'products',
  },
  products_wearables: {
    directus_files_id: 'directus_files',
    file_format: 'file_formats',
    id: 'ID',
    primary: 'Boolean',
    products_id: 'products',
  },
  file_formats: {
    description: 'String',
    extension: 'String',
    id: 'ID',
    mime_type: 'String',
    name: 'String',
  },
  products_production_methods: {
    id: 'ID',
    production_methods_id: 'production_methods',
    products_id: 'products',
  },
  invoices: {
    id: 'ID',
    user_created: 'directus_users',
    date_created: 'Date',
    date_created_func: 'datetime_functions',
    user_updated: 'directus_users',
    date_updated: 'Date',
    date_updated_func: 'datetime_functions',
    details: 'String',
    description: 'String',
    status: 'String',
    amount: 'Float',
    transaction_url: 'String',
    production_product_id: 'products',
    client_product_id: 'products',
  },
  brands_directus_users: {
    brands_id: 'brands',
    directus_users_id: 'directus_users',
    id: 'ID',
  },
  brands_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'brands_aggregated_count',
    countDistinct: 'brands_aggregated_count',
  },
  brands_aggregated_count: {
    created_at: 'Int',
    description: 'Int',
    discord_url: 'Int',
    eth_address: 'Int',
    id: 'Int',
    logo: 'Int',
    name: 'Int',
    notion_id: 'Int',
    twitter_url: 'Int',
    website_url: 'Int',
    products: 'Int',
    users: 'Int',
  },
  brands_directus_users_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'brands_directus_users_aggregated_count',
    countDistinct: 'brands_directus_users_aggregated_count',
    avg: 'brands_directus_users_aggregated_fields',
    sum: 'brands_directus_users_aggregated_fields',
    avgDistinct: 'brands_directus_users_aggregated_fields',
    sumDistinct: 'brands_directus_users_aggregated_fields',
    min: 'brands_directus_users_aggregated_fields',
    max: 'brands_directus_users_aggregated_fields',
  },
  brands_directus_users_aggregated_count: {
    brands_id: 'Int',
    directus_users_id: 'Int',
    id: 'Int',
  },
  brands_directus_users_aggregated_fields: {
    brands_id: 'Float',
    id: 'Float',
  },
  collaborators_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'collaborators_aggregated_count',
    countDistinct: 'collaborators_aggregated_count',
    avg: 'collaborators_aggregated_fields',
    sum: 'collaborators_aggregated_fields',
    avgDistinct: 'collaborators_aggregated_fields',
    sumDistinct: 'collaborators_aggregated_fields',
    min: 'collaborators_aggregated_fields',
    max: 'collaborators_aggregated_fields',
  },
  collaborators_aggregated_count: {
    account: 'Int',
    date_created: 'Int',
    date_updated: 'Int',
    display_name: 'Int',
    id: 'Int',
    payment_eth_address: 'Int',
    role: 'Int',
    user_created: 'Int',
  },
  collaborators_aggregated_fields: {
    id: 'Float',
    role: 'Float',
  },
  collaborator_roles_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'collaborator_roles_aggregated_count',
    countDistinct: 'collaborator_roles_aggregated_count',
    avg: 'collaborator_roles_aggregated_fields',
    sum: 'collaborator_roles_aggregated_fields',
    avgDistinct: 'collaborator_roles_aggregated_fields',
    sumDistinct: 'collaborator_roles_aggregated_fields',
    min: 'collaborator_roles_aggregated_fields',
    max: 'collaborator_roles_aggregated_fields',
  },
  collaborator_roles_aggregated_count: {
    description: 'Int',
    id: 'Int',
    name: 'Int',
  },
  collaborator_roles_aggregated_fields: {
    id: 'Float',
  },
  junction_directus_users_skills_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'junction_directus_users_skills_aggregated_count',
    countDistinct: 'junction_directus_users_skills_aggregated_count',
    avg: 'junction_directus_users_skills_aggregated_fields',
    sum: 'junction_directus_users_skills_aggregated_fields',
    avgDistinct: 'junction_directus_users_skills_aggregated_fields',
    sumDistinct: 'junction_directus_users_skills_aggregated_fields',
    min: 'junction_directus_users_skills_aggregated_fields',
    max: 'junction_directus_users_skills_aggregated_fields',
  },
  junction_directus_users_skills_aggregated_count: {
    directus_users_id: 'Int',
    id: 'Int',
    skills_id: 'Int',
  },
  junction_directus_users_skills_aggregated_fields: {
    id: 'Float',
    skills_id: 'Float',
  },
  skills_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'skills_aggregated_count',
    countDistinct: 'skills_aggregated_count',
  },
  skills_aggregated_count: {
    description: 'Int',
    id: 'Int',
    name: 'Int',
  },
  producers_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'producers_aggregated_count',
    countDistinct: 'producers_aggregated_count',
  },
  producers_aggregated_count: {
    created_at: 'Int',
    email: 'Int',
    eth_address: 'Int',
    id: 'Int',
    name: 'Int',
    shipping_address: 'Int',
    production_materials_stocked: 'Int',
    production_methods: 'Int',
    supplied_materials: 'Int',
  },
  producers_production_materials_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'producers_production_materials_aggregated_count',
    countDistinct: 'producers_production_materials_aggregated_count',
    avg: 'producers_production_materials_aggregated_fields',
    sum: 'producers_production_materials_aggregated_fields',
    avgDistinct: 'producers_production_materials_aggregated_fields',
    sumDistinct: 'producers_production_materials_aggregated_fields',
    min: 'producers_production_materials_aggregated_fields',
    max: 'producers_production_materials_aggregated_fields',
  },
  producers_production_materials_aggregated_count: {
    id: 'Int',
    producers_id: 'Int',
    production_materials_id: 'Int',
    quantity: 'Int',
  },
  producers_production_materials_aggregated_fields: {
    id: 'Float',
    producers_id: 'Float',
    production_materials_id: 'Float',
    quantity: 'Float',
  },
  producers_production_methods_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'producers_production_methods_aggregated_count',
    countDistinct: 'producers_production_methods_aggregated_count',
    avg: 'producers_production_methods_aggregated_fields',
    sum: 'producers_production_methods_aggregated_fields',
    avgDistinct: 'producers_production_methods_aggregated_fields',
    sumDistinct: 'producers_production_methods_aggregated_fields',
    min: 'producers_production_methods_aggregated_fields',
    max: 'producers_production_methods_aggregated_fields',
  },
  producers_production_methods_aggregated_count: {
    id: 'Int',
    producers_id: 'Int',
    production_methods_id: 'Int',
  },
  producers_production_methods_aggregated_fields: {
    id: 'Float',
    producers_id: 'Float',
    production_methods_id: 'Float',
  },
  production_methods_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'production_methods_aggregated_count',
    countDistinct: 'production_methods_aggregated_count',
  },
  production_methods_aggregated_count: {
    created_at: 'Int',
    description: 'Int',
    id: 'Int',
    name: 'Int',
    producers: 'Int',
    production_materials: 'Int',
  },
  production_materials_production_methods_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'production_materials_production_methods_aggregated_count',
    countDistinct: 'production_materials_production_methods_aggregated_count',
    avg: 'production_materials_production_methods_aggregated_fields',
    sum: 'production_materials_production_methods_aggregated_fields',
    avgDistinct: 'production_materials_production_methods_aggregated_fields',
    sumDistinct: 'production_materials_production_methods_aggregated_fields',
    min: 'production_materials_production_methods_aggregated_fields',
    max: 'production_materials_production_methods_aggregated_fields',
  },
  production_materials_production_methods_aggregated_count: {
    id: 'Int',
    production_materials_id: 'Int',
    production_methods_id: 'Int',
  },
  production_materials_production_methods_aggregated_fields: {
    id: 'Float',
    production_materials_id: 'Float',
    production_methods_id: 'Float',
  },
  fulfillers_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'fulfillers_aggregated_count',
    countDistinct: 'fulfillers_aggregated_count',
  },
  fulfillers_aggregated_count: {
    address: 'Int',
    created_at: 'Int',
    email: 'Int',
    eth_address: 'Int',
    id: 'Int',
    name: 'Int',
    website_url: 'Int',
  },
  price_currencies_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'price_currencies_aggregated_count',
    countDistinct: 'price_currencies_aggregated_count',
    avg: 'price_currencies_aggregated_fields',
    sum: 'price_currencies_aggregated_fields',
    avgDistinct: 'price_currencies_aggregated_fields',
    sumDistinct: 'price_currencies_aggregated_fields',
    min: 'price_currencies_aggregated_fields',
    max: 'price_currencies_aggregated_fields',
  },
  price_currencies_aggregated_count: {
    amount: 'Int',
    currency: 'Int',
    id: 'Int',
  },
  price_currencies_aggregated_fields: {
    amount: 'Float',
    id: 'Float',
  },
  stages_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'stages_aggregated_count',
    countDistinct: 'stages_aggregated_count',
    avg: 'stages_aggregated_fields',
    sum: 'stages_aggregated_fields',
    avgDistinct: 'stages_aggregated_fields',
    sumDistinct: 'stages_aggregated_fields',
    min: 'stages_aggregated_fields',
    max: 'stages_aggregated_fields',
  },
  stages_aggregated_count: {
    description: 'Int',
    name: 'Int',
    sort: 'Int',
  },
  stages_aggregated_fields: {
    sort: 'Float',
  },
  currencies_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'currencies_aggregated_count',
    countDistinct: 'currencies_aggregated_count',
    avg: 'currencies_aggregated_fields',
    sum: 'currencies_aggregated_fields',
    avgDistinct: 'currencies_aggregated_fields',
    sumDistinct: 'currencies_aggregated_fields',
    min: 'currencies_aggregated_fields',
    max: 'currencies_aggregated_fields',
  },
  currencies_aggregated_count: {
    currency: 'Int',
    id: 'Int',
  },
  currencies_aggregated_fields: {
    id: 'Float',
  },
  products_content_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_content_aggregated_count',
    countDistinct: 'products_content_aggregated_count',
    avg: 'products_content_aggregated_fields',
    sum: 'products_content_aggregated_fields',
    avgDistinct: 'products_content_aggregated_fields',
    sumDistinct: 'products_content_aggregated_fields',
    min: 'products_content_aggregated_fields',
    max: 'products_content_aggregated_fields',
  },
  products_content_aggregated_count: {
    directus_files_id: 'Int',
    id: 'Int',
    products_id: 'Int',
  },
  products_content_aggregated_fields: {
    id: 'Float',
    products_id: 'Float',
  },
  products_contributors_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_contributors_aggregated_count',
    countDistinct: 'products_contributors_aggregated_count',
    avg: 'products_contributors_aggregated_fields',
    sum: 'products_contributors_aggregated_fields',
    avgDistinct: 'products_contributors_aggregated_fields',
    sumDistinct: 'products_contributors_aggregated_fields',
    min: 'products_contributors_aggregated_fields',
    max: 'products_contributors_aggregated_fields',
  },
  products_contributors_aggregated_count: {
    collaborators_id: 'Int',
    contribution_share: 'Int',
    id: 'Int',
    products_id: 'Int',
    robot_earned: 'Int',
  },
  products_contributors_aggregated_fields: {
    collaborators_id: 'Float',
    contribution_share: 'Float',
    id: 'Float',
    products_id: 'Float',
    robot_earned: 'Float',
  },
  products_design_files_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_design_files_aggregated_count',
    countDistinct: 'products_design_files_aggregated_count',
    avg: 'products_design_files_aggregated_fields',
    sum: 'products_design_files_aggregated_fields',
    avgDistinct: 'products_design_files_aggregated_fields',
    sumDistinct: 'products_design_files_aggregated_fields',
    min: 'products_design_files_aggregated_fields',
    max: 'products_design_files_aggregated_fields',
  },
  products_design_files_aggregated_count: {
    directus_files_id: 'Int',
    id: 'Int',
    products_id: 'Int',
  },
  products_design_files_aggregated_fields: {
    id: 'Float',
    products_id: 'Float',
  },
  products_files_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_files_aggregated_count',
    countDistinct: 'products_files_aggregated_count',
    avg: 'products_files_aggregated_fields',
    sum: 'products_files_aggregated_fields',
    avgDistinct: 'products_files_aggregated_fields',
    sumDistinct: 'products_files_aggregated_fields',
    min: 'products_files_aggregated_fields',
    max: 'products_files_aggregated_fields',
  },
  products_files_aggregated_count: {
    directus_files_id: 'Int',
    id: 'Int',
    products_id: 'Int',
  },
  products_files_aggregated_fields: {
    id: 'Float',
    products_id: 'Float',
  },
  products_production_materials_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_production_materials_aggregated_count',
    countDistinct: 'products_production_materials_aggregated_count',
    avg: 'products_production_materials_aggregated_fields',
    sum: 'products_production_materials_aggregated_fields',
    avgDistinct: 'products_production_materials_aggregated_fields',
    sumDistinct: 'products_production_materials_aggregated_fields',
    min: 'products_production_materials_aggregated_fields',
    max: 'products_production_materials_aggregated_fields',
  },
  products_production_materials_aggregated_count: {
    id: 'Int',
    production_materials_id: 'Int',
    products_id: 'Int',
  },
  products_production_materials_aggregated_fields: {
    id: 'Float',
    production_materials_id: 'Float',
    products_id: 'Float',
  },
  products_production_methods_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_production_methods_aggregated_count',
    countDistinct: 'products_production_methods_aggregated_count',
    avg: 'products_production_methods_aggregated_fields',
    sum: 'products_production_methods_aggregated_fields',
    avgDistinct: 'products_production_methods_aggregated_fields',
    sumDistinct: 'products_production_methods_aggregated_fields',
    min: 'products_production_methods_aggregated_fields',
    max: 'products_production_methods_aggregated_fields',
  },
  products_production_methods_aggregated_count: {
    id: 'Int',
    production_methods_id: 'Int',
    products_id: 'Int',
  },
  products_production_methods_aggregated_fields: {
    id: 'Float',
    production_methods_id: 'Float',
    products_id: 'Float',
  },
  products_wearables_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_wearables_aggregated_count',
    countDistinct: 'products_wearables_aggregated_count',
    avg: 'products_wearables_aggregated_fields',
    sum: 'products_wearables_aggregated_fields',
    avgDistinct: 'products_wearables_aggregated_fields',
    sumDistinct: 'products_wearables_aggregated_fields',
    min: 'products_wearables_aggregated_fields',
    max: 'products_wearables_aggregated_fields',
  },
  products_wearables_aggregated_count: {
    directus_files_id: 'Int',
    file_format: 'Int',
    id: 'Int',
    primary: 'Int',
    products_id: 'Int',
  },
  products_wearables_aggregated_fields: {
    file_format: 'Float',
    id: 'Float',
    products_id: 'Float',
  },
  file_formats_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'file_formats_aggregated_count',
    countDistinct: 'file_formats_aggregated_count',
    avg: 'file_formats_aggregated_fields',
    sum: 'file_formats_aggregated_fields',
    avgDistinct: 'file_formats_aggregated_fields',
    sumDistinct: 'file_formats_aggregated_fields',
    min: 'file_formats_aggregated_fields',
    max: 'file_formats_aggregated_fields',
  },
  file_formats_aggregated_count: {
    description: 'Int',
    extension: 'Int',
    id: 'Int',
    mime_type: 'Int',
    name: 'Int',
  },
  file_formats_aggregated_fields: {
    id: 'Float',
  },
  products_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_aggregated_count',
    countDistinct: 'products_aggregated_count',
    avg: 'products_aggregated_fields',
    sum: 'products_aggregated_fields',
    avgDistinct: 'products_aggregated_fields',
    sumDistinct: 'products_aggregated_fields',
    min: 'products_aggregated_fields',
    max: 'products_aggregated_fields',
  },
  products_aggregated_count: {
    brand_id: 'Int',
    clo3d_file: 'Int',
    created_at: 'Int',
    description: 'Int',
    discord_channel_id: 'Int',
    fulfiller_id: 'Int',
    id: 'Int',
    name: 'Int',
    nft_token_id: 'Int',
    notion_id: 'Int',
    price: 'Int',
    producer_id: 'Int',
    product_stage: 'Int',
    production_cost: 'Int',
    quantity: 'Int',
    release_date: 'Int',
    sale_currency: 'Int',
    sale_price: 'Int',
    sale_type: 'Int',
    season: 'Int',
    shopify_id: 'Int',
    status: 'Int',
    notes: 'Int',
    contributors: 'Int',
    design_files: 'Int',
    content: 'Int',
    images: 'Int',
    materials: 'Int',
    wearable_files: 'Int',
    production_methods: 'Int',
    client_invoices: 'Int',
    production_invoices: 'Int',
  },
  products_aggregated_fields: {
    brand_id: 'Float',
    fulfiller_id: 'Float',
    id: 'Float',
    nft_token_id: 'Float',
    price: 'Float',
    producer_id: 'Float',
    production_cost: 'Float',
    quantity: 'Float',
    sale_currency: 'Float',
    sale_price: 'Float',
    season: 'Float',
  },
  production_materials_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'production_materials_aggregated_count',
    countDistinct: 'production_materials_aggregated_count',
    avg: 'production_materials_aggregated_fields',
    sum: 'production_materials_aggregated_fields',
    avgDistinct: 'production_materials_aggregated_fields',
    sumDistinct: 'production_materials_aggregated_fields',
    min: 'production_materials_aggregated_fields',
    max: 'production_materials_aggregated_fields',
  },
  production_materials_aggregated_count: {
    base_price: 'Int',
    color_palette: 'Int',
    composition: 'Int',
    created_at: 'Int',
    created_by: 'Int',
    description: 'Int',
    gender: 'Int',
    id: 'Int',
    made_in: 'Int',
    name: 'Int',
    neck_tag: 'Int',
    note: 'Int',
    rating: 'Int',
    size_guide: 'Int',
    supplier: 'Int',
    tags: 'Int',
    production_methods: 'Int',
    stocked_at: 'Int',
  },
  production_materials_aggregated_fields: {
    base_price: 'Float',
    id: 'Float',
    supplier: 'Float',
  },
  invoices_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'invoices_aggregated_count',
    countDistinct: 'invoices_aggregated_count',
    avg: 'invoices_aggregated_fields',
    sum: 'invoices_aggregated_fields',
    avgDistinct: 'invoices_aggregated_fields',
    sumDistinct: 'invoices_aggregated_fields',
    min: 'invoices_aggregated_fields',
    max: 'invoices_aggregated_fields',
  },
  invoices_aggregated_count: {
    id: 'Int',
    user_created: 'Int',
    date_created: 'Int',
    user_updated: 'Int',
    date_updated: 'Int',
    details: 'Int',
    description: 'Int',
    status: 'Int',
    amount: 'Int',
    transaction_url: 'Int',
    production_product_id: 'Int',
    client_product_id: 'Int',
  },
  invoices_aggregated_fields: {
    id: 'Float',
    amount: 'Float',
    production_product_id: 'Float',
    client_product_id: 'Float',
  },
  Mutation: {
    create_brands_items: 'brands',
    create_brands_item: 'brands',
    create_brands_directus_users_items: 'brands_directus_users',
    create_brands_directus_users_item: 'brands_directus_users',
    create_collaborators_items: 'collaborators',
    create_collaborators_item: 'collaborators',
    create_collaborator_roles_items: 'collaborator_roles',
    create_collaborator_roles_item: 'collaborator_roles',
    create_junction_directus_users_skills_items:
      'junction_directus_users_skills',
    create_junction_directus_users_skills_item:
      'junction_directus_users_skills',
    create_skills_items: 'skills',
    create_skills_item: 'skills',
    create_producers_items: 'producers',
    create_producers_item: 'producers',
    create_producers_production_materials_items:
      'producers_production_materials',
    create_producers_production_materials_item:
      'producers_production_materials',
    create_producers_production_methods_items: 'producers_production_methods',
    create_producers_production_methods_item: 'producers_production_methods',
    create_production_methods_items: 'production_methods',
    create_production_methods_item: 'production_methods',
    create_production_materials_production_methods_items:
      'production_materials_production_methods',
    create_production_materials_production_methods_item:
      'production_materials_production_methods',
    create_fulfillers_items: 'fulfillers',
    create_fulfillers_item: 'fulfillers',
    create_price_currencies_items: 'price_currencies',
    create_price_currencies_item: 'price_currencies',
    create_stages_items: 'stages',
    create_stages_item: 'stages',
    create_currencies_items: 'currencies',
    create_currencies_item: 'currencies',
    create_products_content_items: 'products_content',
    create_products_content_item: 'products_content',
    create_products_contributors_items: 'products_contributors',
    create_products_contributors_item: 'products_contributors',
    create_products_design_files_items: 'products_design_files',
    create_products_design_files_item: 'products_design_files',
    create_products_files_items: 'products_files',
    create_products_files_item: 'products_files',
    create_products_production_materials_items: 'products_production_materials',
    create_products_production_materials_item: 'products_production_materials',
    create_products_production_methods_items: 'products_production_methods',
    create_products_production_methods_item: 'products_production_methods',
    create_products_wearables_items: 'products_wearables',
    create_products_wearables_item: 'products_wearables',
    create_file_formats_items: 'file_formats',
    create_file_formats_item: 'file_formats',
    create_products_items: 'products',
    create_products_item: 'products',
    create_production_materials_items: 'production_materials',
    create_production_materials_item: 'production_materials',
    create_invoices_items: 'invoices',
    create_invoices_item: 'invoices',
    update_brands_items: 'brands',
    update_brands_batch: 'brands',
    update_brands_item: 'brands',
    update_brands_directus_users_items: 'brands_directus_users',
    update_brands_directus_users_batch: 'brands_directus_users',
    update_brands_directus_users_item: 'brands_directus_users',
    update_collaborators_items: 'collaborators',
    update_collaborators_batch: 'collaborators',
    update_collaborators_item: 'collaborators',
    update_collaborator_roles_items: 'collaborator_roles',
    update_collaborator_roles_batch: 'collaborator_roles',
    update_collaborator_roles_item: 'collaborator_roles',
    update_junction_directus_users_skills_items:
      'junction_directus_users_skills',
    update_junction_directus_users_skills_batch:
      'junction_directus_users_skills',
    update_junction_directus_users_skills_item:
      'junction_directus_users_skills',
    update_skills_items: 'skills',
    update_skills_batch: 'skills',
    update_skills_item: 'skills',
    update_producers_items: 'producers',
    update_producers_batch: 'producers',
    update_producers_item: 'producers',
    update_producers_production_materials_items:
      'producers_production_materials',
    update_producers_production_materials_batch:
      'producers_production_materials',
    update_producers_production_materials_item:
      'producers_production_materials',
    update_producers_production_methods_items: 'producers_production_methods',
    update_producers_production_methods_batch: 'producers_production_methods',
    update_producers_production_methods_item: 'producers_production_methods',
    update_production_methods_items: 'production_methods',
    update_production_methods_batch: 'production_methods',
    update_production_methods_item: 'production_methods',
    update_production_materials_production_methods_items:
      'production_materials_production_methods',
    update_production_materials_production_methods_batch:
      'production_materials_production_methods',
    update_production_materials_production_methods_item:
      'production_materials_production_methods',
    update_fulfillers_items: 'fulfillers',
    update_fulfillers_batch: 'fulfillers',
    update_fulfillers_item: 'fulfillers',
    update_price_currencies_items: 'price_currencies',
    update_price_currencies_batch: 'price_currencies',
    update_price_currencies_item: 'price_currencies',
    update_stages_items: 'stages',
    update_stages_batch: 'stages',
    update_stages_item: 'stages',
    update_currencies_items: 'currencies',
    update_currencies_batch: 'currencies',
    update_currencies_item: 'currencies',
    update_products_content_items: 'products_content',
    update_products_content_batch: 'products_content',
    update_products_content_item: 'products_content',
    update_products_contributors_items: 'products_contributors',
    update_products_contributors_batch: 'products_contributors',
    update_products_contributors_item: 'products_contributors',
    update_products_design_files_items: 'products_design_files',
    update_products_design_files_batch: 'products_design_files',
    update_products_design_files_item: 'products_design_files',
    update_products_files_items: 'products_files',
    update_products_files_batch: 'products_files',
    update_products_files_item: 'products_files',
    update_products_production_materials_items: 'products_production_materials',
    update_products_production_materials_batch: 'products_production_materials',
    update_products_production_materials_item: 'products_production_materials',
    update_products_production_methods_items: 'products_production_methods',
    update_products_production_methods_batch: 'products_production_methods',
    update_products_production_methods_item: 'products_production_methods',
    update_products_wearables_items: 'products_wearables',
    update_products_wearables_batch: 'products_wearables',
    update_products_wearables_item: 'products_wearables',
    update_file_formats_items: 'file_formats',
    update_file_formats_batch: 'file_formats',
    update_file_formats_item: 'file_formats',
    update_products_items: 'products',
    update_products_batch: 'products',
    update_products_item: 'products',
    update_production_materials_items: 'production_materials',
    update_production_materials_batch: 'production_materials',
    update_production_materials_item: 'production_materials',
    update_invoices_items: 'invoices',
    update_invoices_batch: 'invoices',
    update_invoices_item: 'invoices',
    delete_brands_items: 'delete_many',
    delete_brands_item: 'delete_one',
    delete_brands_directus_users_items: 'delete_many',
    delete_brands_directus_users_item: 'delete_one',
    delete_collaborators_items: 'delete_many',
    delete_collaborators_item: 'delete_one',
    delete_collaborator_roles_items: 'delete_many',
    delete_collaborator_roles_item: 'delete_one',
    delete_junction_directus_users_skills_items: 'delete_many',
    delete_junction_directus_users_skills_item: 'delete_one',
    delete_skills_items: 'delete_many',
    delete_skills_item: 'delete_one',
    delete_producers_items: 'delete_many',
    delete_producers_item: 'delete_one',
    delete_producers_production_materials_items: 'delete_many',
    delete_producers_production_materials_item: 'delete_one',
    delete_producers_production_methods_items: 'delete_many',
    delete_producers_production_methods_item: 'delete_one',
    delete_production_methods_items: 'delete_many',
    delete_production_methods_item: 'delete_one',
    delete_production_materials_production_methods_items: 'delete_many',
    delete_production_materials_production_methods_item: 'delete_one',
    delete_fulfillers_items: 'delete_many',
    delete_fulfillers_item: 'delete_one',
    delete_price_currencies_items: 'delete_many',
    delete_price_currencies_item: 'delete_one',
    delete_stages_items: 'delete_many',
    delete_stages_item: 'delete_one',
    delete_currencies_items: 'delete_many',
    delete_currencies_item: 'delete_one',
    delete_products_content_items: 'delete_many',
    delete_products_content_item: 'delete_one',
    delete_products_contributors_items: 'delete_many',
    delete_products_contributors_item: 'delete_one',
    delete_products_design_files_items: 'delete_many',
    delete_products_design_files_item: 'delete_one',
    delete_products_files_items: 'delete_many',
    delete_products_files_item: 'delete_one',
    delete_products_production_materials_items: 'delete_many',
    delete_products_production_materials_item: 'delete_one',
    delete_products_production_methods_items: 'delete_many',
    delete_products_production_methods_item: 'delete_one',
    delete_products_wearables_items: 'delete_many',
    delete_products_wearables_item: 'delete_one',
    delete_file_formats_items: 'delete_many',
    delete_file_formats_item: 'delete_one',
    delete_products_items: 'delete_many',
    delete_products_item: 'delete_one',
    delete_production_materials_items: 'delete_many',
    delete_production_materials_item: 'delete_one',
    delete_invoices_items: 'delete_many',
    delete_invoices_item: 'delete_one',
  },
  delete_many: {
    ids: 'ID',
  },
  delete_one: {
    id: 'ID',
  },
};

export const Ops = {
  query: 'Query' as const,
  mutation: 'Mutation' as const,
};
