/* eslint-disable */

export const AllTypesProps: Record<string, any> = {
  Query: {
    server_specs_graphql: {
      scope: 'graphql_sdl_scope',
    },
    collections_by_name: {},
    fields_in_collection: {},
    fields_by_name: {},
    relations_in_collection: {},
    relations_by_name: {},
    roles: {
      filter: 'directus_roles_filter',
    },
    roles_by_id: {},
    roles_aggregated: {
      filter: 'directus_roles_filter',
    },
    files: {
      filter: 'directus_files_filter',
    },
    files_by_id: {},
    files_aggregated: {
      filter: 'directus_files_filter',
    },
    activity: {
      filter: 'directus_activity_filter',
    },
    activity_by_id: {},
    activity_aggregated: {
      filter: 'directus_activity_filter',
    },
    folders: {
      filter: 'directus_folders_filter',
    },
    folders_by_id: {},
    folders_aggregated: {
      filter: 'directus_folders_filter',
    },
    permissions: {
      filter: 'directus_permissions_filter',
    },
    permissions_by_id: {},
    permissions_aggregated: {
      filter: 'directus_permissions_filter',
    },
    users: {
      filter: 'directus_users_filter',
    },
    users_by_id: {},
    users_aggregated: {
      filter: 'directus_users_filter',
    },
    presets: {
      filter: 'directus_presets_filter',
    },
    presets_by_id: {},
    presets_aggregated: {
      filter: 'directus_presets_filter',
    },
    revisions: {
      filter: 'directus_revisions_filter',
    },
    revisions_by_id: {},
    revisions_aggregated: {
      filter: 'directus_revisions_filter',
    },
    webhooks: {
      filter: 'directus_webhooks_filter',
    },
    webhooks_by_id: {},
    webhooks_aggregated: {
      filter: 'directus_webhooks_filter',
    },
    panels: {
      filter: 'directus_panels_filter',
    },
    panels_by_id: {},
    panels_aggregated: {
      filter: 'directus_panels_filter',
    },
    notifications: {
      filter: 'directus_notifications_filter',
    },
    notifications_by_id: {},
    notifications_aggregated: {
      filter: 'directus_notifications_filter',
    },
    shares: {
      filter: 'directus_shares_filter',
    },
    shares_by_id: {},
    shares_aggregated: {
      filter: 'directus_shares_filter',
    },
    flows: {
      filter: 'directus_flows_filter',
    },
    flows_by_id: {},
    flows_aggregated: {
      filter: 'directus_flows_filter',
    },
    operations: {
      filter: 'directus_operations_filter',
    },
    operations_by_id: {},
    operations_aggregated: {
      filter: 'directus_operations_filter',
    },
    dashboards: {
      filter: 'directus_dashboards_filter',
    },
    dashboards_by_id: {},
    dashboards_aggregated: {
      filter: 'directus_dashboards_filter',
    },
  },
  JSON: `scalar.JSON` as const,
  graphql_sdl_scope: 'enum' as const,
  directus_users: {
    avatar: {
      filter: 'directus_files_filter',
    },
    role: {
      filter: 'directus_roles_filter',
    },
  },
  directus_files: {
    folder: {
      filter: 'directus_folders_filter',
    },
    uploaded_by: {
      filter: 'directus_users_filter',
    },
    modified_by: {
      filter: 'directus_users_filter',
    },
  },
  directus_folders: {
    parent: {
      filter: 'directus_folders_filter',
    },
  },
  directus_folders_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    parent: 'directus_folders_filter',
    _and: 'directus_folders_filter',
    _or: 'directus_folders_filter',
  },
  string_filter_operators: {},
  directus_users_filter: {
    id: 'string_filter_operators',
    first_name: 'string_filter_operators',
    last_name: 'string_filter_operators',
    email: 'string_filter_operators',
    password: 'string_filter_operators',
    location: 'string_filter_operators',
    title: 'string_filter_operators',
    description: 'string_filter_operators',
    tags: 'string_filter_operators',
    tags_func: 'count_function_filter_operators',
    avatar: 'directus_files_filter',
    language: 'string_filter_operators',
    theme: 'string_filter_operators',
    tfa_secret: 'string_filter_operators',
    status: 'string_filter_operators',
    role: 'directus_roles_filter',
    token: 'string_filter_operators',
    last_access: 'date_filter_operators',
    last_access_func: 'datetime_function_filter_operators',
    last_page: 'string_filter_operators',
    provider: 'string_filter_operators',
    external_identifier: 'string_filter_operators',
    auth_data: 'string_filter_operators',
    auth_data_func: 'count_function_filter_operators',
    email_notifications: 'boolean_filter_operators',
    _and: 'directus_users_filter',
    _or: 'directus_users_filter',
  },
  count_function_filter_operators: {
    count: 'number_filter_operators',
  },
  number_filter_operators: {},
  directus_files_filter: {
    id: 'string_filter_operators',
    storage: 'string_filter_operators',
    filename_disk: 'string_filter_operators',
    filename_download: 'string_filter_operators',
    title: 'string_filter_operators',
    type: 'string_filter_operators',
    folder: 'directus_folders_filter',
    uploaded_by: 'directus_users_filter',
    uploaded_on: 'date_filter_operators',
    uploaded_on_func: 'datetime_function_filter_operators',
    modified_by: 'directus_users_filter',
    modified_on: 'date_filter_operators',
    modified_on_func: 'datetime_function_filter_operators',
    charset: 'string_filter_operators',
    filesize: 'string_filter_operators',
    width: 'number_filter_operators',
    height: 'number_filter_operators',
    duration: 'number_filter_operators',
    embed: 'string_filter_operators',
    description: 'string_filter_operators',
    location: 'string_filter_operators',
    tags: 'string_filter_operators',
    tags_func: 'count_function_filter_operators',
    metadata: 'string_filter_operators',
    metadata_func: 'count_function_filter_operators',
    _and: 'directus_files_filter',
    _or: 'directus_files_filter',
  },
  date_filter_operators: {},
  datetime_function_filter_operators: {
    year: 'number_filter_operators',
    month: 'number_filter_operators',
    week: 'number_filter_operators',
    day: 'number_filter_operators',
    weekday: 'number_filter_operators',
    hour: 'number_filter_operators',
    minute: 'number_filter_operators',
    second: 'number_filter_operators',
  },
  directus_roles_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    icon: 'string_filter_operators',
    description: 'string_filter_operators',
    ip_access: 'string_filter_operators',
    enforce_tfa: 'boolean_filter_operators',
    admin_access: 'boolean_filter_operators',
    app_access: 'boolean_filter_operators',
    users: 'directus_users_filter',
    users_func: 'count_function_filter_operators',
    _and: 'directus_roles_filter',
    _or: 'directus_roles_filter',
  },
  boolean_filter_operators: {},
  Date: `scalar.Date` as const,
  directus_roles: {
    users: {
      filter: 'directus_users_filter',
    },
  },
  directus_activity: {
    user: {
      filter: 'directus_users_filter',
    },
    revisions: {
      filter: 'directus_revisions_filter',
    },
  },
  directus_revisions: {
    activity: {
      filter: 'directus_activity_filter',
    },
    parent: {
      filter: 'directus_revisions_filter',
    },
  },
  directus_activity_filter: {
    id: 'number_filter_operators',
    action: 'string_filter_operators',
    user: 'directus_users_filter',
    timestamp: 'date_filter_operators',
    timestamp_func: 'datetime_function_filter_operators',
    ip: 'string_filter_operators',
    user_agent: 'string_filter_operators',
    collection: 'string_filter_operators',
    item: 'string_filter_operators',
    comment: 'string_filter_operators',
    revisions: 'directus_revisions_filter',
    revisions_func: 'count_function_filter_operators',
    _and: 'directus_activity_filter',
    _or: 'directus_activity_filter',
  },
  directus_revisions_filter: {
    id: 'number_filter_operators',
    activity: 'directus_activity_filter',
    collection: 'string_filter_operators',
    item: 'string_filter_operators',
    data: 'string_filter_operators',
    data_func: 'count_function_filter_operators',
    delta: 'string_filter_operators',
    delta_func: 'count_function_filter_operators',
    parent: 'directus_revisions_filter',
    _and: 'directus_revisions_filter',
    _or: 'directus_revisions_filter',
  },
  directus_permissions: {
    role: {
      filter: 'directus_roles_filter',
    },
  },
  directus_permissions_filter: {
    id: 'number_filter_operators',
    role: 'directus_roles_filter',
    collection: 'string_filter_operators',
    action: 'string_filter_operators',
    permissions: 'string_filter_operators',
    permissions_func: 'count_function_filter_operators',
    validation: 'string_filter_operators',
    validation_func: 'count_function_filter_operators',
    presets: 'string_filter_operators',
    presets_func: 'count_function_filter_operators',
    fields: 'string_filter_operators',
    _and: 'directus_permissions_filter',
    _or: 'directus_permissions_filter',
  },
  directus_presets: {
    user: {
      filter: 'directus_users_filter',
    },
    role: {
      filter: 'directus_roles_filter',
    },
  },
  directus_presets_filter: {
    id: 'number_filter_operators',
    bookmark: 'string_filter_operators',
    user: 'directus_users_filter',
    role: 'directus_roles_filter',
    collection: 'string_filter_operators',
    search: 'string_filter_operators',
    layout: 'string_filter_operators',
    layout_query: 'string_filter_operators',
    layout_query_func: 'count_function_filter_operators',
    layout_options: 'string_filter_operators',
    layout_options_func: 'count_function_filter_operators',
    refresh_interval: 'number_filter_operators',
    filter: 'string_filter_operators',
    filter_func: 'count_function_filter_operators',
    icon: 'string_filter_operators',
    color: 'string_filter_operators',
    _and: 'directus_presets_filter',
    _or: 'directus_presets_filter',
  },
  directus_webhooks_filter: {
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    method: 'string_filter_operators',
    url: 'string_filter_operators',
    status: 'string_filter_operators',
    data: 'boolean_filter_operators',
    actions: 'string_filter_operators',
    collections: 'string_filter_operators',
    headers: 'string_filter_operators',
    headers_func: 'count_function_filter_operators',
    _and: 'directus_webhooks_filter',
    _or: 'directus_webhooks_filter',
  },
  directus_settings: {
    project_logo: {
      filter: 'directus_files_filter',
    },
    public_foreground: {
      filter: 'directus_files_filter',
    },
    public_background: {
      filter: 'directus_files_filter',
    },
    storage_default_folder: {
      filter: 'directus_folders_filter',
    },
  },
  directus_panels: {
    dashboard: {
      filter: 'directus_dashboards_filter',
    },
    user_created: {
      filter: 'directus_users_filter',
    },
  },
  directus_dashboards: {
    user_created: {
      filter: 'directus_users_filter',
    },
    panels: {
      filter: 'directus_panels_filter',
    },
  },
  directus_panels_filter: {
    id: 'string_filter_operators',
    dashboard: 'directus_dashboards_filter',
    name: 'string_filter_operators',
    icon: 'string_filter_operators',
    color: 'string_filter_operators',
    show_header: 'boolean_filter_operators',
    note: 'string_filter_operators',
    type: 'string_filter_operators',
    position_x: 'number_filter_operators',
    position_y: 'number_filter_operators',
    width: 'number_filter_operators',
    height: 'number_filter_operators',
    options: 'string_filter_operators',
    options_func: 'count_function_filter_operators',
    date_created: 'date_filter_operators',
    date_created_func: 'datetime_function_filter_operators',
    user_created: 'directus_users_filter',
    _and: 'directus_panels_filter',
    _or: 'directus_panels_filter',
  },
  directus_dashboards_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    icon: 'string_filter_operators',
    note: 'string_filter_operators',
    date_created: 'date_filter_operators',
    date_created_func: 'datetime_function_filter_operators',
    user_created: 'directus_users_filter',
    color: 'string_filter_operators',
    panels: 'directus_panels_filter',
    panels_func: 'count_function_filter_operators',
    _and: 'directus_dashboards_filter',
    _or: 'directus_dashboards_filter',
  },
  directus_notifications: {
    recipient: {
      filter: 'directus_users_filter',
    },
    sender: {
      filter: 'directus_users_filter',
    },
  },
  directus_notifications_filter: {
    id: 'number_filter_operators',
    timestamp: 'date_filter_operators',
    timestamp_func: 'datetime_function_filter_operators',
    status: 'string_filter_operators',
    recipient: 'directus_users_filter',
    sender: 'directus_users_filter',
    subject: 'string_filter_operators',
    message: 'string_filter_operators',
    collection: 'string_filter_operators',
    item: 'string_filter_operators',
    _and: 'directus_notifications_filter',
    _or: 'directus_notifications_filter',
  },
  directus_shares: {
    role: {
      filter: 'directus_roles_filter',
    },
    user_created: {
      filter: 'directus_users_filter',
    },
  },
  directus_shares_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    collection: 'string_filter_operators',
    item: 'string_filter_operators',
    role: 'directus_roles_filter',
    password: 'string_filter_operators',
    user_created: 'directus_users_filter',
    date_created: 'date_filter_operators',
    date_created_func: 'datetime_function_filter_operators',
    date_start: 'date_filter_operators',
    date_start_func: 'datetime_function_filter_operators',
    date_end: 'date_filter_operators',
    date_end_func: 'datetime_function_filter_operators',
    times_used: 'number_filter_operators',
    max_uses: 'number_filter_operators',
    _and: 'directus_shares_filter',
    _or: 'directus_shares_filter',
  },
  directus_flows: {
    operation: {
      filter: 'directus_operations_filter',
    },
    user_created: {
      filter: 'directus_users_filter',
    },
    operations: {
      filter: 'directus_operations_filter',
    },
  },
  directus_operations: {
    resolve: {
      filter: 'directus_operations_filter',
    },
    reject: {
      filter: 'directus_operations_filter',
    },
    flow: {
      filter: 'directus_flows_filter',
    },
    user_created: {
      filter: 'directus_users_filter',
    },
  },
  directus_operations_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    key: 'string_filter_operators',
    type: 'string_filter_operators',
    position_x: 'number_filter_operators',
    position_y: 'number_filter_operators',
    options: 'string_filter_operators',
    options_func: 'count_function_filter_operators',
    resolve: 'directus_operations_filter',
    reject: 'directus_operations_filter',
    flow: 'directus_flows_filter',
    date_created: 'date_filter_operators',
    date_created_func: 'datetime_function_filter_operators',
    user_created: 'directus_users_filter',
    _and: 'directus_operations_filter',
    _or: 'directus_operations_filter',
  },
  directus_flows_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    icon: 'string_filter_operators',
    color: 'string_filter_operators',
    description: 'string_filter_operators',
    status: 'string_filter_operators',
    trigger: 'string_filter_operators',
    accountability: 'string_filter_operators',
    options: 'string_filter_operators',
    options_func: 'count_function_filter_operators',
    operation: 'directus_operations_filter',
    date_created: 'date_filter_operators',
    date_created_func: 'datetime_function_filter_operators',
    user_created: 'directus_users_filter',
    operations: 'directus_operations_filter',
    operations_func: 'count_function_filter_operators',
    _and: 'directus_flows_filter',
    _or: 'directus_flows_filter',
  },
  Mutation: {
    auth_login: {
      mode: 'auth_mode',
    },
    auth_refresh: {
      mode: 'auth_mode',
    },
    auth_logout: {},
    auth_password_request: {},
    auth_password_reset: {},
    users_me_tfa_generate: {},
    users_me_tfa_enable: {},
    users_me_tfa_disable: {},
    utils_hash_generate: {},
    utils_hash_verify: {},
    utils_sort: {},
    utils_revert: {},
    users_invite_accept: {},
    create_collections_item: {
      data: 'create_directus_collections_input',
    },
    update_collections_item: {
      data: 'update_directus_collections_input',
    },
    delete_collections_item: {},
    create_fields_item: {
      data: 'create_directus_fields_input',
    },
    update_fields_item: {
      data: 'update_directus_fields_input',
    },
    delete_fields_item: {},
    create_relations_item: {
      data: 'create_directus_relations_input',
    },
    update_relations_item: {
      data: 'update_directus_relations_input',
    },
    delete_relations_item: {},
    update_users_me: {
      data: 'update_directus_users_input',
    },
    create_comment: {},
    update_comment: {},
    delete_comment: {},
    import_file: {
      data: 'create_directus_files_input',
    },
    users_invite: {},
    create_roles_items: {
      filter: 'directus_roles_filter',
      data: 'create_directus_roles_input',
    },
    create_roles_item: {
      data: 'create_directus_roles_input',
    },
    create_files_items: {
      filter: 'directus_files_filter',
      data: 'create_directus_files_input',
    },
    create_files_item: {
      data: 'create_directus_files_input',
    },
    create_folders_items: {
      filter: 'directus_folders_filter',
      data: 'create_directus_folders_input',
    },
    create_folders_item: {
      data: 'create_directus_folders_input',
    },
    create_permissions_items: {
      filter: 'directus_permissions_filter',
      data: 'create_directus_permissions_input',
    },
    create_permissions_item: {
      data: 'create_directus_permissions_input',
    },
    create_users_items: {
      filter: 'directus_users_filter',
      data: 'create_directus_users_input',
    },
    create_users_item: {
      data: 'create_directus_users_input',
    },
    create_presets_items: {
      filter: 'directus_presets_filter',
      data: 'create_directus_presets_input',
    },
    create_presets_item: {
      data: 'create_directus_presets_input',
    },
    create_webhooks_items: {
      filter: 'directus_webhooks_filter',
      data: 'create_directus_webhooks_input',
    },
    create_webhooks_item: {
      data: 'create_directus_webhooks_input',
    },
    create_panels_items: {
      filter: 'directus_panels_filter',
      data: 'create_directus_panels_input',
    },
    create_panels_item: {
      data: 'create_directus_panels_input',
    },
    create_notifications_items: {
      filter: 'directus_notifications_filter',
      data: 'create_directus_notifications_input',
    },
    create_notifications_item: {
      data: 'create_directus_notifications_input',
    },
    create_shares_items: {
      filter: 'directus_shares_filter',
      data: 'create_directus_shares_input',
    },
    create_shares_item: {
      data: 'create_directus_shares_input',
    },
    create_flows_items: {
      filter: 'directus_flows_filter',
      data: 'create_directus_flows_input',
    },
    create_flows_item: {
      data: 'create_directus_flows_input',
    },
    create_operations_items: {
      filter: 'directus_operations_filter',
      data: 'create_directus_operations_input',
    },
    create_operations_item: {
      data: 'create_directus_operations_input',
    },
    create_dashboards_items: {
      filter: 'directus_dashboards_filter',
      data: 'create_directus_dashboards_input',
    },
    create_dashboards_item: {
      data: 'create_directus_dashboards_input',
    },
    update_roles_items: {
      filter: 'directus_roles_filter',
      data: 'update_directus_roles_input',
    },
    update_roles_item: {
      data: 'update_directus_roles_input',
    },
    update_files_items: {
      filter: 'directus_files_filter',
      data: 'update_directus_files_input',
    },
    update_files_item: {
      data: 'update_directus_files_input',
    },
    update_folders_items: {
      filter: 'directus_folders_filter',
      data: 'update_directus_folders_input',
    },
    update_folders_item: {
      data: 'update_directus_folders_input',
    },
    update_permissions_items: {
      filter: 'directus_permissions_filter',
      data: 'update_directus_permissions_input',
    },
    update_permissions_item: {
      data: 'update_directus_permissions_input',
    },
    update_users_items: {
      filter: 'directus_users_filter',
      data: 'update_directus_users_input',
    },
    update_users_item: {
      data: 'update_directus_users_input',
    },
    update_presets_items: {
      filter: 'directus_presets_filter',
      data: 'update_directus_presets_input',
    },
    update_presets_item: {
      data: 'update_directus_presets_input',
    },
    update_webhooks_items: {
      filter: 'directus_webhooks_filter',
      data: 'update_directus_webhooks_input',
    },
    update_webhooks_item: {
      data: 'update_directus_webhooks_input',
    },
    update_settings: {
      data: 'update_directus_settings_input',
    },
    update_panels_items: {
      filter: 'directus_panels_filter',
      data: 'update_directus_panels_input',
    },
    update_panels_item: {
      data: 'update_directus_panels_input',
    },
    update_notifications_items: {
      filter: 'directus_notifications_filter',
      data: 'update_directus_notifications_input',
    },
    update_notifications_item: {
      data: 'update_directus_notifications_input',
    },
    update_shares_items: {
      filter: 'directus_shares_filter',
      data: 'update_directus_shares_input',
    },
    update_shares_item: {
      data: 'update_directus_shares_input',
    },
    update_flows_items: {
      filter: 'directus_flows_filter',
      data: 'update_directus_flows_input',
    },
    update_flows_item: {
      data: 'update_directus_flows_input',
    },
    update_operations_items: {
      filter: 'directus_operations_filter',
      data: 'update_directus_operations_input',
    },
    update_operations_item: {
      data: 'update_directus_operations_input',
    },
    update_dashboards_items: {
      filter: 'directus_dashboards_filter',
      data: 'update_directus_dashboards_input',
    },
    update_dashboards_item: {
      data: 'update_directus_dashboards_input',
    },
    delete_roles_items: {},
    delete_roles_item: {},
    delete_files_items: {},
    delete_files_item: {},
    delete_folders_items: {},
    delete_folders_item: {},
    delete_permissions_items: {},
    delete_permissions_item: {},
    delete_users_items: {},
    delete_users_item: {},
    delete_presets_items: {},
    delete_presets_item: {},
    delete_webhooks_items: {},
    delete_webhooks_item: {},
    delete_panels_items: {},
    delete_panels_item: {},
    delete_notifications_items: {},
    delete_notifications_item: {},
    delete_shares_items: {},
    delete_shares_item: {},
    delete_flows_items: {},
    delete_flows_item: {},
    delete_operations_items: {},
    delete_operations_item: {},
    delete_dashboards_items: {},
    delete_dashboards_item: {},
  },
  auth_mode: 'enum' as const,
  Void: `scalar.Void` as const,
  create_directus_collections_input: {
    meta: 'directus_collections_meta_input',
    schema: 'directus_collections_schema_input',
    fields: 'create_directus_collections_fields_input',
  },
  directus_collections_meta_input: {
    translations: 'JSON',
    item_duplication_fields: 'JSON',
  },
  directus_collections_schema_input: {},
  create_directus_collections_fields_input: {
    meta: 'directus_fields_meta_input',
    schema: 'directus_fields_schema_input',
  },
  directus_fields_meta_input: {
    options: 'JSON',
    display_options: 'JSON',
    translations: 'JSON',
    conditions: 'JSON',
    validation: 'JSON',
  },
  directus_fields_schema_input: {},
  update_directus_collections_input: {
    meta: 'directus_collections_meta_input',
  },
  create_directus_fields_input: {
    meta: 'directus_fields_meta_input',
    schema: 'directus_fields_schema_input',
  },
  update_directus_fields_input: {
    meta: 'directus_fields_meta_input',
    schema: 'directus_fields_schema_input',
  },
  create_directus_relations_input: {
    schema: 'directus_relations_schema_input',
    meta: 'directus_relations_meta_input',
  },
  directus_relations_schema_input: {},
  directus_relations_meta_input: {},
  update_directus_relations_input: {
    schema: 'directus_relations_schema_input',
    meta: 'directus_relations_meta_input',
  },
  update_directus_users_input: {
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    avatar: 'update_directus_files_input',
    role: 'update_directus_roles_input',
    last_access: 'Date',
    last_access_func: 'datetime_functionsInput',
    auth_data: 'JSON',
    auth_data_func: 'count_functionsInput',
  },
  count_functionsInput: {},
  update_directus_files_input: {
    folder: 'update_directus_folders_input',
    uploaded_by: 'update_directus_users_input',
    uploaded_on: 'Date',
    uploaded_on_func: 'datetime_functionsInput',
    modified_by: 'update_directus_users_input',
    modified_on: 'Date',
    modified_on_func: 'datetime_functionsInput',
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    metadata: 'JSON',
    metadata_func: 'count_functionsInput',
  },
  update_directus_folders_input: {
    parent: 'update_directus_folders_input',
  },
  datetime_functionsInput: {},
  update_directus_roles_input: {
    users: 'update_directus_users_input',
    users_func: 'count_functionsInput',
  },
  create_directus_files_input: {
    folder: 'create_directus_folders_input',
    uploaded_by: 'create_directus_users_input',
    uploaded_on: 'Date',
    uploaded_on_func: 'datetime_functionsInput',
    modified_by: 'create_directus_users_input',
    modified_on: 'Date',
    modified_on_func: 'datetime_functionsInput',
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    metadata: 'JSON',
    metadata_func: 'count_functionsInput',
  },
  create_directus_folders_input: {
    parent: 'create_directus_folders_input',
  },
  create_directus_users_input: {
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    avatar: 'create_directus_files_input',
    role: 'create_directus_roles_input',
    last_access: 'Date',
    last_access_func: 'datetime_functionsInput',
    auth_data: 'JSON',
    auth_data_func: 'count_functionsInput',
  },
  create_directus_roles_input: {
    users: 'create_directus_users_input',
    users_func: 'count_functionsInput',
  },
  create_directus_permissions_input: {
    role: 'create_directus_roles_input',
    permissions: 'JSON',
    permissions_func: 'count_functionsInput',
    validation: 'JSON',
    validation_func: 'count_functionsInput',
    presets: 'JSON',
    presets_func: 'count_functionsInput',
  },
  create_directus_presets_input: {
    user: 'create_directus_users_input',
    role: 'create_directus_roles_input',
    layout_query: 'JSON',
    layout_query_func: 'count_functionsInput',
    layout_options: 'JSON',
    layout_options_func: 'count_functionsInput',
    filter: 'JSON',
    filter_func: 'count_functionsInput',
  },
  create_directus_webhooks_input: {
    headers: 'JSON',
    headers_func: 'count_functionsInput',
  },
  create_directus_panels_input: {
    dashboard: 'create_directus_dashboards_input',
    options: 'JSON',
    options_func: 'count_functionsInput',
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    user_created: 'create_directus_users_input',
  },
  create_directus_dashboards_input: {
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    user_created: 'create_directus_users_input',
    panels: 'create_directus_panels_input',
    panels_func: 'count_functionsInput',
  },
  create_directus_notifications_input: {
    timestamp: 'Date',
    timestamp_func: 'datetime_functionsInput',
    recipient: 'create_directus_users_input',
    sender: 'create_directus_users_input',
  },
  create_directus_shares_input: {
    role: 'create_directus_roles_input',
    user_created: 'create_directus_users_input',
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    date_start: 'Date',
    date_start_func: 'datetime_functionsInput',
    date_end: 'Date',
    date_end_func: 'datetime_functionsInput',
  },
  create_directus_flows_input: {
    options: 'JSON',
    options_func: 'count_functionsInput',
    operation: 'create_directus_operations_input',
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    user_created: 'create_directus_users_input',
    operations: 'create_directus_operations_input',
    operations_func: 'count_functionsInput',
  },
  create_directus_operations_input: {
    options: 'JSON',
    options_func: 'count_functionsInput',
    resolve: 'create_directus_operations_input',
    reject: 'create_directus_operations_input',
    flow: 'create_directus_flows_input',
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    user_created: 'create_directus_users_input',
  },
  update_directus_permissions_input: {
    role: 'update_directus_roles_input',
    permissions: 'JSON',
    permissions_func: 'count_functionsInput',
    validation: 'JSON',
    validation_func: 'count_functionsInput',
    presets: 'JSON',
    presets_func: 'count_functionsInput',
  },
  update_directus_presets_input: {
    user: 'update_directus_users_input',
    role: 'update_directus_roles_input',
    layout_query: 'JSON',
    layout_query_func: 'count_functionsInput',
    layout_options: 'JSON',
    layout_options_func: 'count_functionsInput',
    filter: 'JSON',
    filter_func: 'count_functionsInput',
  },
  update_directus_webhooks_input: {
    headers: 'JSON',
    headers_func: 'count_functionsInput',
  },
  update_directus_settings_input: {
    project_logo: 'update_directus_files_input',
    public_foreground: 'update_directus_files_input',
    public_background: 'update_directus_files_input',
    storage_asset_presets: 'JSON',
    storage_asset_presets_func: 'count_functionsInput',
    storage_default_folder: 'update_directus_folders_input',
    basemaps: 'JSON',
    basemaps_func: 'count_functionsInput',
    module_bar: 'JSON',
    module_bar_func: 'count_functionsInput',
    translation_strings: 'JSON',
    translation_strings_func: 'count_functionsInput',
  },
  update_directus_panels_input: {
    dashboard: 'update_directus_dashboards_input',
    options: 'JSON',
    options_func: 'count_functionsInput',
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    user_created: 'update_directus_users_input',
  },
  update_directus_dashboards_input: {
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    user_created: 'update_directus_users_input',
    panels: 'update_directus_panels_input',
    panels_func: 'count_functionsInput',
  },
  update_directus_notifications_input: {
    timestamp: 'Date',
    timestamp_func: 'datetime_functionsInput',
    recipient: 'update_directus_users_input',
    sender: 'update_directus_users_input',
  },
  update_directus_shares_input: {
    role: 'update_directus_roles_input',
    user_created: 'update_directus_users_input',
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    date_start: 'Date',
    date_start_func: 'datetime_functionsInput',
    date_end: 'Date',
    date_end_func: 'datetime_functionsInput',
  },
  update_directus_flows_input: {
    options: 'JSON',
    options_func: 'count_functionsInput',
    operation: 'update_directus_operations_input',
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    user_created: 'update_directus_users_input',
    operations: 'update_directus_operations_input',
    operations_func: 'count_functionsInput',
  },
  update_directus_operations_input: {
    options: 'JSON',
    options_func: 'count_functionsInput',
    resolve: 'update_directus_operations_input',
    reject: 'update_directus_operations_input',
    flow: 'update_directus_flows_input',
    date_created: 'Date',
    date_created_func: 'datetime_functionsInput',
    user_created: 'update_directus_users_input',
  },
};

export const ReturnTypes: Record<string, any> = {
  Query: {
    extensions: 'extensions',
    server_specs_oas: 'JSON',
    server_specs_graphql: 'String',
    server_ping: 'String',
    server_info: 'server_info',
    server_health: 'JSON',
    collections: 'directus_collections',
    collections_by_name: 'directus_collections',
    fields: 'directus_fields',
    fields_in_collection: 'directus_fields',
    fields_by_name: 'directus_fields',
    relations: 'directus_relations',
    relations_in_collection: 'directus_relations',
    relations_by_name: 'directus_relations',
    users_me: 'directus_users',
    roles: 'directus_roles',
    roles_by_id: 'directus_roles',
    roles_aggregated: 'directus_roles_aggregated',
    files: 'directus_files',
    files_by_id: 'directus_files',
    files_aggregated: 'directus_files_aggregated',
    activity: 'directus_activity',
    activity_by_id: 'directus_activity',
    activity_aggregated: 'directus_activity_aggregated',
    folders: 'directus_folders',
    folders_by_id: 'directus_folders',
    folders_aggregated: 'directus_folders_aggregated',
    permissions: 'directus_permissions',
    permissions_by_id: 'directus_permissions',
    permissions_aggregated: 'directus_permissions_aggregated',
    users: 'directus_users',
    users_by_id: 'directus_users',
    users_aggregated: 'directus_users_aggregated',
    presets: 'directus_presets',
    presets_by_id: 'directus_presets',
    presets_aggregated: 'directus_presets_aggregated',
    revisions: 'directus_revisions',
    revisions_by_id: 'directus_revisions',
    revisions_aggregated: 'directus_revisions_aggregated',
    webhooks: 'directus_webhooks',
    webhooks_by_id: 'directus_webhooks',
    webhooks_aggregated: 'directus_webhooks_aggregated',
    settings: 'directus_settings',
    panels: 'directus_panels',
    panels_by_id: 'directus_panels',
    panels_aggregated: 'directus_panels_aggregated',
    notifications: 'directus_notifications',
    notifications_by_id: 'directus_notifications',
    notifications_aggregated: 'directus_notifications_aggregated',
    shares: 'directus_shares',
    shares_by_id: 'directus_shares',
    shares_aggregated: 'directus_shares_aggregated',
    flows: 'directus_flows',
    flows_by_id: 'directus_flows',
    flows_aggregated: 'directus_flows_aggregated',
    operations: 'directus_operations',
    operations_by_id: 'directus_operations',
    operations_aggregated: 'directus_operations_aggregated',
    dashboards: 'directus_dashboards',
    dashboards_by_id: 'directus_dashboards',
    dashboards_aggregated: 'directus_dashboards_aggregated',
  },
  extensions: {
    interfaces: 'String',
    displays: 'String',
    layouts: 'String',
    modules: 'String',
  },
  JSON: `scalar.JSON` as const,
  server_info: {
    project_name: 'String',
    project_logo: 'String',
    project_color: 'String',
    project_foreground: 'String',
    project_background: 'String',
    project_note: 'String',
    custom_css: 'String',
    directus: 'server_info_directus',
    node: 'server_info_node',
    os: 'server_info_os',
  },
  server_info_directus: {
    version: 'String',
  },
  server_info_node: {
    version: 'String',
    uptime: 'Int',
  },
  server_info_os: {
    type: 'String',
    version: 'String',
    uptime: 'Int',
    totalmem: 'Int',
  },
  directus_collections: {
    collection: 'String',
    meta: 'directus_collections_meta',
    schema: 'directus_collections_schema',
  },
  directus_collections_meta: {
    collection: 'String',
    icon: 'String',
    note: 'String',
    display_template: 'String',
    hidden: 'Boolean',
    singleton: 'Boolean',
    translations: 'JSON',
    archive_field: 'String',
    archive_app_filter: 'Boolean',
    archive_value: 'String',
    unarchive_value: 'String',
    sort_field: 'String',
    accountability: 'String',
    color: 'String',
    item_duplication_fields: 'JSON',
    sort: 'Int',
    group: 'String',
    collapse: 'String',
  },
  directus_collections_schema: {
    name: 'String',
    comment: 'String',
  },
  directus_fields: {
    collection: 'String',
    field: 'String',
    type: 'String',
    meta: 'directus_fields_meta',
    schema: 'directus_fields_schema',
  },
  directus_fields_meta: {
    id: 'Int',
    collection: 'String',
    field: 'String',
    special: 'String',
    interface: 'String',
    options: 'JSON',
    display: 'String',
    display_options: 'JSON',
    readonly: 'Boolean',
    hidden: 'Boolean',
    sort: 'Int',
    width: 'String',
    translations: 'JSON',
    note: 'String',
    conditions: 'JSON',
    required: 'Boolean',
    group: 'String',
    validation: 'JSON',
    validation_message: 'String',
  },
  directus_fields_schema: {
    name: 'String',
    table: 'String',
    data_type: 'String',
    default_value: 'String',
    max_length: 'Int',
    numeric_precision: 'Int',
    numeric_scale: 'Int',
    is_nullable: 'Boolean',
    is_unique: 'Boolean',
    is_primary_key: 'Boolean',
    has_auto_increment: 'Boolean',
    foreign_key_column: 'String',
    foreign_key_table: 'String',
    comment: 'String',
  },
  directus_relations: {
    collection: 'String',
    field: 'String',
    related_collection: 'String',
    schema: 'directus_relations_schema',
    meta: 'directus_relations_meta',
  },
  directus_relations_schema: {
    table: 'String',
    column: 'String',
    foreign_key_table: 'String',
    foreign_key_column: 'String',
    constraint_name: 'String',
    on_update: 'String',
    on_delete: 'String',
  },
  directus_relations_meta: {
    id: 'Int',
    many_collection: 'String',
    many_field: 'String',
    one_collection: 'String',
    one_field: 'String',
    one_collection_field: 'String',
    one_allowed_collections: 'String',
    junction_field: 'String',
    sort_field: 'String',
    one_deselect_action: 'String',
  },
  directus_users: {
    id: 'ID',
    first_name: 'String',
    last_name: 'String',
    email: 'String',
    password: 'String',
    location: 'String',
    title: 'String',
    description: 'String',
    tags: 'JSON',
    tags_func: 'count_functions',
    avatar: 'directus_files',
    language: 'String',
    theme: 'String',
    tfa_secret: 'String',
    status: 'String',
    role: 'directus_roles',
    token: 'String',
    last_access: 'Date',
    last_access_func: 'datetime_functions',
    last_page: 'String',
    provider: 'String',
    external_identifier: 'String',
    auth_data: 'JSON',
    auth_data_func: 'count_functions',
    email_notifications: 'Boolean',
  },
  count_functions: {
    count: 'Int',
  },
  directus_files: {
    id: 'ID',
    storage: 'String',
    filename_disk: 'String',
    filename_download: 'String',
    title: 'String',
    type: 'String',
    folder: 'directus_folders',
    uploaded_by: 'directus_users',
    uploaded_on: 'Date',
    uploaded_on_func: 'datetime_functions',
    modified_by: 'directus_users',
    modified_on: 'Date',
    modified_on_func: 'datetime_functions',
    charset: 'String',
    filesize: 'String',
    width: 'Int',
    height: 'Int',
    duration: 'Int',
    embed: 'String',
    description: 'String',
    location: 'String',
    tags: 'JSON',
    tags_func: 'count_functions',
    metadata: 'JSON',
    metadata_func: 'count_functions',
  },
  directus_folders: {
    id: 'ID',
    name: 'String',
    parent: 'directus_folders',
  },
  Date: `scalar.Date` as const,
  datetime_functions: {
    year: 'Int',
    month: 'Int',
    week: 'Int',
    day: 'Int',
    weekday: 'Int',
    hour: 'Int',
    minute: 'Int',
    second: 'Int',
  },
  directus_roles: {
    id: 'ID',
    name: 'String',
    icon: 'String',
    description: 'String',
    ip_access: 'String',
    enforce_tfa: 'Boolean',
    admin_access: 'Boolean',
    app_access: 'Boolean',
    users: 'directus_users',
    users_func: 'count_functions',
  },
  directus_roles_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_roles_aggregated_count',
  },
  directus_roles_aggregated_count: {
    id: 'Int',
    name: 'Int',
    icon: 'Int',
    description: 'Int',
    ip_access: 'Int',
    enforce_tfa: 'Int',
    admin_access: 'Int',
    app_access: 'Int',
    users: 'Int',
  },
  directus_files_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_files_aggregated_count',
    avg: 'directus_files_aggregated_fields',
    sum: 'directus_files_aggregated_fields',
    countDistinct: 'directus_files_aggregated_fields',
    avgDistinct: 'directus_files_aggregated_fields',
    sumDistinct: 'directus_files_aggregated_fields',
    min: 'directus_files_aggregated_fields',
    max: 'directus_files_aggregated_fields',
  },
  directus_files_aggregated_count: {
    id: 'Int',
    storage: 'Int',
    filename_disk: 'Int',
    filename_download: 'Int',
    title: 'Int',
    type: 'Int',
    folder: 'Int',
    uploaded_by: 'Int',
    uploaded_on: 'Int',
    modified_by: 'Int',
    modified_on: 'Int',
    charset: 'Int',
    filesize: 'Int',
    width: 'Int',
    height: 'Int',
    duration: 'Int',
    embed: 'Int',
    description: 'Int',
    location: 'Int',
    tags: 'Int',
    metadata: 'Int',
  },
  directus_files_aggregated_fields: {
    width: 'Float',
    height: 'Float',
    duration: 'Float',
  },
  directus_activity: {
    id: 'ID',
    action: 'String',
    user: 'directus_users',
    timestamp: 'Date',
    timestamp_func: 'datetime_functions',
    ip: 'String',
    user_agent: 'String',
    collection: 'String',
    item: 'String',
    comment: 'String',
    revisions: 'directus_revisions',
    revisions_func: 'count_functions',
  },
  directus_revisions: {
    id: 'ID',
    activity: 'directus_activity',
    collection: 'String',
    item: 'String',
    data: 'JSON',
    data_func: 'count_functions',
    delta: 'JSON',
    delta_func: 'count_functions',
    parent: 'directus_revisions',
  },
  directus_activity_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_activity_aggregated_count',
    avg: 'directus_activity_aggregated_fields',
    sum: 'directus_activity_aggregated_fields',
    countDistinct: 'directus_activity_aggregated_fields',
    avgDistinct: 'directus_activity_aggregated_fields',
    sumDistinct: 'directus_activity_aggregated_fields',
    min: 'directus_activity_aggregated_fields',
    max: 'directus_activity_aggregated_fields',
  },
  directus_activity_aggregated_count: {
    id: 'Int',
    action: 'Int',
    user: 'Int',
    timestamp: 'Int',
    ip: 'Int',
    user_agent: 'Int',
    collection: 'Int',
    item: 'Int',
    comment: 'Int',
    revisions: 'Int',
  },
  directus_activity_aggregated_fields: {
    id: 'Float',
  },
  directus_folders_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_folders_aggregated_count',
  },
  directus_folders_aggregated_count: {
    id: 'Int',
    name: 'Int',
    parent: 'Int',
  },
  directus_permissions: {
    id: 'ID',
    role: 'directus_roles',
    collection: 'String',
    action: 'String',
    permissions: 'JSON',
    permissions_func: 'count_functions',
    validation: 'JSON',
    validation_func: 'count_functions',
    presets: 'JSON',
    presets_func: 'count_functions',
    fields: 'String',
  },
  directus_permissions_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_permissions_aggregated_count',
    avg: 'directus_permissions_aggregated_fields',
    sum: 'directus_permissions_aggregated_fields',
    countDistinct: 'directus_permissions_aggregated_fields',
    avgDistinct: 'directus_permissions_aggregated_fields',
    sumDistinct: 'directus_permissions_aggregated_fields',
    min: 'directus_permissions_aggregated_fields',
    max: 'directus_permissions_aggregated_fields',
  },
  directus_permissions_aggregated_count: {
    id: 'Int',
    role: 'Int',
    collection: 'Int',
    action: 'Int',
    permissions: 'Int',
    validation: 'Int',
    presets: 'Int',
    fields: 'Int',
  },
  directus_permissions_aggregated_fields: {
    id: 'Float',
  },
  directus_users_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_users_aggregated_count',
  },
  directus_users_aggregated_count: {
    id: 'Int',
    first_name: 'Int',
    last_name: 'Int',
    email: 'Int',
    password: 'Int',
    location: 'Int',
    title: 'Int',
    description: 'Int',
    tags: 'Int',
    avatar: 'Int',
    language: 'Int',
    theme: 'Int',
    tfa_secret: 'Int',
    status: 'Int',
    role: 'Int',
    token: 'Int',
    last_access: 'Int',
    last_page: 'Int',
    provider: 'Int',
    external_identifier: 'Int',
    auth_data: 'Int',
    email_notifications: 'Int',
  },
  directus_presets: {
    id: 'ID',
    bookmark: 'String',
    user: 'directus_users',
    role: 'directus_roles',
    collection: 'String',
    search: 'String',
    layout: 'String',
    layout_query: 'JSON',
    layout_query_func: 'count_functions',
    layout_options: 'JSON',
    layout_options_func: 'count_functions',
    refresh_interval: 'Int',
    filter: 'JSON',
    filter_func: 'count_functions',
    icon: 'String',
    color: 'String',
  },
  directus_presets_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_presets_aggregated_count',
    avg: 'directus_presets_aggregated_fields',
    sum: 'directus_presets_aggregated_fields',
    countDistinct: 'directus_presets_aggregated_fields',
    avgDistinct: 'directus_presets_aggregated_fields',
    sumDistinct: 'directus_presets_aggregated_fields',
    min: 'directus_presets_aggregated_fields',
    max: 'directus_presets_aggregated_fields',
  },
  directus_presets_aggregated_count: {
    id: 'Int',
    bookmark: 'Int',
    user: 'Int',
    role: 'Int',
    collection: 'Int',
    search: 'Int',
    layout: 'Int',
    layout_query: 'Int',
    layout_options: 'Int',
    refresh_interval: 'Int',
    filter: 'Int',
    icon: 'Int',
    color: 'Int',
  },
  directus_presets_aggregated_fields: {
    id: 'Float',
    refresh_interval: 'Float',
  },
  directus_revisions_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_revisions_aggregated_count',
    avg: 'directus_revisions_aggregated_fields',
    sum: 'directus_revisions_aggregated_fields',
    countDistinct: 'directus_revisions_aggregated_fields',
    avgDistinct: 'directus_revisions_aggregated_fields',
    sumDistinct: 'directus_revisions_aggregated_fields',
    min: 'directus_revisions_aggregated_fields',
    max: 'directus_revisions_aggregated_fields',
  },
  directus_revisions_aggregated_count: {
    id: 'Int',
    activity: 'Int',
    collection: 'Int',
    item: 'Int',
    data: 'Int',
    delta: 'Int',
    parent: 'Int',
  },
  directus_revisions_aggregated_fields: {
    id: 'Float',
    activity: 'Float',
    parent: 'Float',
  },
  directus_webhooks: {
    id: 'ID',
    name: 'String',
    method: 'String',
    url: 'String',
    status: 'String',
    data: 'Boolean',
    actions: 'String',
    collections: 'String',
    headers: 'JSON',
    headers_func: 'count_functions',
  },
  directus_webhooks_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_webhooks_aggregated_count',
    avg: 'directus_webhooks_aggregated_fields',
    sum: 'directus_webhooks_aggregated_fields',
    countDistinct: 'directus_webhooks_aggregated_fields',
    avgDistinct: 'directus_webhooks_aggregated_fields',
    sumDistinct: 'directus_webhooks_aggregated_fields',
    min: 'directus_webhooks_aggregated_fields',
    max: 'directus_webhooks_aggregated_fields',
  },
  directus_webhooks_aggregated_count: {
    id: 'Int',
    name: 'Int',
    method: 'Int',
    url: 'Int',
    status: 'Int',
    data: 'Int',
    actions: 'Int',
    collections: 'Int',
    headers: 'Int',
  },
  directus_webhooks_aggregated_fields: {
    id: 'Float',
  },
  directus_settings: {
    id: 'ID',
    project_name: 'String',
    project_url: 'String',
    project_color: 'String',
    project_logo: 'directus_files',
    public_foreground: 'directus_files',
    public_background: 'directus_files',
    public_note: 'String',
    auth_login_attempts: 'Int',
    auth_password_policy: 'String',
    storage_asset_transform: 'String',
    storage_asset_presets: 'JSON',
    storage_asset_presets_func: 'count_functions',
    custom_css: 'String',
    storage_default_folder: 'directus_folders',
    basemaps: 'JSON',
    basemaps_func: 'count_functions',
    mapbox_key: 'String',
    module_bar: 'JSON',
    module_bar_func: 'count_functions',
    project_descriptor: 'String',
    translation_strings: 'JSON',
    translation_strings_func: 'count_functions',
    default_language: 'String',
  },
  directus_panels: {
    id: 'ID',
    dashboard: 'directus_dashboards',
    name: 'String',
    icon: 'String',
    color: 'String',
    show_header: 'Boolean',
    note: 'String',
    type: 'String',
    position_x: 'Int',
    position_y: 'Int',
    width: 'Int',
    height: 'Int',
    options: 'JSON',
    options_func: 'count_functions',
    date_created: 'Date',
    date_created_func: 'datetime_functions',
    user_created: 'directus_users',
  },
  directus_dashboards: {
    id: 'ID',
    name: 'String',
    icon: 'String',
    note: 'String',
    date_created: 'Date',
    date_created_func: 'datetime_functions',
    user_created: 'directus_users',
    color: 'String',
    panels: 'directus_panels',
    panels_func: 'count_functions',
  },
  directus_panels_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_panels_aggregated_count',
    avg: 'directus_panels_aggregated_fields',
    sum: 'directus_panels_aggregated_fields',
    countDistinct: 'directus_panels_aggregated_fields',
    avgDistinct: 'directus_panels_aggregated_fields',
    sumDistinct: 'directus_panels_aggregated_fields',
    min: 'directus_panels_aggregated_fields',
    max: 'directus_panels_aggregated_fields',
  },
  directus_panels_aggregated_count: {
    id: 'Int',
    dashboard: 'Int',
    name: 'Int',
    icon: 'Int',
    color: 'Int',
    show_header: 'Int',
    note: 'Int',
    type: 'Int',
    position_x: 'Int',
    position_y: 'Int',
    width: 'Int',
    height: 'Int',
    options: 'Int',
    date_created: 'Int',
    user_created: 'Int',
  },
  directus_panels_aggregated_fields: {
    position_x: 'Float',
    position_y: 'Float',
    width: 'Float',
    height: 'Float',
  },
  directus_notifications: {
    id: 'ID',
    timestamp: 'Date',
    timestamp_func: 'datetime_functions',
    status: 'String',
    recipient: 'directus_users',
    sender: 'directus_users',
    subject: 'String',
    message: 'String',
    collection: 'String',
    item: 'String',
  },
  directus_notifications_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_notifications_aggregated_count',
    avg: 'directus_notifications_aggregated_fields',
    sum: 'directus_notifications_aggregated_fields',
    countDistinct: 'directus_notifications_aggregated_fields',
    avgDistinct: 'directus_notifications_aggregated_fields',
    sumDistinct: 'directus_notifications_aggregated_fields',
    min: 'directus_notifications_aggregated_fields',
    max: 'directus_notifications_aggregated_fields',
  },
  directus_notifications_aggregated_count: {
    id: 'Int',
    timestamp: 'Int',
    status: 'Int',
    recipient: 'Int',
    sender: 'Int',
    subject: 'Int',
    message: 'Int',
    collection: 'Int',
    item: 'Int',
  },
  directus_notifications_aggregated_fields: {
    id: 'Float',
  },
  directus_shares: {
    id: 'ID',
    name: 'String',
    collection: 'String',
    item: 'String',
    role: 'directus_roles',
    password: 'String',
    user_created: 'directus_users',
    date_created: 'Date',
    date_created_func: 'datetime_functions',
    date_start: 'Date',
    date_start_func: 'datetime_functions',
    date_end: 'Date',
    date_end_func: 'datetime_functions',
    times_used: 'Int',
    max_uses: 'Int',
  },
  directus_shares_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_shares_aggregated_count',
    avg: 'directus_shares_aggregated_fields',
    sum: 'directus_shares_aggregated_fields',
    countDistinct: 'directus_shares_aggregated_fields',
    avgDistinct: 'directus_shares_aggregated_fields',
    sumDistinct: 'directus_shares_aggregated_fields',
    min: 'directus_shares_aggregated_fields',
    max: 'directus_shares_aggregated_fields',
  },
  directus_shares_aggregated_count: {
    id: 'Int',
    name: 'Int',
    collection: 'Int',
    item: 'Int',
    role: 'Int',
    password: 'Int',
    user_created: 'Int',
    date_created: 'Int',
    date_start: 'Int',
    date_end: 'Int',
    times_used: 'Int',
    max_uses: 'Int',
  },
  directus_shares_aggregated_fields: {
    times_used: 'Float',
    max_uses: 'Float',
  },
  directus_flows: {
    id: 'ID',
    name: 'String',
    icon: 'String',
    color: 'String',
    description: 'String',
    status: 'String',
    trigger: 'String',
    accountability: 'String',
    options: 'JSON',
    options_func: 'count_functions',
    operation: 'directus_operations',
    date_created: 'Date',
    date_created_func: 'datetime_functions',
    user_created: 'directus_users',
    operations: 'directus_operations',
    operations_func: 'count_functions',
  },
  directus_operations: {
    id: 'ID',
    name: 'String',
    key: 'String',
    type: 'String',
    position_x: 'Int',
    position_y: 'Int',
    options: 'JSON',
    options_func: 'count_functions',
    resolve: 'directus_operations',
    reject: 'directus_operations',
    flow: 'directus_flows',
    date_created: 'Date',
    date_created_func: 'datetime_functions',
    user_created: 'directus_users',
  },
  directus_flows_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_flows_aggregated_count',
  },
  directus_flows_aggregated_count: {
    id: 'Int',
    name: 'Int',
    icon: 'Int',
    color: 'Int',
    description: 'Int',
    status: 'Int',
    trigger: 'Int',
    accountability: 'Int',
    options: 'Int',
    operation: 'Int',
    date_created: 'Int',
    user_created: 'Int',
    operations: 'Int',
  },
  directus_operations_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_operations_aggregated_count',
    avg: 'directus_operations_aggregated_fields',
    sum: 'directus_operations_aggregated_fields',
    countDistinct: 'directus_operations_aggregated_fields',
    avgDistinct: 'directus_operations_aggregated_fields',
    sumDistinct: 'directus_operations_aggregated_fields',
    min: 'directus_operations_aggregated_fields',
    max: 'directus_operations_aggregated_fields',
  },
  directus_operations_aggregated_count: {
    id: 'Int',
    name: 'Int',
    key: 'Int',
    type: 'Int',
    position_x: 'Int',
    position_y: 'Int',
    options: 'Int',
    resolve: 'Int',
    reject: 'Int',
    flow: 'Int',
    date_created: 'Int',
    user_created: 'Int',
  },
  directus_operations_aggregated_fields: {
    position_x: 'Float',
    position_y: 'Float',
  },
  directus_dashboards_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'directus_dashboards_aggregated_count',
  },
  directus_dashboards_aggregated_count: {
    id: 'Int',
    name: 'Int',
    icon: 'Int',
    note: 'Int',
    date_created: 'Int',
    user_created: 'Int',
    color: 'Int',
    panels: 'Int',
  },
  Mutation: {
    auth_login: 'auth_tokens',
    auth_refresh: 'auth_tokens',
    auth_logout: 'Boolean',
    auth_password_request: 'Boolean',
    auth_password_reset: 'Boolean',
    users_me_tfa_generate: 'users_me_tfa_generate_data',
    users_me_tfa_enable: 'Boolean',
    users_me_tfa_disable: 'Boolean',
    utils_hash_generate: 'String',
    utils_hash_verify: 'Boolean',
    utils_sort: 'Boolean',
    utils_revert: 'Boolean',
    utils_cache_clear: 'Void',
    users_invite_accept: 'Boolean',
    create_collections_item: 'directus_collections',
    update_collections_item: 'directus_collections',
    delete_collections_item: 'delete_collection',
    create_fields_item: 'directus_fields',
    update_fields_item: 'directus_fields',
    delete_fields_item: 'delete_field',
    create_relations_item: 'directus_relations',
    update_relations_item: 'directus_relations',
    delete_relations_item: 'delete_relation',
    update_users_me: 'directus_users',
    create_comment: 'directus_activity',
    update_comment: 'directus_activity',
    delete_comment: 'delete_one',
    import_file: 'directus_files',
    users_invite: 'Boolean',
    create_roles_items: 'directus_roles',
    create_roles_item: 'directus_roles',
    create_files_items: 'directus_files',
    create_files_item: 'directus_files',
    create_folders_items: 'directus_folders',
    create_folders_item: 'directus_folders',
    create_permissions_items: 'directus_permissions',
    create_permissions_item: 'directus_permissions',
    create_users_items: 'directus_users',
    create_users_item: 'directus_users',
    create_presets_items: 'directus_presets',
    create_presets_item: 'directus_presets',
    create_webhooks_items: 'directus_webhooks',
    create_webhooks_item: 'directus_webhooks',
    create_panels_items: 'directus_panels',
    create_panels_item: 'directus_panels',
    create_notifications_items: 'directus_notifications',
    create_notifications_item: 'directus_notifications',
    create_shares_items: 'directus_shares',
    create_shares_item: 'directus_shares',
    create_flows_items: 'directus_flows',
    create_flows_item: 'directus_flows',
    create_operations_items: 'directus_operations',
    create_operations_item: 'directus_operations',
    create_dashboards_items: 'directus_dashboards',
    create_dashboards_item: 'directus_dashboards',
    update_roles_items: 'directus_roles',
    update_roles_item: 'directus_roles',
    update_files_items: 'directus_files',
    update_files_item: 'directus_files',
    update_folders_items: 'directus_folders',
    update_folders_item: 'directus_folders',
    update_permissions_items: 'directus_permissions',
    update_permissions_item: 'directus_permissions',
    update_users_items: 'directus_users',
    update_users_item: 'directus_users',
    update_presets_items: 'directus_presets',
    update_presets_item: 'directus_presets',
    update_webhooks_items: 'directus_webhooks',
    update_webhooks_item: 'directus_webhooks',
    update_settings: 'directus_settings',
    update_panels_items: 'directus_panels',
    update_panels_item: 'directus_panels',
    update_notifications_items: 'directus_notifications',
    update_notifications_item: 'directus_notifications',
    update_shares_items: 'directus_shares',
    update_shares_item: 'directus_shares',
    update_flows_items: 'directus_flows',
    update_flows_item: 'directus_flows',
    update_operations_items: 'directus_operations',
    update_operations_item: 'directus_operations',
    update_dashboards_items: 'directus_dashboards',
    update_dashboards_item: 'directus_dashboards',
    delete_roles_items: 'delete_many',
    delete_roles_item: 'delete_one',
    delete_files_items: 'delete_many',
    delete_files_item: 'delete_one',
    delete_folders_items: 'delete_many',
    delete_folders_item: 'delete_one',
    delete_permissions_items: 'delete_many',
    delete_permissions_item: 'delete_one',
    delete_users_items: 'delete_many',
    delete_users_item: 'delete_one',
    delete_presets_items: 'delete_many',
    delete_presets_item: 'delete_one',
    delete_webhooks_items: 'delete_many',
    delete_webhooks_item: 'delete_one',
    delete_panels_items: 'delete_many',
    delete_panels_item: 'delete_one',
    delete_notifications_items: 'delete_many',
    delete_notifications_item: 'delete_one',
    delete_shares_items: 'delete_many',
    delete_shares_item: 'delete_one',
    delete_flows_items: 'delete_many',
    delete_flows_item: 'delete_one',
    delete_operations_items: 'delete_many',
    delete_operations_item: 'delete_one',
    delete_dashboards_items: 'delete_many',
    delete_dashboards_item: 'delete_one',
  },
  auth_tokens: {
    access_token: 'String',
    expires: 'Int',
    refresh_token: 'String',
  },
  users_me_tfa_generate_data: {
    secret: 'String',
    otpauth_url: 'String',
  },
  Void: `scalar.Void` as const,
  delete_collection: {
    collection: 'String',
  },
  delete_field: {
    collection: 'String',
    field: 'String',
  },
  delete_relation: {
    collection: 'String',
    field: 'String',
  },
  delete_one: {
    id: 'ID',
  },
  delete_many: {
    ids: 'ID',
  },
};

export const Ops = {
  query: 'Query' as const,
  mutation: 'Mutation' as const,
};
