/* eslint-disable */

export const AllTypesProps: Record<string, any> = {
  Query: {
    brands: {
      filter: 'brands_filter',
    },
    brands_by_id: {},
    brands_aggregated: {
      filter: 'brands_filter',
    },
    brands_users: {
      filter: 'brands_users_filter',
    },
    brands_users_by_id: {},
    brands_users_aggregated: {
      filter: 'brands_users_filter',
    },
    users: {
      filter: 'users_filter',
    },
    users_by_id: {},
    users_aggregated: {
      filter: 'users_filter',
    },
    producers: {
      filter: 'producers_filter',
    },
    producers_by_id: {},
    producers_aggregated: {
      filter: 'producers_filter',
    },
    producers_production_materials: {
      filter: 'producers_production_materials_filter',
    },
    producers_production_materials_by_id: {},
    producers_production_materials_aggregated: {
      filter: 'producers_production_materials_filter',
    },
    production_materials: {
      filter: 'production_materials_filter',
    },
    production_materials_by_id: {},
    production_materials_aggregated: {
      filter: 'production_materials_filter',
    },
    producers_production_methods: {
      filter: 'producers_production_methods_filter',
    },
    producers_production_methods_by_id: {},
    producers_production_methods_aggregated: {
      filter: 'producers_production_methods_filter',
    },
    production_methods: {
      filter: 'production_methods_filter',
    },
    production_methods_by_id: {},
    production_methods_aggregated: {
      filter: 'production_methods_filter',
    },
    product_collaborators: {
      filter: 'product_collaborators_filter',
    },
    product_collaborators_by_id: {},
    product_collaborators_aggregated: {
      filter: 'product_collaborators_filter',
    },
    collaborator_roles: {
      filter: 'collaborator_roles_filter',
    },
    collaborator_roles_by_id: {},
    collaborator_roles_aggregated: {
      filter: 'collaborator_roles_filter',
    },
    production_materials_production_methods: {
      filter: 'production_materials_production_methods_filter',
    },
    production_materials_production_methods_by_id: {},
    production_materials_production_methods_aggregated: {
      filter: 'production_materials_production_methods_filter',
    },
    fulfillers: {
      filter: 'fulfillers_filter',
    },
    fulfillers_by_id: {},
    fulfillers_aggregated: {
      filter: 'fulfillers_filter',
    },
    price_currencies: {
      filter: 'price_currencies_filter',
    },
    price_currencies_by_id: {},
    price_currencies_aggregated: {
      filter: 'price_currencies_filter',
    },
    stage: {
      filter: 'stage_filter',
    },
    stage_by_id: {},
    stage_aggregated: {
      filter: 'stage_filter',
    },
    products_files: {
      filter: 'products_files_filter',
    },
    products_files_by_id: {},
    products_files_aggregated: {
      filter: 'products_files_filter',
    },
    products_production_methods: {
      filter: 'products_production_methods_filter',
    },
    products_production_methods_by_id: {},
    products_production_methods_aggregated: {
      filter: 'products_production_methods_filter',
    },
    skills: {
      filter: 'skills_filter',
    },
    skills_by_id: {},
    skills_aggregated: {
      filter: 'skills_filter',
    },
    users_skills: {
      filter: 'users_skills_filter',
    },
    users_skills_by_id: {},
    users_skills_aggregated: {
      filter: 'users_skills_filter',
    },
    products: {
      filter: 'products_filter',
    },
    products_by_id: {},
    products_aggregated: {
      filter: 'products_filter',
    },
    products_production_materials: {
      filter: 'products_production_materials_filter',
    },
    products_production_materials_by_id: {},
    products_production_materials_aggregated: {
      filter: 'products_production_materials_filter',
    },
    products_wearables: {
      filter: 'products_wearables_filter',
    },
    products_wearables_by_id: {},
    products_wearables_aggregated: {
      filter: 'products_wearables_filter',
    },
    file_formats: {
      filter: 'file_formats_filter',
    },
    file_formats_by_id: {},
    file_formats_aggregated: {
      filter: 'file_formats_filter',
    },
    products_design_files: {
      filter: 'products_design_files_filter',
    },
    products_design_files_by_id: {},
    products_design_files_aggregated: {
      filter: 'products_design_files_filter',
    },
    products_content: {
      filter: 'products_content_filter',
    },
    products_content_by_id: {},
    products_content_aggregated: {
      filter: 'products_content_filter',
    },
    stages: {
      filter: 'stages_filter',
    },
    stages_by_id: {},
    stages_aggregated: {
      filter: 'stages_filter',
    },
  },
  brands: {
    logo: {
      filter: 'directus_files_filter',
    },
    products: {
      filter: 'products_filter',
    },
    members: {
      filter: 'brands_users_filter',
    },
  },
  Date: `scalar.Date` as const,
  directus_files: {
    folder: {
      filter: 'directus_folders_filter',
    },
    uploaded_by: {
      filter: 'directus_users_filter',
    },
    modified_by: {
      filter: 'directus_users_filter',
    },
  },
  directus_folders: {
    parent: {
      filter: 'directus_folders_filter',
    },
  },
  directus_folders_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    parent: 'directus_folders_filter',
    _and: 'directus_folders_filter',
    _or: 'directus_folders_filter',
  },
  string_filter_operators: {},
  directus_users: {
    avatar: {
      filter: 'directus_files_filter',
    },
    role: {
      filter: 'directus_roles_filter',
    },
  },
  JSON: `scalar.JSON` as const,
  directus_files_filter: {
    id: 'string_filter_operators',
    storage: 'string_filter_operators',
    filename_disk: 'string_filter_operators',
    filename_download: 'string_filter_operators',
    title: 'string_filter_operators',
    type: 'string_filter_operators',
    folder: 'directus_folders_filter',
    uploaded_by: 'directus_users_filter',
    uploaded_on: 'date_filter_operators',
    uploaded_on_func: 'datetime_function_filter_operators',
    modified_by: 'directus_users_filter',
    modified_on: 'date_filter_operators',
    modified_on_func: 'datetime_function_filter_operators',
    charset: 'string_filter_operators',
    filesize: 'string_filter_operators',
    width: 'number_filter_operators',
    height: 'number_filter_operators',
    duration: 'number_filter_operators',
    embed: 'string_filter_operators',
    description: 'string_filter_operators',
    location: 'string_filter_operators',
    tags: 'string_filter_operators',
    tags_func: 'count_function_filter_operators',
    metadata: 'string_filter_operators',
    metadata_func: 'count_function_filter_operators',
    _and: 'directus_files_filter',
    _or: 'directus_files_filter',
  },
  directus_users_filter: {
    id: 'string_filter_operators',
    first_name: 'string_filter_operators',
    last_name: 'string_filter_operators',
    email: 'string_filter_operators',
    password: 'string_filter_operators',
    location: 'string_filter_operators',
    title: 'string_filter_operators',
    description: 'string_filter_operators',
    tags: 'string_filter_operators',
    tags_func: 'count_function_filter_operators',
    avatar: 'directus_files_filter',
    language: 'string_filter_operators',
    theme: 'string_filter_operators',
    tfa_secret: 'string_filter_operators',
    status: 'string_filter_operators',
    role: 'directus_roles_filter',
    token: 'string_filter_operators',
    last_access: 'date_filter_operators',
    last_access_func: 'datetime_function_filter_operators',
    last_page: 'string_filter_operators',
    provider: 'string_filter_operators',
    external_identifier: 'string_filter_operators',
    auth_data: 'string_filter_operators',
    auth_data_func: 'count_function_filter_operators',
    email_notifications: 'boolean_filter_operators',
    _and: 'directus_users_filter',
    _or: 'directus_users_filter',
  },
  count_function_filter_operators: {
    count: 'number_filter_operators',
  },
  number_filter_operators: {},
  directus_roles_filter: {
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    icon: 'string_filter_operators',
    description: 'string_filter_operators',
    ip_access: 'string_filter_operators',
    enforce_tfa: 'boolean_filter_operators',
    admin_access: 'boolean_filter_operators',
    app_access: 'boolean_filter_operators',
    users: 'directus_users_filter',
    users_func: 'count_function_filter_operators',
    _and: 'directus_roles_filter',
    _or: 'directus_roles_filter',
  },
  boolean_filter_operators: {},
  date_filter_operators: {},
  datetime_function_filter_operators: {
    year: 'number_filter_operators',
    month: 'number_filter_operators',
    week: 'number_filter_operators',
    day: 'number_filter_operators',
    weekday: 'number_filter_operators',
    hour: 'number_filter_operators',
    minute: 'number_filter_operators',
    second: 'number_filter_operators',
  },
  directus_roles: {
    users: {
      filter: 'directus_users_filter',
    },
  },
  products: {
    brand_id: {
      filter: 'brands_filter',
    },
    fulfiller_id: {
      filter: 'fulfillers_filter',
    },
    price: {
      filter: 'price_currencies_filter',
    },
    producer_id: {
      filter: 'producers_filter',
    },
    clo3d_file: {
      filter: 'directus_files_filter',
    },
    product_stage: {
      filter: 'stages_filter',
    },
    collaborators: {
      filter: 'product_collaborators_filter',
    },
    production_methods: {
      filter: 'products_production_methods_filter',
    },
    images: {
      filter: 'products_files_filter',
    },
    materials: {
      filter: 'products_production_materials_filter',
    },
    wearable_files: {
      filter: 'products_wearables_filter',
    },
    content: {
      filter: 'products_content_filter',
    },
    design_files: {
      filter: 'products_design_files_filter',
    },
  },
  brands_filter: {
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    description: 'string_filter_operators',
    discord_url: 'string_filter_operators',
    eth_address: 'string_filter_operators',
    id: 'string_filter_operators',
    logo: 'directus_files_filter',
    name: 'string_filter_operators',
    twitter_url: 'string_filter_operators',
    website_url: 'string_filter_operators',
    notion_id: 'string_filter_operators',
    products: 'products_filter',
    products_func: 'count_function_filter_operators',
    members: 'brands_users_filter',
    members_func: 'count_function_filter_operators',
    _and: 'brands_filter',
    _or: 'brands_filter',
  },
  products_filter: {
    brand_id: 'brands_filter',
    brand_reward_share: 'number_filter_operators',
    collaborator_reward_share: 'number_filter_operators',
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    description: 'string_filter_operators',
    discord_channel_id: 'string_filter_operators',
    fulfiller_id: 'fulfillers_filter',
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    notion_id: 'string_filter_operators',
    price: 'price_currencies_filter',
    producer_id: 'producers_filter',
    production_cost: 'number_filter_operators',
    quantity: 'string_filter_operators',
    sale_type: 'string_filter_operators',
    shopify_id: 'string_filter_operators',
    status: 'string_filter_operators',
    season: 'number_filter_operators',
    release_date: 'date_filter_operators',
    release_date_func: 'datetime_function_filter_operators',
    clo3d_file: 'directus_files_filter',
    product_stage: 'stages_filter',
    collaborators: 'product_collaborators_filter',
    collaborators_func: 'count_function_filter_operators',
    production_methods: 'products_production_methods_filter',
    production_methods_func: 'count_function_filter_operators',
    images: 'products_files_filter',
    images_func: 'count_function_filter_operators',
    materials: 'products_production_materials_filter',
    materials_func: 'count_function_filter_operators',
    wearable_files: 'products_wearables_filter',
    wearable_files_func: 'count_function_filter_operators',
    content: 'products_content_filter',
    content_func: 'count_function_filter_operators',
    design_files: 'products_design_files_filter',
    design_files_func: 'count_function_filter_operators',
    _and: 'products_filter',
    _or: 'products_filter',
  },
  fulfillers_filter: {
    address: 'string_filter_operators',
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    email: 'string_filter_operators',
    eth_address: 'string_filter_operators',
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    website_url: 'string_filter_operators',
    _and: 'fulfillers_filter',
    _or: 'fulfillers_filter',
  },
  price_currencies_filter: {
    amount: 'number_filter_operators',
    currency: 'string_filter_operators',
    id: 'string_filter_operators',
    _and: 'price_currencies_filter',
    _or: 'price_currencies_filter',
  },
  producers_filter: {
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    email: 'string_filter_operators',
    eth_address: 'string_filter_operators',
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    shipping_address: 'string_filter_operators',
    production_materials_stocked: 'producers_production_materials_filter',
    production_materials_stocked_func: 'count_function_filter_operators',
    production_methods: 'producers_production_methods_filter',
    production_methods_func: 'count_function_filter_operators',
    supplied_materials: 'production_materials_filter',
    supplied_materials_func: 'count_function_filter_operators',
    _and: 'producers_filter',
    _or: 'producers_filter',
  },
  producers_production_materials_filter: {
    id: 'number_filter_operators',
    producers_id: 'producers_filter',
    production_materials_id: 'production_materials_filter',
    quantity: 'number_filter_operators',
    _and: 'producers_production_materials_filter',
    _or: 'producers_production_materials_filter',
  },
  production_materials_filter: {
    base_price: 'number_filter_operators',
    color_palette: 'string_filter_operators',
    color_palette_func: 'count_function_filter_operators',
    composition: 'string_filter_operators',
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    created_by: 'directus_users_filter',
    description: 'string_filter_operators',
    gender: 'string_filter_operators',
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    neck_tag: 'boolean_filter_operators',
    rating: 'string_filter_operators',
    size_guide: 'directus_files_filter',
    supplier: 'producers_filter',
    tags: 'string_filter_operators',
    tags_func: 'count_function_filter_operators',
    production_methods: 'production_materials_production_methods_filter',
    production_methods_func: 'count_function_filter_operators',
    stocked_at: 'producers_production_materials_filter',
    stocked_at_func: 'count_function_filter_operators',
    _and: 'production_materials_filter',
    _or: 'production_materials_filter',
  },
  production_materials_production_methods_filter: {
    id: 'number_filter_operators',
    production_materials_id: 'production_materials_filter',
    production_methods_id: 'production_methods_filter',
    _and: 'production_materials_production_methods_filter',
    _or: 'production_materials_production_methods_filter',
  },
  production_methods_filter: {
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    description: 'string_filter_operators',
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    producers: 'producers_production_methods_filter',
    producers_func: 'count_function_filter_operators',
    production_materials: 'production_materials_production_methods_filter',
    production_materials_func: 'count_function_filter_operators',
    _and: 'production_methods_filter',
    _or: 'production_methods_filter',
  },
  producers_production_methods_filter: {
    id: 'number_filter_operators',
    producers_id: 'producers_filter',
    production_methods_id: 'production_methods_filter',
    _and: 'producers_production_methods_filter',
    _or: 'producers_production_methods_filter',
  },
  stages_filter: {
    name: 'string_filter_operators',
    sort: 'number_filter_operators',
    description: 'string_filter_operators',
    _and: 'stages_filter',
    _or: 'stages_filter',
  },
  product_collaborators_filter: {
    collaboration_share: 'number_filter_operators',
    collaborator_id: 'users_filter',
    id: 'string_filter_operators',
    product_id: 'products_filter',
    role: 'collaborator_roles_filter',
    _and: 'product_collaborators_filter',
    _or: 'product_collaborators_filter',
  },
  users_filter: {
    created_at: 'date_filter_operators',
    created_at_func: 'datetime_function_filter_operators',
    discord_handle: 'string_filter_operators',
    discord_id: 'string_filter_operators',
    eth_address: 'string_filter_operators',
    github_handle: 'string_filter_operators',
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    timezone: 'string_filter_operators',
    twitter_handle: 'string_filter_operators',
    brands: 'brands_users_filter',
    brands_func: 'count_function_filter_operators',
    products: 'product_collaborators_filter',
    products_func: 'count_function_filter_operators',
    skills: 'users_skills_filter',
    skills_func: 'count_function_filter_operators',
    _and: 'users_filter',
    _or: 'users_filter',
  },
  brands_users_filter: {
    brands_id: 'brands_filter',
    id: 'number_filter_operators',
    users_id: 'users_filter',
    _and: 'brands_users_filter',
    _or: 'brands_users_filter',
  },
  users_skills_filter: {
    id: 'number_filter_operators',
    skills_id: 'skills_filter',
    users_id: 'users_filter',
    _and: 'users_skills_filter',
    _or: 'users_skills_filter',
  },
  skills_filter: {
    description: 'string_filter_operators',
    id: 'string_filter_operators',
    name: 'string_filter_operators',
    users: 'users_skills_filter',
    users_func: 'count_function_filter_operators',
    _and: 'skills_filter',
    _or: 'skills_filter',
  },
  collaborator_roles_filter: {
    description: 'string_filter_operators',
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    _and: 'collaborator_roles_filter',
    _or: 'collaborator_roles_filter',
  },
  products_production_methods_filter: {
    id: 'number_filter_operators',
    production_methods_id: 'production_methods_filter',
    products_id: 'products_filter',
    _and: 'products_production_methods_filter',
    _or: 'products_production_methods_filter',
  },
  products_files_filter: {
    directus_files_id: 'directus_files_filter',
    id: 'number_filter_operators',
    products_id: 'products_filter',
    _and: 'products_files_filter',
    _or: 'products_files_filter',
  },
  products_production_materials_filter: {
    id: 'number_filter_operators',
    products_id: 'products_filter',
    production_materials_id: 'production_materials_filter',
    _and: 'products_production_materials_filter',
    _or: 'products_production_materials_filter',
  },
  products_wearables_filter: {
    id: 'number_filter_operators',
    products_id: 'products_filter',
    directus_files_id: 'directus_files_filter',
    file_format: 'file_formats_filter',
    _and: 'products_wearables_filter',
    _or: 'products_wearables_filter',
  },
  file_formats_filter: {
    id: 'number_filter_operators',
    mime_type: 'string_filter_operators',
    extension: 'string_filter_operators',
    description: 'string_filter_operators',
    name: 'string_filter_operators',
    _and: 'file_formats_filter',
    _or: 'file_formats_filter',
  },
  products_content_filter: {
    id: 'number_filter_operators',
    products_id: 'products_filter',
    directus_files_id: 'directus_files_filter',
    _and: 'products_content_filter',
    _or: 'products_content_filter',
  },
  products_design_files_filter: {
    id: 'number_filter_operators',
    products_id: 'products_filter',
    directus_files_id: 'directus_files_filter',
    _and: 'products_design_files_filter',
    _or: 'products_design_files_filter',
  },
  producers: {
    production_materials_stocked: {
      filter: 'producers_production_materials_filter',
    },
    production_methods: {
      filter: 'producers_production_methods_filter',
    },
    supplied_materials: {
      filter: 'production_materials_filter',
    },
  },
  producers_production_materials: {
    producers_id: {
      filter: 'producers_filter',
    },
    production_materials_id: {
      filter: 'production_materials_filter',
    },
  },
  production_materials: {
    created_by: {
      filter: 'directus_users_filter',
    },
    size_guide: {
      filter: 'directus_files_filter',
    },
    supplier: {
      filter: 'producers_filter',
    },
    production_methods: {
      filter: 'production_materials_production_methods_filter',
    },
    stocked_at: {
      filter: 'producers_production_materials_filter',
    },
  },
  production_materials_production_methods: {
    production_materials_id: {
      filter: 'production_materials_filter',
    },
    production_methods_id: {
      filter: 'production_methods_filter',
    },
  },
  production_methods: {
    producers: {
      filter: 'producers_production_methods_filter',
    },
    production_materials: {
      filter: 'production_materials_production_methods_filter',
    },
  },
  producers_production_methods: {
    producers_id: {
      filter: 'producers_filter',
    },
    production_methods_id: {
      filter: 'production_methods_filter',
    },
  },
  product_collaborators: {
    collaborator_id: {
      filter: 'users_filter',
    },
    product_id: {
      filter: 'products_filter',
    },
    role: {
      filter: 'collaborator_roles_filter',
    },
  },
  users: {
    brands: {
      filter: 'brands_users_filter',
    },
    products: {
      filter: 'product_collaborators_filter',
    },
    skills: {
      filter: 'users_skills_filter',
    },
  },
  brands_users: {
    brands_id: {
      filter: 'brands_filter',
    },
    users_id: {
      filter: 'users_filter',
    },
  },
  users_skills: {
    skills_id: {
      filter: 'skills_filter',
    },
    users_id: {
      filter: 'users_filter',
    },
  },
  skills: {
    users: {
      filter: 'users_skills_filter',
    },
  },
  products_production_methods: {
    production_methods_id: {
      filter: 'production_methods_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  products_files: {
    directus_files_id: {
      filter: 'directus_files_filter',
    },
    products_id: {
      filter: 'products_filter',
    },
  },
  products_production_materials: {
    products_id: {
      filter: 'products_filter',
    },
    production_materials_id: {
      filter: 'production_materials_filter',
    },
  },
  products_wearables: {
    products_id: {
      filter: 'products_filter',
    },
    directus_files_id: {
      filter: 'directus_files_filter',
    },
    file_format: {
      filter: 'file_formats_filter',
    },
  },
  products_content: {
    products_id: {
      filter: 'products_filter',
    },
    directus_files_id: {
      filter: 'directus_files_filter',
    },
  },
  products_design_files: {
    products_id: {
      filter: 'products_filter',
    },
    directus_files_id: {
      filter: 'directus_files_filter',
    },
  },
  stage_filter: {
    description: 'string_filter_operators',
    id: 'number_filter_operators',
    name: 'string_filter_operators',
    sort: 'number_filter_operators',
    _and: 'stage_filter',
    _or: 'stage_filter',
  },
  Mutation: {
    create_brands_items: {
      filter: 'brands_filter',
      data: 'create_brands_input',
    },
    create_brands_item: {
      data: 'create_brands_input',
    },
    create_brands_users_items: {
      filter: 'brands_users_filter',
      data: 'create_brands_users_input',
    },
    create_brands_users_item: {
      data: 'create_brands_users_input',
    },
    create_users_items: {
      filter: 'users_filter',
      data: 'create_users_input',
    },
    create_users_item: {
      data: 'create_users_input',
    },
    create_producers_items: {
      filter: 'producers_filter',
      data: 'create_producers_input',
    },
    create_producers_item: {
      data: 'create_producers_input',
    },
    create_producers_production_materials_items: {
      filter: 'producers_production_materials_filter',
      data: 'create_producers_production_materials_input',
    },
    create_producers_production_materials_item: {
      data: 'create_producers_production_materials_input',
    },
    create_production_materials_items: {
      filter: 'production_materials_filter',
      data: 'create_production_materials_input',
    },
    create_production_materials_item: {
      data: 'create_production_materials_input',
    },
    create_producers_production_methods_items: {
      filter: 'producers_production_methods_filter',
      data: 'create_producers_production_methods_input',
    },
    create_producers_production_methods_item: {
      data: 'create_producers_production_methods_input',
    },
    create_production_methods_items: {
      filter: 'production_methods_filter',
      data: 'create_production_methods_input',
    },
    create_production_methods_item: {
      data: 'create_production_methods_input',
    },
    create_product_collaborators_items: {
      filter: 'product_collaborators_filter',
      data: 'create_product_collaborators_input',
    },
    create_product_collaborators_item: {
      data: 'create_product_collaborators_input',
    },
    create_collaborator_roles_items: {
      filter: 'collaborator_roles_filter',
      data: 'create_collaborator_roles_input',
    },
    create_collaborator_roles_item: {
      data: 'create_collaborator_roles_input',
    },
    create_production_materials_production_methods_items: {
      filter: 'production_materials_production_methods_filter',
      data: 'create_production_materials_production_methods_input',
    },
    create_production_materials_production_methods_item: {
      data: 'create_production_materials_production_methods_input',
    },
    create_fulfillers_items: {
      filter: 'fulfillers_filter',
      data: 'create_fulfillers_input',
    },
    create_fulfillers_item: {
      data: 'create_fulfillers_input',
    },
    create_price_currencies_items: {
      filter: 'price_currencies_filter',
      data: 'create_price_currencies_input',
    },
    create_price_currencies_item: {
      data: 'create_price_currencies_input',
    },
    create_stage_items: {
      filter: 'stage_filter',
      data: 'create_stage_input',
    },
    create_stage_item: {
      data: 'create_stage_input',
    },
    create_products_files_items: {
      filter: 'products_files_filter',
      data: 'create_products_files_input',
    },
    create_products_files_item: {
      data: 'create_products_files_input',
    },
    create_products_production_methods_items: {
      filter: 'products_production_methods_filter',
      data: 'create_products_production_methods_input',
    },
    create_products_production_methods_item: {
      data: 'create_products_production_methods_input',
    },
    create_skills_items: {
      filter: 'skills_filter',
      data: 'create_skills_input',
    },
    create_skills_item: {
      data: 'create_skills_input',
    },
    create_users_skills_items: {
      filter: 'users_skills_filter',
      data: 'create_users_skills_input',
    },
    create_users_skills_item: {
      data: 'create_users_skills_input',
    },
    create_products_items: {
      filter: 'products_filter',
      data: 'create_products_input',
    },
    create_products_item: {
      data: 'create_products_input',
    },
    create_products_production_materials_items: {
      filter: 'products_production_materials_filter',
      data: 'create_products_production_materials_input',
    },
    create_products_production_materials_item: {
      data: 'create_products_production_materials_input',
    },
    create_products_wearables_items: {
      filter: 'products_wearables_filter',
      data: 'create_products_wearables_input',
    },
    create_products_wearables_item: {
      data: 'create_products_wearables_input',
    },
    create_file_formats_items: {
      filter: 'file_formats_filter',
      data: 'create_file_formats_input',
    },
    create_file_formats_item: {
      data: 'create_file_formats_input',
    },
    create_products_design_files_items: {
      filter: 'products_design_files_filter',
      data: 'create_products_design_files_input',
    },
    create_products_design_files_item: {
      data: 'create_products_design_files_input',
    },
    create_products_content_items: {
      filter: 'products_content_filter',
      data: 'create_products_content_input',
    },
    create_products_content_item: {
      data: 'create_products_content_input',
    },
    create_stages_items: {
      filter: 'stages_filter',
      data: 'create_stages_input',
    },
    create_stages_item: {
      data: 'create_stages_input',
    },
    update_brands_items: {
      filter: 'brands_filter',
      data: 'update_brands_input',
    },
    update_brands_item: {
      data: 'update_brands_input',
    },
    update_brands_users_items: {
      filter: 'brands_users_filter',
      data: 'update_brands_users_input',
    },
    update_brands_users_item: {
      data: 'update_brands_users_input',
    },
    update_users_items: {
      filter: 'users_filter',
      data: 'update_users_input',
    },
    update_users_item: {
      data: 'update_users_input',
    },
    update_producers_items: {
      filter: 'producers_filter',
      data: 'update_producers_input',
    },
    update_producers_item: {
      data: 'update_producers_input',
    },
    update_producers_production_materials_items: {
      filter: 'producers_production_materials_filter',
      data: 'update_producers_production_materials_input',
    },
    update_producers_production_materials_item: {
      data: 'update_producers_production_materials_input',
    },
    update_production_materials_items: {
      filter: 'production_materials_filter',
      data: 'update_production_materials_input',
    },
    update_production_materials_item: {
      data: 'update_production_materials_input',
    },
    update_producers_production_methods_items: {
      filter: 'producers_production_methods_filter',
      data: 'update_producers_production_methods_input',
    },
    update_producers_production_methods_item: {
      data: 'update_producers_production_methods_input',
    },
    update_production_methods_items: {
      filter: 'production_methods_filter',
      data: 'update_production_methods_input',
    },
    update_production_methods_item: {
      data: 'update_production_methods_input',
    },
    update_product_collaborators_items: {
      filter: 'product_collaborators_filter',
      data: 'update_product_collaborators_input',
    },
    update_product_collaborators_item: {
      data: 'update_product_collaborators_input',
    },
    update_collaborator_roles_items: {
      filter: 'collaborator_roles_filter',
      data: 'update_collaborator_roles_input',
    },
    update_collaborator_roles_item: {
      data: 'update_collaborator_roles_input',
    },
    update_production_materials_production_methods_items: {
      filter: 'production_materials_production_methods_filter',
      data: 'update_production_materials_production_methods_input',
    },
    update_production_materials_production_methods_item: {
      data: 'update_production_materials_production_methods_input',
    },
    update_fulfillers_items: {
      filter: 'fulfillers_filter',
      data: 'update_fulfillers_input',
    },
    update_fulfillers_item: {
      data: 'update_fulfillers_input',
    },
    update_price_currencies_items: {
      filter: 'price_currencies_filter',
      data: 'update_price_currencies_input',
    },
    update_price_currencies_item: {
      data: 'update_price_currencies_input',
    },
    update_stage_items: {
      filter: 'stage_filter',
      data: 'update_stage_input',
    },
    update_stage_item: {
      data: 'update_stage_input',
    },
    update_products_files_items: {
      filter: 'products_files_filter',
      data: 'update_products_files_input',
    },
    update_products_files_item: {
      data: 'update_products_files_input',
    },
    update_products_production_methods_items: {
      filter: 'products_production_methods_filter',
      data: 'update_products_production_methods_input',
    },
    update_products_production_methods_item: {
      data: 'update_products_production_methods_input',
    },
    update_skills_items: {
      filter: 'skills_filter',
      data: 'update_skills_input',
    },
    update_skills_item: {
      data: 'update_skills_input',
    },
    update_users_skills_items: {
      filter: 'users_skills_filter',
      data: 'update_users_skills_input',
    },
    update_users_skills_item: {
      data: 'update_users_skills_input',
    },
    update_products_items: {
      filter: 'products_filter',
      data: 'update_products_input',
    },
    update_products_item: {
      data: 'update_products_input',
    },
    update_products_production_materials_items: {
      filter: 'products_production_materials_filter',
      data: 'update_products_production_materials_input',
    },
    update_products_production_materials_item: {
      data: 'update_products_production_materials_input',
    },
    update_products_wearables_items: {
      filter: 'products_wearables_filter',
      data: 'update_products_wearables_input',
    },
    update_products_wearables_item: {
      data: 'update_products_wearables_input',
    },
    update_file_formats_items: {
      filter: 'file_formats_filter',
      data: 'update_file_formats_input',
    },
    update_file_formats_item: {
      data: 'update_file_formats_input',
    },
    update_products_design_files_items: {
      filter: 'products_design_files_filter',
      data: 'update_products_design_files_input',
    },
    update_products_design_files_item: {
      data: 'update_products_design_files_input',
    },
    update_products_content_items: {
      filter: 'products_content_filter',
      data: 'update_products_content_input',
    },
    update_products_content_item: {
      data: 'update_products_content_input',
    },
    update_stages_items: {
      filter: 'stages_filter',
      data: 'update_stages_input',
    },
    update_stages_item: {
      data: 'update_stages_input',
    },
    delete_brands_items: {},
    delete_brands_item: {},
    delete_brands_users_items: {},
    delete_brands_users_item: {},
    delete_users_items: {},
    delete_users_item: {},
    delete_producers_items: {},
    delete_producers_item: {},
    delete_producers_production_materials_items: {},
    delete_producers_production_materials_item: {},
    delete_production_materials_items: {},
    delete_production_materials_item: {},
    delete_producers_production_methods_items: {},
    delete_producers_production_methods_item: {},
    delete_production_methods_items: {},
    delete_production_methods_item: {},
    delete_product_collaborators_items: {},
    delete_product_collaborators_item: {},
    delete_collaborator_roles_items: {},
    delete_collaborator_roles_item: {},
    delete_production_materials_production_methods_items: {},
    delete_production_materials_production_methods_item: {},
    delete_fulfillers_items: {},
    delete_fulfillers_item: {},
    delete_price_currencies_items: {},
    delete_price_currencies_item: {},
    delete_stage_items: {},
    delete_stage_item: {},
    delete_products_files_items: {},
    delete_products_files_item: {},
    delete_products_production_methods_items: {},
    delete_products_production_methods_item: {},
    delete_skills_items: {},
    delete_skills_item: {},
    delete_users_skills_items: {},
    delete_users_skills_item: {},
    delete_products_items: {},
    delete_products_item: {},
    delete_products_production_materials_items: {},
    delete_products_production_materials_item: {},
    delete_products_wearables_items: {},
    delete_products_wearables_item: {},
    delete_file_formats_items: {},
    delete_file_formats_item: {},
    delete_products_design_files_items: {},
    delete_products_design_files_item: {},
    delete_products_content_items: {},
    delete_products_content_item: {},
    delete_stages_items: {},
    delete_stages_item: {},
  },
  create_brands_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    logo: 'create_directus_files_input',
    products: 'create_products_input',
    products_func: 'count_functionsInput',
    members: 'create_brands_users_input',
    members_func: 'count_functionsInput',
  },
  datetime_functionsInput: {},
  create_directus_files_input: {
    folder: 'create_directus_folders_input',
    uploaded_by: 'create_directus_users_input',
    uploaded_on: 'Date',
    uploaded_on_func: 'datetime_functionsInput',
    modified_by: 'create_directus_users_input',
    modified_on: 'Date',
    modified_on_func: 'datetime_functionsInput',
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    metadata: 'JSON',
    metadata_func: 'count_functionsInput',
  },
  create_directus_folders_input: {
    parent: 'create_directus_folders_input',
  },
  create_directus_users_input: {
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    avatar: 'create_directus_files_input',
    role: 'create_directus_roles_input',
    last_access: 'Date',
    last_access_func: 'datetime_functionsInput',
    auth_data: 'JSON',
    auth_data_func: 'count_functionsInput',
  },
  count_functionsInput: {},
  create_directus_roles_input: {
    users: 'create_directus_users_input',
    users_func: 'count_functionsInput',
  },
  create_products_input: {
    brand_id: 'create_brands_input',
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    fulfiller_id: 'create_fulfillers_input',
    price: 'create_price_currencies_input',
    producer_id: 'create_producers_input',
    release_date: 'Date',
    release_date_func: 'datetime_functionsInput',
    clo3d_file: 'create_directus_files_input',
    product_stage: 'create_stages_input',
    collaborators: 'create_product_collaborators_input',
    collaborators_func: 'count_functionsInput',
    production_methods: 'create_products_production_methods_input',
    production_methods_func: 'count_functionsInput',
    images: 'create_products_files_input',
    images_func: 'count_functionsInput',
    materials: 'create_products_production_materials_input',
    materials_func: 'count_functionsInput',
    wearable_files: 'create_products_wearables_input',
    wearable_files_func: 'count_functionsInput',
    content: 'create_products_content_input',
    content_func: 'count_functionsInput',
    design_files: 'create_products_design_files_input',
    design_files_func: 'count_functionsInput',
  },
  create_fulfillers_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
  },
  create_price_currencies_input: {},
  create_producers_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    production_materials_stocked: 'create_producers_production_materials_input',
    production_materials_stocked_func: 'count_functionsInput',
    production_methods: 'create_producers_production_methods_input',
    production_methods_func: 'count_functionsInput',
    supplied_materials: 'create_production_materials_input',
    supplied_materials_func: 'count_functionsInput',
  },
  create_producers_production_materials_input: {
    producers_id: 'create_producers_input',
    production_materials_id: 'create_production_materials_input',
  },
  create_production_materials_input: {
    color_palette: 'JSON',
    color_palette_func: 'count_functionsInput',
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    created_by: 'create_directus_users_input',
    size_guide: 'create_directus_files_input',
    supplier: 'create_producers_input',
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    production_methods: 'create_production_materials_production_methods_input',
    production_methods_func: 'count_functionsInput',
    stocked_at: 'create_producers_production_materials_input',
    stocked_at_func: 'count_functionsInput',
  },
  create_production_materials_production_methods_input: {
    production_materials_id: 'create_production_materials_input',
    production_methods_id: 'create_production_methods_input',
  },
  create_production_methods_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    producers: 'create_producers_production_methods_input',
    producers_func: 'count_functionsInput',
    production_materials:
      'create_production_materials_production_methods_input',
    production_materials_func: 'count_functionsInput',
  },
  create_producers_production_methods_input: {
    producers_id: 'create_producers_input',
    production_methods_id: 'create_production_methods_input',
  },
  create_stages_input: {},
  create_product_collaborators_input: {
    collaborator_id: 'create_users_input',
    product_id: 'create_products_input',
    role: 'create_collaborator_roles_input',
  },
  create_users_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    brands: 'create_brands_users_input',
    brands_func: 'count_functionsInput',
    products: 'create_product_collaborators_input',
    products_func: 'count_functionsInput',
    skills: 'create_users_skills_input',
    skills_func: 'count_functionsInput',
  },
  create_brands_users_input: {
    brands_id: 'create_brands_input',
    users_id: 'create_users_input',
  },
  create_users_skills_input: {
    skills_id: 'create_skills_input',
    users_id: 'create_users_input',
  },
  create_skills_input: {
    users: 'create_users_skills_input',
    users_func: 'count_functionsInput',
  },
  create_collaborator_roles_input: {},
  create_products_production_methods_input: {
    production_methods_id: 'create_production_methods_input',
    products_id: 'create_products_input',
  },
  create_products_files_input: {
    directus_files_id: 'create_directus_files_input',
    products_id: 'create_products_input',
  },
  create_products_production_materials_input: {
    products_id: 'create_products_input',
    production_materials_id: 'create_production_materials_input',
  },
  create_products_wearables_input: {
    products_id: 'create_products_input',
    directus_files_id: 'create_directus_files_input',
    file_format: 'create_file_formats_input',
  },
  create_file_formats_input: {},
  create_products_content_input: {
    products_id: 'create_products_input',
    directus_files_id: 'create_directus_files_input',
  },
  create_products_design_files_input: {
    products_id: 'create_products_input',
    directus_files_id: 'create_directus_files_input',
  },
  create_stage_input: {},
  update_brands_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    logo: 'update_directus_files_input',
    products: 'update_products_input',
    products_func: 'count_functionsInput',
    members: 'update_brands_users_input',
    members_func: 'count_functionsInput',
  },
  update_directus_files_input: {
    folder: 'update_directus_folders_input',
    uploaded_by: 'update_directus_users_input',
    uploaded_on: 'Date',
    uploaded_on_func: 'datetime_functionsInput',
    modified_by: 'update_directus_users_input',
    modified_on: 'Date',
    modified_on_func: 'datetime_functionsInput',
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    metadata: 'JSON',
    metadata_func: 'count_functionsInput',
  },
  update_directus_folders_input: {
    parent: 'update_directus_folders_input',
  },
  update_directus_users_input: {
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    avatar: 'update_directus_files_input',
    role: 'update_directus_roles_input',
    last_access: 'Date',
    last_access_func: 'datetime_functionsInput',
    auth_data: 'JSON',
    auth_data_func: 'count_functionsInput',
  },
  update_directus_roles_input: {
    users: 'update_directus_users_input',
    users_func: 'count_functionsInput',
  },
  update_products_input: {
    brand_id: 'update_brands_input',
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    fulfiller_id: 'update_fulfillers_input',
    price: 'update_price_currencies_input',
    producer_id: 'update_producers_input',
    release_date: 'Date',
    release_date_func: 'datetime_functionsInput',
    clo3d_file: 'update_directus_files_input',
    product_stage: 'update_stages_input',
    collaborators: 'update_product_collaborators_input',
    collaborators_func: 'count_functionsInput',
    production_methods: 'update_products_production_methods_input',
    production_methods_func: 'count_functionsInput',
    images: 'update_products_files_input',
    images_func: 'count_functionsInput',
    materials: 'update_products_production_materials_input',
    materials_func: 'count_functionsInput',
    wearable_files: 'update_products_wearables_input',
    wearable_files_func: 'count_functionsInput',
    content: 'update_products_content_input',
    content_func: 'count_functionsInput',
    design_files: 'update_products_design_files_input',
    design_files_func: 'count_functionsInput',
  },
  update_fulfillers_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
  },
  update_price_currencies_input: {},
  update_producers_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    production_materials_stocked: 'update_producers_production_materials_input',
    production_materials_stocked_func: 'count_functionsInput',
    production_methods: 'update_producers_production_methods_input',
    production_methods_func: 'count_functionsInput',
    supplied_materials: 'update_production_materials_input',
    supplied_materials_func: 'count_functionsInput',
  },
  update_producers_production_materials_input: {
    producers_id: 'update_producers_input',
    production_materials_id: 'update_production_materials_input',
  },
  update_production_materials_input: {
    color_palette: 'JSON',
    color_palette_func: 'count_functionsInput',
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    created_by: 'update_directus_users_input',
    size_guide: 'update_directus_files_input',
    supplier: 'update_producers_input',
    tags: 'JSON',
    tags_func: 'count_functionsInput',
    production_methods: 'update_production_materials_production_methods_input',
    production_methods_func: 'count_functionsInput',
    stocked_at: 'update_producers_production_materials_input',
    stocked_at_func: 'count_functionsInput',
  },
  update_production_materials_production_methods_input: {
    production_materials_id: 'update_production_materials_input',
    production_methods_id: 'update_production_methods_input',
  },
  update_production_methods_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    producers: 'update_producers_production_methods_input',
    producers_func: 'count_functionsInput',
    production_materials:
      'update_production_materials_production_methods_input',
    production_materials_func: 'count_functionsInput',
  },
  update_producers_production_methods_input: {
    producers_id: 'update_producers_input',
    production_methods_id: 'update_production_methods_input',
  },
  update_stages_input: {},
  update_product_collaborators_input: {
    collaborator_id: 'update_users_input',
    product_id: 'update_products_input',
    role: 'update_collaborator_roles_input',
  },
  update_users_input: {
    created_at: 'Date',
    created_at_func: 'datetime_functionsInput',
    brands: 'update_brands_users_input',
    brands_func: 'count_functionsInput',
    products: 'update_product_collaborators_input',
    products_func: 'count_functionsInput',
    skills: 'update_users_skills_input',
    skills_func: 'count_functionsInput',
  },
  update_brands_users_input: {
    brands_id: 'update_brands_input',
    users_id: 'update_users_input',
  },
  update_users_skills_input: {
    skills_id: 'update_skills_input',
    users_id: 'update_users_input',
  },
  update_skills_input: {
    users: 'update_users_skills_input',
    users_func: 'count_functionsInput',
  },
  update_collaborator_roles_input: {},
  update_products_production_methods_input: {
    production_methods_id: 'update_production_methods_input',
    products_id: 'update_products_input',
  },
  update_products_files_input: {
    directus_files_id: 'update_directus_files_input',
    products_id: 'update_products_input',
  },
  update_products_production_materials_input: {
    products_id: 'update_products_input',
    production_materials_id: 'update_production_materials_input',
  },
  update_products_wearables_input: {
    products_id: 'update_products_input',
    directus_files_id: 'update_directus_files_input',
    file_format: 'update_file_formats_input',
  },
  update_file_formats_input: {},
  update_products_content_input: {
    products_id: 'update_products_input',
    directus_files_id: 'update_directus_files_input',
  },
  update_products_design_files_input: {
    products_id: 'update_products_input',
    directus_files_id: 'update_directus_files_input',
  },
  update_stage_input: {},
};

export const ReturnTypes: Record<string, any> = {
  Query: {
    brands: 'brands',
    brands_by_id: 'brands',
    brands_aggregated: 'brands_aggregated',
    brands_users: 'brands_users',
    brands_users_by_id: 'brands_users',
    brands_users_aggregated: 'brands_users_aggregated',
    users: 'users',
    users_by_id: 'users',
    users_aggregated: 'users_aggregated',
    producers: 'producers',
    producers_by_id: 'producers',
    producers_aggregated: 'producers_aggregated',
    producers_production_materials: 'producers_production_materials',
    producers_production_materials_by_id: 'producers_production_materials',
    producers_production_materials_aggregated:
      'producers_production_materials_aggregated',
    production_materials: 'production_materials',
    production_materials_by_id: 'production_materials',
    production_materials_aggregated: 'production_materials_aggregated',
    producers_production_methods: 'producers_production_methods',
    producers_production_methods_by_id: 'producers_production_methods',
    producers_production_methods_aggregated:
      'producers_production_methods_aggregated',
    production_methods: 'production_methods',
    production_methods_by_id: 'production_methods',
    production_methods_aggregated: 'production_methods_aggregated',
    product_collaborators: 'product_collaborators',
    product_collaborators_by_id: 'product_collaborators',
    product_collaborators_aggregated: 'product_collaborators_aggregated',
    collaborator_roles: 'collaborator_roles',
    collaborator_roles_by_id: 'collaborator_roles',
    collaborator_roles_aggregated: 'collaborator_roles_aggregated',
    production_materials_production_methods:
      'production_materials_production_methods',
    production_materials_production_methods_by_id:
      'production_materials_production_methods',
    production_materials_production_methods_aggregated:
      'production_materials_production_methods_aggregated',
    fulfillers: 'fulfillers',
    fulfillers_by_id: 'fulfillers',
    fulfillers_aggregated: 'fulfillers_aggregated',
    price_currencies: 'price_currencies',
    price_currencies_by_id: 'price_currencies',
    price_currencies_aggregated: 'price_currencies_aggregated',
    stage: 'stage',
    stage_by_id: 'stage',
    stage_aggregated: 'stage_aggregated',
    products_files: 'products_files',
    products_files_by_id: 'products_files',
    products_files_aggregated: 'products_files_aggregated',
    products_production_methods: 'products_production_methods',
    products_production_methods_by_id: 'products_production_methods',
    products_production_methods_aggregated:
      'products_production_methods_aggregated',
    skills: 'skills',
    skills_by_id: 'skills',
    skills_aggregated: 'skills_aggregated',
    users_skills: 'users_skills',
    users_skills_by_id: 'users_skills',
    users_skills_aggregated: 'users_skills_aggregated',
    products: 'products',
    products_by_id: 'products',
    products_aggregated: 'products_aggregated',
    products_production_materials: 'products_production_materials',
    products_production_materials_by_id: 'products_production_materials',
    products_production_materials_aggregated:
      'products_production_materials_aggregated',
    products_wearables: 'products_wearables',
    products_wearables_by_id: 'products_wearables',
    products_wearables_aggregated: 'products_wearables_aggregated',
    file_formats: 'file_formats',
    file_formats_by_id: 'file_formats',
    file_formats_aggregated: 'file_formats_aggregated',
    products_design_files: 'products_design_files',
    products_design_files_by_id: 'products_design_files',
    products_design_files_aggregated: 'products_design_files_aggregated',
    products_content: 'products_content',
    products_content_by_id: 'products_content',
    products_content_aggregated: 'products_content_aggregated',
    stages: 'stages',
    stages_by_id: 'stages',
    stages_aggregated: 'stages_aggregated',
  },
  brands: {
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    description: 'String',
    discord_url: 'String',
    eth_address: 'String',
    id: 'ID',
    logo: 'directus_files',
    name: 'String',
    twitter_url: 'String',
    website_url: 'String',
    notion_id: 'String',
    products: 'products',
    products_func: 'count_functions',
    members: 'brands_users',
    members_func: 'count_functions',
  },
  Date: `scalar.Date` as const,
  datetime_functions: {
    year: 'Int',
    month: 'Int',
    week: 'Int',
    day: 'Int',
    weekday: 'Int',
    hour: 'Int',
    minute: 'Int',
    second: 'Int',
  },
  directus_files: {
    id: 'ID',
    storage: 'String',
    filename_disk: 'String',
    filename_download: 'String',
    title: 'String',
    type: 'String',
    folder: 'directus_folders',
    uploaded_by: 'directus_users',
    uploaded_on: 'Date',
    uploaded_on_func: 'datetime_functions',
    modified_by: 'directus_users',
    modified_on: 'Date',
    modified_on_func: 'datetime_functions',
    charset: 'String',
    filesize: 'String',
    width: 'Int',
    height: 'Int',
    duration: 'Int',
    embed: 'String',
    description: 'String',
    location: 'String',
    tags: 'JSON',
    tags_func: 'count_functions',
    metadata: 'JSON',
    metadata_func: 'count_functions',
  },
  directus_folders: {
    id: 'ID',
    name: 'String',
    parent: 'directus_folders',
  },
  directus_users: {
    id: 'ID',
    first_name: 'String',
    last_name: 'String',
    email: 'String',
    password: 'String',
    location: 'String',
    title: 'String',
    description: 'String',
    tags: 'JSON',
    tags_func: 'count_functions',
    avatar: 'directus_files',
    language: 'String',
    theme: 'String',
    tfa_secret: 'String',
    status: 'String',
    role: 'directus_roles',
    token: 'String',
    last_access: 'Date',
    last_access_func: 'datetime_functions',
    last_page: 'String',
    provider: 'String',
    external_identifier: 'String',
    auth_data: 'JSON',
    auth_data_func: 'count_functions',
    email_notifications: 'Boolean',
  },
  JSON: `scalar.JSON` as const,
  count_functions: {
    count: 'Int',
  },
  directus_roles: {
    id: 'ID',
    name: 'String',
    icon: 'String',
    description: 'String',
    ip_access: 'String',
    enforce_tfa: 'Boolean',
    admin_access: 'Boolean',
    app_access: 'Boolean',
    users: 'directus_users',
    users_func: 'count_functions',
  },
  products: {
    brand_id: 'brands',
    brand_reward_share: 'Int',
    collaborator_reward_share: 'Int',
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    description: 'String',
    discord_channel_id: 'String',
    fulfiller_id: 'fulfillers',
    id: 'ID',
    name: 'String',
    notion_id: 'String',
    price: 'price_currencies',
    producer_id: 'producers',
    production_cost: 'Float',
    quantity: 'String',
    sale_type: 'String',
    shopify_id: 'String',
    status: 'String',
    season: 'Int',
    release_date: 'Date',
    release_date_func: 'datetime_functions',
    clo3d_file: 'directus_files',
    product_stage: 'stages',
    collaborators: 'product_collaborators',
    collaborators_func: 'count_functions',
    production_methods: 'products_production_methods',
    production_methods_func: 'count_functions',
    images: 'products_files',
    images_func: 'count_functions',
    materials: 'products_production_materials',
    materials_func: 'count_functions',
    wearable_files: 'products_wearables',
    wearable_files_func: 'count_functions',
    content: 'products_content',
    content_func: 'count_functions',
    design_files: 'products_design_files',
    design_files_func: 'count_functions',
  },
  fulfillers: {
    address: 'String',
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    email: 'String',
    eth_address: 'String',
    id: 'ID',
    name: 'String',
    website_url: 'String',
  },
  price_currencies: {
    amount: 'Int',
    currency: 'String',
    id: 'ID',
  },
  producers: {
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    email: 'String',
    eth_address: 'String',
    id: 'ID',
    name: 'String',
    shipping_address: 'String',
    production_materials_stocked: 'producers_production_materials',
    production_materials_stocked_func: 'count_functions',
    production_methods: 'producers_production_methods',
    production_methods_func: 'count_functions',
    supplied_materials: 'production_materials',
    supplied_materials_func: 'count_functions',
  },
  producers_production_materials: {
    id: 'ID',
    producers_id: 'producers',
    production_materials_id: 'production_materials',
    quantity: 'Int',
  },
  production_materials: {
    base_price: 'Int',
    color_palette: 'JSON',
    color_palette_func: 'count_functions',
    composition: 'String',
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    created_by: 'directus_users',
    description: 'String',
    gender: 'String',
    id: 'ID',
    name: 'String',
    neck_tag: 'Boolean',
    rating: 'String',
    size_guide: 'directus_files',
    supplier: 'producers',
    tags: 'JSON',
    tags_func: 'count_functions',
    production_methods: 'production_materials_production_methods',
    production_methods_func: 'count_functions',
    stocked_at: 'producers_production_materials',
    stocked_at_func: 'count_functions',
  },
  production_materials_production_methods: {
    id: 'ID',
    production_materials_id: 'production_materials',
    production_methods_id: 'production_methods',
  },
  production_methods: {
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    description: 'String',
    id: 'ID',
    name: 'String',
    producers: 'producers_production_methods',
    producers_func: 'count_functions',
    production_materials: 'production_materials_production_methods',
    production_materials_func: 'count_functions',
  },
  producers_production_methods: {
    id: 'ID',
    producers_id: 'producers',
    production_methods_id: 'production_methods',
  },
  stages: {
    name: 'ID',
    sort: 'Int',
    description: 'String',
  },
  product_collaborators: {
    collaboration_share: 'Int',
    collaborator_id: 'users',
    id: 'ID',
    product_id: 'products',
    role: 'collaborator_roles',
  },
  users: {
    created_at: 'Date',
    created_at_func: 'datetime_functions',
    discord_handle: 'String',
    discord_id: 'String',
    eth_address: 'String',
    github_handle: 'String',
    id: 'ID',
    name: 'String',
    timezone: 'String',
    twitter_handle: 'String',
    brands: 'brands_users',
    brands_func: 'count_functions',
    products: 'product_collaborators',
    products_func: 'count_functions',
    skills: 'users_skills',
    skills_func: 'count_functions',
  },
  brands_users: {
    brands_id: 'brands',
    id: 'ID',
    users_id: 'users',
  },
  users_skills: {
    id: 'ID',
    skills_id: 'skills',
    users_id: 'users',
  },
  skills: {
    description: 'String',
    id: 'ID',
    name: 'String',
    users: 'users_skills',
    users_func: 'count_functions',
  },
  collaborator_roles: {
    description: 'String',
    id: 'ID',
    name: 'String',
  },
  products_production_methods: {
    id: 'ID',
    production_methods_id: 'production_methods',
    products_id: 'products',
  },
  products_files: {
    directus_files_id: 'directus_files',
    id: 'ID',
    products_id: 'products',
  },
  products_production_materials: {
    id: 'ID',
    products_id: 'products',
    production_materials_id: 'production_materials',
  },
  products_wearables: {
    id: 'ID',
    products_id: 'products',
    directus_files_id: 'directus_files',
    file_format: 'file_formats',
  },
  file_formats: {
    id: 'ID',
    mime_type: 'String',
    extension: 'String',
    description: 'String',
    name: 'String',
  },
  products_content: {
    id: 'ID',
    products_id: 'products',
    directus_files_id: 'directus_files',
  },
  products_design_files: {
    id: 'ID',
    products_id: 'products',
    directus_files_id: 'directus_files',
  },
  brands_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'brands_aggregated_count',
  },
  brands_aggregated_count: {
    created_at: 'Int',
    description: 'Int',
    discord_url: 'Int',
    eth_address: 'Int',
    id: 'Int',
    logo: 'Int',
    name: 'Int',
    twitter_url: 'Int',
    website_url: 'Int',
    notion_id: 'Int',
    products: 'Int',
    members: 'Int',
  },
  brands_users_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'brands_users_aggregated_count',
    avg: 'brands_users_aggregated_fields',
    sum: 'brands_users_aggregated_fields',
    countDistinct: 'brands_users_aggregated_fields',
    avgDistinct: 'brands_users_aggregated_fields',
    sumDistinct: 'brands_users_aggregated_fields',
    min: 'brands_users_aggregated_fields',
    max: 'brands_users_aggregated_fields',
  },
  brands_users_aggregated_count: {
    brands_id: 'Int',
    id: 'Int',
    users_id: 'Int',
  },
  brands_users_aggregated_fields: {
    id: 'Float',
  },
  users_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'users_aggregated_count',
  },
  users_aggregated_count: {
    created_at: 'Int',
    discord_handle: 'Int',
    discord_id: 'Int',
    eth_address: 'Int',
    github_handle: 'Int',
    id: 'Int',
    name: 'Int',
    timezone: 'Int',
    twitter_handle: 'Int',
    brands: 'Int',
    products: 'Int',
    skills: 'Int',
  },
  producers_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'producers_aggregated_count',
  },
  producers_aggregated_count: {
    created_at: 'Int',
    email: 'Int',
    eth_address: 'Int',
    id: 'Int',
    name: 'Int',
    shipping_address: 'Int',
    production_materials_stocked: 'Int',
    production_methods: 'Int',
    supplied_materials: 'Int',
  },
  producers_production_materials_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'producers_production_materials_aggregated_count',
    avg: 'producers_production_materials_aggregated_fields',
    sum: 'producers_production_materials_aggregated_fields',
    countDistinct: 'producers_production_materials_aggregated_fields',
    avgDistinct: 'producers_production_materials_aggregated_fields',
    sumDistinct: 'producers_production_materials_aggregated_fields',
    min: 'producers_production_materials_aggregated_fields',
    max: 'producers_production_materials_aggregated_fields',
  },
  producers_production_materials_aggregated_count: {
    id: 'Int',
    producers_id: 'Int',
    production_materials_id: 'Int',
    quantity: 'Int',
  },
  producers_production_materials_aggregated_fields: {
    id: 'Float',
    quantity: 'Float',
  },
  production_materials_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'production_materials_aggregated_count',
    avg: 'production_materials_aggregated_fields',
    sum: 'production_materials_aggregated_fields',
    countDistinct: 'production_materials_aggregated_fields',
    avgDistinct: 'production_materials_aggregated_fields',
    sumDistinct: 'production_materials_aggregated_fields',
    min: 'production_materials_aggregated_fields',
    max: 'production_materials_aggregated_fields',
  },
  production_materials_aggregated_count: {
    base_price: 'Int',
    color_palette: 'Int',
    composition: 'Int',
    created_at: 'Int',
    created_by: 'Int',
    description: 'Int',
    gender: 'Int',
    id: 'Int',
    name: 'Int',
    neck_tag: 'Int',
    rating: 'Int',
    size_guide: 'Int',
    supplier: 'Int',
    tags: 'Int',
    production_methods: 'Int',
    stocked_at: 'Int',
  },
  production_materials_aggregated_fields: {
    base_price: 'Float',
  },
  producers_production_methods_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'producers_production_methods_aggregated_count',
    avg: 'producers_production_methods_aggregated_fields',
    sum: 'producers_production_methods_aggregated_fields',
    countDistinct: 'producers_production_methods_aggregated_fields',
    avgDistinct: 'producers_production_methods_aggregated_fields',
    sumDistinct: 'producers_production_methods_aggregated_fields',
    min: 'producers_production_methods_aggregated_fields',
    max: 'producers_production_methods_aggregated_fields',
  },
  producers_production_methods_aggregated_count: {
    id: 'Int',
    producers_id: 'Int',
    production_methods_id: 'Int',
  },
  producers_production_methods_aggregated_fields: {
    id: 'Float',
  },
  production_methods_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'production_methods_aggregated_count',
  },
  production_methods_aggregated_count: {
    created_at: 'Int',
    description: 'Int',
    id: 'Int',
    name: 'Int',
    producers: 'Int',
    production_materials: 'Int',
  },
  product_collaborators_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'product_collaborators_aggregated_count',
    avg: 'product_collaborators_aggregated_fields',
    sum: 'product_collaborators_aggregated_fields',
    countDistinct: 'product_collaborators_aggregated_fields',
    avgDistinct: 'product_collaborators_aggregated_fields',
    sumDistinct: 'product_collaborators_aggregated_fields',
    min: 'product_collaborators_aggregated_fields',
    max: 'product_collaborators_aggregated_fields',
  },
  product_collaborators_aggregated_count: {
    collaboration_share: 'Int',
    collaborator_id: 'Int',
    id: 'Int',
    product_id: 'Int',
    role: 'Int',
  },
  product_collaborators_aggregated_fields: {
    collaboration_share: 'Float',
    role: 'Float',
  },
  collaborator_roles_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'collaborator_roles_aggregated_count',
    avg: 'collaborator_roles_aggregated_fields',
    sum: 'collaborator_roles_aggregated_fields',
    countDistinct: 'collaborator_roles_aggregated_fields',
    avgDistinct: 'collaborator_roles_aggregated_fields',
    sumDistinct: 'collaborator_roles_aggregated_fields',
    min: 'collaborator_roles_aggregated_fields',
    max: 'collaborator_roles_aggregated_fields',
  },
  collaborator_roles_aggregated_count: {
    description: 'Int',
    id: 'Int',
    name: 'Int',
  },
  collaborator_roles_aggregated_fields: {
    id: 'Float',
  },
  production_materials_production_methods_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'production_materials_production_methods_aggregated_count',
    avg: 'production_materials_production_methods_aggregated_fields',
    sum: 'production_materials_production_methods_aggregated_fields',
    countDistinct: 'production_materials_production_methods_aggregated_fields',
    avgDistinct: 'production_materials_production_methods_aggregated_fields',
    sumDistinct: 'production_materials_production_methods_aggregated_fields',
    min: 'production_materials_production_methods_aggregated_fields',
    max: 'production_materials_production_methods_aggregated_fields',
  },
  production_materials_production_methods_aggregated_count: {
    id: 'Int',
    production_materials_id: 'Int',
    production_methods_id: 'Int',
  },
  production_materials_production_methods_aggregated_fields: {
    id: 'Float',
  },
  fulfillers_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'fulfillers_aggregated_count',
  },
  fulfillers_aggregated_count: {
    address: 'Int',
    created_at: 'Int',
    email: 'Int',
    eth_address: 'Int',
    id: 'Int',
    name: 'Int',
    website_url: 'Int',
  },
  price_currencies_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'price_currencies_aggregated_count',
    avg: 'price_currencies_aggregated_fields',
    sum: 'price_currencies_aggregated_fields',
    countDistinct: 'price_currencies_aggregated_fields',
    avgDistinct: 'price_currencies_aggregated_fields',
    sumDistinct: 'price_currencies_aggregated_fields',
    min: 'price_currencies_aggregated_fields',
    max: 'price_currencies_aggregated_fields',
  },
  price_currencies_aggregated_count: {
    amount: 'Int',
    currency: 'Int',
    id: 'Int',
  },
  price_currencies_aggregated_fields: {
    amount: 'Float',
  },
  stage: {
    description: 'String',
    id: 'ID',
    name: 'String',
    sort: 'Int',
  },
  stage_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'stage_aggregated_count',
    avg: 'stage_aggregated_fields',
    sum: 'stage_aggregated_fields',
    countDistinct: 'stage_aggregated_fields',
    avgDistinct: 'stage_aggregated_fields',
    sumDistinct: 'stage_aggregated_fields',
    min: 'stage_aggregated_fields',
    max: 'stage_aggregated_fields',
  },
  stage_aggregated_count: {
    description: 'Int',
    id: 'Int',
    name: 'Int',
    sort: 'Int',
  },
  stage_aggregated_fields: {
    id: 'Float',
    sort: 'Float',
  },
  products_files_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_files_aggregated_count',
    avg: 'products_files_aggregated_fields',
    sum: 'products_files_aggregated_fields',
    countDistinct: 'products_files_aggregated_fields',
    avgDistinct: 'products_files_aggregated_fields',
    sumDistinct: 'products_files_aggregated_fields',
    min: 'products_files_aggregated_fields',
    max: 'products_files_aggregated_fields',
  },
  products_files_aggregated_count: {
    directus_files_id: 'Int',
    id: 'Int',
    products_id: 'Int',
  },
  products_files_aggregated_fields: {
    id: 'Float',
  },
  products_production_methods_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_production_methods_aggregated_count',
    avg: 'products_production_methods_aggregated_fields',
    sum: 'products_production_methods_aggregated_fields',
    countDistinct: 'products_production_methods_aggregated_fields',
    avgDistinct: 'products_production_methods_aggregated_fields',
    sumDistinct: 'products_production_methods_aggregated_fields',
    min: 'products_production_methods_aggregated_fields',
    max: 'products_production_methods_aggregated_fields',
  },
  products_production_methods_aggregated_count: {
    id: 'Int',
    production_methods_id: 'Int',
    products_id: 'Int',
  },
  products_production_methods_aggregated_fields: {
    id: 'Float',
  },
  skills_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'skills_aggregated_count',
  },
  skills_aggregated_count: {
    description: 'Int',
    id: 'Int',
    name: 'Int',
    users: 'Int',
  },
  users_skills_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'users_skills_aggregated_count',
    avg: 'users_skills_aggregated_fields',
    sum: 'users_skills_aggregated_fields',
    countDistinct: 'users_skills_aggregated_fields',
    avgDistinct: 'users_skills_aggregated_fields',
    sumDistinct: 'users_skills_aggregated_fields',
    min: 'users_skills_aggregated_fields',
    max: 'users_skills_aggregated_fields',
  },
  users_skills_aggregated_count: {
    id: 'Int',
    skills_id: 'Int',
    users_id: 'Int',
  },
  users_skills_aggregated_fields: {
    id: 'Float',
  },
  products_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_aggregated_count',
    avg: 'products_aggregated_fields',
    sum: 'products_aggregated_fields',
    countDistinct: 'products_aggregated_fields',
    avgDistinct: 'products_aggregated_fields',
    sumDistinct: 'products_aggregated_fields',
    min: 'products_aggregated_fields',
    max: 'products_aggregated_fields',
  },
  products_aggregated_count: {
    brand_id: 'Int',
    brand_reward_share: 'Int',
    collaborator_reward_share: 'Int',
    created_at: 'Int',
    description: 'Int',
    discord_channel_id: 'Int',
    fulfiller_id: 'Int',
    id: 'Int',
    name: 'Int',
    notion_id: 'Int',
    price: 'Int',
    producer_id: 'Int',
    production_cost: 'Int',
    quantity: 'Int',
    sale_type: 'Int',
    shopify_id: 'Int',
    status: 'Int',
    season: 'Int',
    release_date: 'Int',
    clo3d_file: 'Int',
    product_stage: 'Int',
    collaborators: 'Int',
    production_methods: 'Int',
    images: 'Int',
    materials: 'Int',
    wearable_files: 'Int',
    content: 'Int',
    design_files: 'Int',
  },
  products_aggregated_fields: {
    brand_reward_share: 'Float',
    collaborator_reward_share: 'Float',
    production_cost: 'Float',
    season: 'Float',
  },
  products_production_materials_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_production_materials_aggregated_count',
    avg: 'products_production_materials_aggregated_fields',
    sum: 'products_production_materials_aggregated_fields',
    countDistinct: 'products_production_materials_aggregated_fields',
    avgDistinct: 'products_production_materials_aggregated_fields',
    sumDistinct: 'products_production_materials_aggregated_fields',
    min: 'products_production_materials_aggregated_fields',
    max: 'products_production_materials_aggregated_fields',
  },
  products_production_materials_aggregated_count: {
    id: 'Int',
    products_id: 'Int',
    production_materials_id: 'Int',
  },
  products_production_materials_aggregated_fields: {
    id: 'Float',
  },
  products_wearables_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_wearables_aggregated_count',
    avg: 'products_wearables_aggregated_fields',
    sum: 'products_wearables_aggregated_fields',
    countDistinct: 'products_wearables_aggregated_fields',
    avgDistinct: 'products_wearables_aggregated_fields',
    sumDistinct: 'products_wearables_aggregated_fields',
    min: 'products_wearables_aggregated_fields',
    max: 'products_wearables_aggregated_fields',
  },
  products_wearables_aggregated_count: {
    id: 'Int',
    products_id: 'Int',
    directus_files_id: 'Int',
    file_format: 'Int',
  },
  products_wearables_aggregated_fields: {
    id: 'Float',
    file_format: 'Float',
  },
  file_formats_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'file_formats_aggregated_count',
    avg: 'file_formats_aggregated_fields',
    sum: 'file_formats_aggregated_fields',
    countDistinct: 'file_formats_aggregated_fields',
    avgDistinct: 'file_formats_aggregated_fields',
    sumDistinct: 'file_formats_aggregated_fields',
    min: 'file_formats_aggregated_fields',
    max: 'file_formats_aggregated_fields',
  },
  file_formats_aggregated_count: {
    id: 'Int',
    mime_type: 'Int',
    extension: 'Int',
    description: 'Int',
    name: 'Int',
  },
  file_formats_aggregated_fields: {
    id: 'Float',
  },
  products_design_files_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_design_files_aggregated_count',
    avg: 'products_design_files_aggregated_fields',
    sum: 'products_design_files_aggregated_fields',
    countDistinct: 'products_design_files_aggregated_fields',
    avgDistinct: 'products_design_files_aggregated_fields',
    sumDistinct: 'products_design_files_aggregated_fields',
    min: 'products_design_files_aggregated_fields',
    max: 'products_design_files_aggregated_fields',
  },
  products_design_files_aggregated_count: {
    id: 'Int',
    products_id: 'Int',
    directus_files_id: 'Int',
  },
  products_design_files_aggregated_fields: {
    id: 'Float',
  },
  products_content_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'products_content_aggregated_count',
    avg: 'products_content_aggregated_fields',
    sum: 'products_content_aggregated_fields',
    countDistinct: 'products_content_aggregated_fields',
    avgDistinct: 'products_content_aggregated_fields',
    sumDistinct: 'products_content_aggregated_fields',
    min: 'products_content_aggregated_fields',
    max: 'products_content_aggregated_fields',
  },
  products_content_aggregated_count: {
    id: 'Int',
    products_id: 'Int',
    directus_files_id: 'Int',
  },
  products_content_aggregated_fields: {
    id: 'Float',
  },
  stages_aggregated: {
    group: 'JSON',
    countAll: 'Int',
    count: 'stages_aggregated_count',
    avg: 'stages_aggregated_fields',
    sum: 'stages_aggregated_fields',
    countDistinct: 'stages_aggregated_fields',
    avgDistinct: 'stages_aggregated_fields',
    sumDistinct: 'stages_aggregated_fields',
    min: 'stages_aggregated_fields',
    max: 'stages_aggregated_fields',
  },
  stages_aggregated_count: {
    name: 'Int',
    sort: 'Int',
    description: 'Int',
  },
  stages_aggregated_fields: {
    sort: 'Float',
  },
  Mutation: {
    create_brands_items: 'brands',
    create_brands_item: 'brands',
    create_brands_users_items: 'brands_users',
    create_brands_users_item: 'brands_users',
    create_users_items: 'users',
    create_users_item: 'users',
    create_producers_items: 'producers',
    create_producers_item: 'producers',
    create_producers_production_materials_items:
      'producers_production_materials',
    create_producers_production_materials_item:
      'producers_production_materials',
    create_production_materials_items: 'production_materials',
    create_production_materials_item: 'production_materials',
    create_producers_production_methods_items: 'producers_production_methods',
    create_producers_production_methods_item: 'producers_production_methods',
    create_production_methods_items: 'production_methods',
    create_production_methods_item: 'production_methods',
    create_product_collaborators_items: 'product_collaborators',
    create_product_collaborators_item: 'product_collaborators',
    create_collaborator_roles_items: 'collaborator_roles',
    create_collaborator_roles_item: 'collaborator_roles',
    create_production_materials_production_methods_items:
      'production_materials_production_methods',
    create_production_materials_production_methods_item:
      'production_materials_production_methods',
    create_fulfillers_items: 'fulfillers',
    create_fulfillers_item: 'fulfillers',
    create_price_currencies_items: 'price_currencies',
    create_price_currencies_item: 'price_currencies',
    create_stage_items: 'stage',
    create_stage_item: 'stage',
    create_products_files_items: 'products_files',
    create_products_files_item: 'products_files',
    create_products_production_methods_items: 'products_production_methods',
    create_products_production_methods_item: 'products_production_methods',
    create_skills_items: 'skills',
    create_skills_item: 'skills',
    create_users_skills_items: 'users_skills',
    create_users_skills_item: 'users_skills',
    create_products_items: 'products',
    create_products_item: 'products',
    create_products_production_materials_items: 'products_production_materials',
    create_products_production_materials_item: 'products_production_materials',
    create_products_wearables_items: 'products_wearables',
    create_products_wearables_item: 'products_wearables',
    create_file_formats_items: 'file_formats',
    create_file_formats_item: 'file_formats',
    create_products_design_files_items: 'products_design_files',
    create_products_design_files_item: 'products_design_files',
    create_products_content_items: 'products_content',
    create_products_content_item: 'products_content',
    create_stages_items: 'stages',
    create_stages_item: 'stages',
    update_brands_items: 'brands',
    update_brands_item: 'brands',
    update_brands_users_items: 'brands_users',
    update_brands_users_item: 'brands_users',
    update_users_items: 'users',
    update_users_item: 'users',
    update_producers_items: 'producers',
    update_producers_item: 'producers',
    update_producers_production_materials_items:
      'producers_production_materials',
    update_producers_production_materials_item:
      'producers_production_materials',
    update_production_materials_items: 'production_materials',
    update_production_materials_item: 'production_materials',
    update_producers_production_methods_items: 'producers_production_methods',
    update_producers_production_methods_item: 'producers_production_methods',
    update_production_methods_items: 'production_methods',
    update_production_methods_item: 'production_methods',
    update_product_collaborators_items: 'product_collaborators',
    update_product_collaborators_item: 'product_collaborators',
    update_collaborator_roles_items: 'collaborator_roles',
    update_collaborator_roles_item: 'collaborator_roles',
    update_production_materials_production_methods_items:
      'production_materials_production_methods',
    update_production_materials_production_methods_item:
      'production_materials_production_methods',
    update_fulfillers_items: 'fulfillers',
    update_fulfillers_item: 'fulfillers',
    update_price_currencies_items: 'price_currencies',
    update_price_currencies_item: 'price_currencies',
    update_stage_items: 'stage',
    update_stage_item: 'stage',
    update_products_files_items: 'products_files',
    update_products_files_item: 'products_files',
    update_products_production_methods_items: 'products_production_methods',
    update_products_production_methods_item: 'products_production_methods',
    update_skills_items: 'skills',
    update_skills_item: 'skills',
    update_users_skills_items: 'users_skills',
    update_users_skills_item: 'users_skills',
    update_products_items: 'products',
    update_products_item: 'products',
    update_products_production_materials_items: 'products_production_materials',
    update_products_production_materials_item: 'products_production_materials',
    update_products_wearables_items: 'products_wearables',
    update_products_wearables_item: 'products_wearables',
    update_file_formats_items: 'file_formats',
    update_file_formats_item: 'file_formats',
    update_products_design_files_items: 'products_design_files',
    update_products_design_files_item: 'products_design_files',
    update_products_content_items: 'products_content',
    update_products_content_item: 'products_content',
    update_stages_items: 'stages',
    update_stages_item: 'stages',
    delete_brands_items: 'delete_many',
    delete_brands_item: 'delete_one',
    delete_brands_users_items: 'delete_many',
    delete_brands_users_item: 'delete_one',
    delete_users_items: 'delete_many',
    delete_users_item: 'delete_one',
    delete_producers_items: 'delete_many',
    delete_producers_item: 'delete_one',
    delete_producers_production_materials_items: 'delete_many',
    delete_producers_production_materials_item: 'delete_one',
    delete_production_materials_items: 'delete_many',
    delete_production_materials_item: 'delete_one',
    delete_producers_production_methods_items: 'delete_many',
    delete_producers_production_methods_item: 'delete_one',
    delete_production_methods_items: 'delete_many',
    delete_production_methods_item: 'delete_one',
    delete_product_collaborators_items: 'delete_many',
    delete_product_collaborators_item: 'delete_one',
    delete_collaborator_roles_items: 'delete_many',
    delete_collaborator_roles_item: 'delete_one',
    delete_production_materials_production_methods_items: 'delete_many',
    delete_production_materials_production_methods_item: 'delete_one',
    delete_fulfillers_items: 'delete_many',
    delete_fulfillers_item: 'delete_one',
    delete_price_currencies_items: 'delete_many',
    delete_price_currencies_item: 'delete_one',
    delete_stage_items: 'delete_many',
    delete_stage_item: 'delete_one',
    delete_products_files_items: 'delete_many',
    delete_products_files_item: 'delete_one',
    delete_products_production_methods_items: 'delete_many',
    delete_products_production_methods_item: 'delete_one',
    delete_skills_items: 'delete_many',
    delete_skills_item: 'delete_one',
    delete_users_skills_items: 'delete_many',
    delete_users_skills_item: 'delete_one',
    delete_products_items: 'delete_many',
    delete_products_item: 'delete_one',
    delete_products_production_materials_items: 'delete_many',
    delete_products_production_materials_item: 'delete_one',
    delete_products_wearables_items: 'delete_many',
    delete_products_wearables_item: 'delete_one',
    delete_file_formats_items: 'delete_many',
    delete_file_formats_item: 'delete_one',
    delete_products_design_files_items: 'delete_many',
    delete_products_design_files_item: 'delete_one',
    delete_products_content_items: 'delete_many',
    delete_products_content_item: 'delete_one',
    delete_stages_items: 'delete_many',
    delete_stages_item: 'delete_one',
  },
  delete_many: {
    ids: 'ID',
  },
  delete_one: {
    id: 'ID',
  },
};

export const Ops = {
  query: 'Query' as const,
  mutation: 'Mutation' as const,
};
