name: Expo Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: ${{ false }} # disable for now
    #    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Deploy To Expo
        run: yarn deploy
