name: MF App CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install packages
        run: yarn --frozen-lockfile
        env:
          CI: true

      - name: Typechecking
        run: yarn typecheck
        env:
          CI: true

      - name: Linting
        run: yarn lint
        env:
          CI: true

      - name: Testing
        run: yarn test --ci --coverage
        env:
          CI: true
  build:
    name: Web Build
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install packages
        run: yarn --frozen-lockfile
        env:
          CI: true

      - name: Build NextJS App
        run: yarn build
        env:
          CI: true
